char* text_ro[] = {
"MENIU BAZÃ",
"Cod#" xstr(code0_in),
"Func?ionare electrolizã#" xstr(btr_art_t),
"Configurare aparat#300",
	"Tip instala?ie,g/h#" xstr(anl_typ_t),
	"Adresã bus#" xstr(sh_adr),
	"Contrast#" xstr(contr),
	"Formare val.medie#" xstr(mttl),
	"Tehnicã mãsurã#" xstr(msr_t),
"Calibrare#301",
	"Calibrare sondã clor#302",
		"Val. mãsurã,mg/l#" xstr(cl_val_ix),
		"Pantã,mV#" xstr(cl_sth_in),
		"Tensiune intrare,mV#" xstr(cl_mv_ix),
		"Memorare Uein:#" xstr(set_nt),
		"Uein memorat,mV#" xstr(uin_saved_ix),
		"Punct nul,mV#" xstr(cl_mv0_in),
		"setare punct nul#" xstr(set_nt),
		"Valoare-DPD,mg/l#" xstr(cl_dpd_in),
		"Reset calibrare #" xstr(set_nt),
		"Final AER în, Min#" xstr(aer_min_ix),
		"Calibrarea nu e posibilã",
	"Calibrare pH#303",
		"Val. mãsurã,pH#" xstr(ph_ix),
		"Pantã,mV/pH#" xstr(ph_sth_in),
		"Punct nul,mV#" xstr(ph_null_in),
		"Tensiune intrare,mV#" xstr(ph_mv_ix),
		"Calibrare pH4/7#" xstr(ph_dpd2_in),
		"Reset calibrare #" xstr(set_nt),
"Val neces tehnicã mãsurã#304",
	"Delay conectare,Min#" xstr(on_dly),
	"Val necesare Cl2#305",
		"Val necesare CL2#306",
			"Valoare alarmã sus,mg/l#" xstr(cl_alr_ob),
			"Val avertizare sus,mg/l#" xstr(cl_wr_ob),
			"Val. necesarã,mg/l#" xstr(cl_soll),
			"Val. avertiz. jos,mg/l#" xstr(cl_wr_un),
			"Valoare alarmã jos,mg/l#" xstr(cl_alr_un),
			"Delay alarmã,Min#" xstr(cl_alr_dly),
		"Reglare CL2#307",
			"Interval-P,mg/l#" xstr(cl_p),
			"Timp de ajustare,Sek#" xstr(cl_i),
			"Histerezã,mg/l#" xstr(cl_hys),
		"Setãri-Dozare#308",
			"Dozare const. man. ,Min#" xstr(cl_man_dos),
			"Pornire dozare temporarã#" xstr(set_nt),
			"Monitorizare timp dozare,Min#" xstr(cl_dos_watch),
	"Valori pH#309",
		"Val necesare pH#310",
			"Valoare alarmã sus,pH#" xstr(ph_alr_ob),
			"Val avertizare sus,pH#" xstr(ph_wr_ob),
			"Val. necesarã,pH#" xstr(ph_soll),
			"Val. avertiz. jos,pH#" xstr(ph_wr_un),
			"Valoare alarmã jos,pH#" xstr(ph_alr_un),
			"Delay alarmã,Min#" xstr(alr_dly_ph),
		"Reglare pH#311",
			"Interval-P,pH#" xstr(ph_p),
			"Histerezã,pH#" xstr(ph_hys),
			"Timp de ajustare,Sek#" xstr(ph_zi),
			"Bandã moartã,pH#" xstr(totband_ph),
		"Setãri-Dozare#312",
			"Dozare const. man. ,Min#" xstr(ph_man_dos),
			"Pornire dozare temporarã#" xstr(set_nt),
			"Monitorizare timp dozare,Min#" xstr(ph_dos_watch),
	"Redox#313",
		"Val. necesar Redox#314",
			"Val. mãsurã,mV#" xstr(rx_ix),
			"Val. necesarã,mV#" xstr(rx_soll),
			"Val. avertiz. jos,mV#" xstr(rx_wr_un),
			"Valoare alarmã jos,mV#" xstr(rx_alr_un),
			"Delay alarmã,Min#" xstr(alr_dly_rx),
		"Reglare Redox#315",
			"Interval-P,mV#" xstr(rx_p),
			"Histerezã,mV#" xstr(rx_hys),
		"Setãri-Dozare#316",
			"Dozare const. man. ,Min#" xstr(rx_man_dos),
			"Pornire dozare temporarã#" xstr(set_nt),
			"Monitorizare timp dozare,Min#" xstr(rx_dos_watch),
	"Monitorizare apã mãsurã#317",
		"Tip#" xstr(mw_art_t),
		"Flux,l/h#" xstr(fl_aktl_mw_ix),
		"Ratã flux,P/l#" xstr(fl_rate_mw),
		"flux minim,l/h#" xstr(min_fl_mw),
		"Compensare,l/h#" xstr(flow_komp),
	"Data ?i ora#318",
		"Ore#" xstr(std_1),
		"Minute#" xstr(min_1),
		"Zi#" xstr(day),
		"Lunã#" xstr(mon),
		"An#" xstr(year),
	"AER#319",
		"Ore#" xstr(asr_std),
		"Minute#" xstr(asr_min),
		"Contor AER pe zi#" xstr(asr_day),
		"AER pornire manualã#" xstr(set_nt),
	"Temperaturã#320",
		"Compensare#" xstr(t_comp_t),
		"Compensare manualã,°C#" xstr(t_man_comp),
		"Corectare,°C#" xstr(t_korr),
"Val necesare electrolizã#321",
	"Electrolizã#322",
		"Dozare saramurã,%#" xstr(sole_dos),
		"Monitorizare reumplere saramurã,Min#" xstr(sole_nspw),
		"limitare temperaturã,°C#" xstr(temp_lim_t),
		"Temp. produs max.°C#" xstr(maxt),
		"Concentra?ie CL2,g/l#" xstr(cl_konz),
	"Vas produs#323",
		"Nivel supraplin,cm#" xstr(prodlev_ovfl),
		"Nivel max,cm#" xstr(prodlev_max),
		"Nivel min,cm#" xstr(prodlev_min),
"Releu#324",
	"Relais 3 [#325",
		"atribuire#" xstr(r3_strg_t),
		"Tip control#" xstr(r3_art_t),
		"Frecven?ã puls,P/h#" xstr(r3_frq),
		"Duratã perioadã,Sek#" xstr(r3_pp),
		"Impuls minim,Sek#" xstr(r3_min),
	"Relais 4 §#326",
		"atribuire#" xstr(r4_strg_t),
		"Tip control#" xstr(r4_art_t),
		"Frecven?ã puls,P/h#" xstr(r4_frq),
		"Duratã perioadã,Sek#" xstr(r4_pp),
		"Impuls minim,Sek#" xstr(r4_min),
"Limbã	#" xstr(sprache_t),
"Setãri fabricã#" xstr(set_nt),
"Date aparat#327",
	"Numãr aparat#" xstr(dev_nr_ix),
	"Stadiu software#" xstr(softver_in),
	"Data fabricãrii#" xstr(mdate_in),
	"Producãtor#328",
		"dinotec GmbH",
		"Spessartstr. 7",
		"D-63477 Maintal",
		"Tel:0049-(0)6109-6011-0",
		"Hotline:0049-(0)6109-6011-72",
		"www.dinotec.de",
		"service@dinotec.de",
"Frei",
"Instala?ie în func?iune",
"Alarmã",
"Scãdere pH",
"Ridicare pH",
"Redox",
"CL2",
"CL2,pH",
"CL2,pH,Redox",
"pH",
"pH,Redox",
"fãrã tehnicã mãsurã",
"30",
"60",
"90",
"150",
"200",
"300",
"setare",
"resetare",
"Oprit",
"Func?ionare normalã",
"Umplere vas saramurã",
"Umplere celulã",
"Umplere instala?ie",
"Instal pregãtitã",
"Vas saramurã umplut",
"Celulã plinã",
"Instala?ie plinã",
"Instala?ia produce",
"Regenerare dedurizator",
"Alarmã func?ionare aparat",
"Avertizare verif instal DES",
"Alarmã mãsurare nivel vas produs",
"Alarmã supraplin vas produs",
"Alarmã tensiune celulã prea micã",
"Alarmã curent prea mare",
"Alarmã curent prea mic",
"Alarmã flux prea mare",
"Alarmã flux prea mic",
"Alarmã nivel vas saramurã",
"ON-OFF",
"Frecven?ã puls",
"Pauzã-Puls",
"Da",
"Nu",
"manual",
"Automat",
"Avertizare CL2 sus",
"Avertizare CL2 jos",
"Avertizare verif sondã-POT",
"Alarmã Cl2 prea mult",
"Alarmã Cl2 prea pu?in",
"Alarmã pH sus",
"Alarmã pH jos",
"Alarmã Redox",
"Avertizare Redox",
"Avertizare pH sus",
"Avertizare pH jos",
"Lipsã apã mãsurã",
"Contactor plutitor",
"Mãsurare flux",
"Stop dozare externã",
"Fãrã conexiune terminal comandã",
"Eroare pantã Cl2",
"Eroare pantã pH",
"Eroare punct nul",
"Canistra pH este goalã",
"Duratã dozare dezinfectare depã?itã ",
"Duratã dozare pH ridicare depã?itã",
"Duratã dozare pH scãdere depã?itã",
"Delay pornire activ",
"Dozare constantã dezinfectare fc?",
"Dozare contantã pH fc?",
"Nivel reglare dezinfectare depã?it",
"Nivel reglare dezinfectare sub limitã",
"Nivel reglare pH depã?it",
"Nivel reglare pH sub limitã ",
"Alarmã temparaturã produs prea mare",
"Avertizare temp produs mare",
"Avertizare temp produs mic",
"Alarmã tensiune celulã prea micã",
"Pur ?i simplu apa perfectã!",
"Românã",
"Englezã",
"Francezã",
"Spaniolã",
"Polonezã",
"Ucraineanã",
"Rusã",
"Italianã",
"Cehã",
"Slovenã",
"Croatã",
"Ungarã",
"Românã",
"Olandezã",
"Sârbã",
};