char* text_sr[] = {
"GLAVNI_MENI",
"Kod#" xstr(code0_in),
"Pogon elektrolizera#" xstr(btr_art_t),
"Konfiguracija_ureðaja#300",
	"Tip ureðaja,g/h#" xstr(anl_typ_t),
	"Bus adresa#" xstr(sh_adr),
	"Kontrast#" xstr(contr),
	"U proseku#" xstr(mttl),
	"Merna tehnika#" xstr(msr_t),
"Kalibracija#301",
	"Kalibracija elektrode za hlor#302",
		"Merna vrednost,mg/l#" xstr(cl_val_ix),
		"Nagib,mV#" xstr(cl_sth_in),
		"Ulazni_napon,mV#" xstr(cl_mv_ix),
		"Saèuvati Uein:#" xstr(set_nt),
		"Uein saèuvati,mV#" xstr(uin_saved_ix),
		"Nulta_taèka,mV#" xstr(cl_mv0_in),
		"Podešavanje nulte taèke#" xstr(set_nt),
		"DPD-vrednost,mg/l#" xstr(cl_dpd_in),
		"Reset_kalibracije#" xstr(set_nt),
		"Završetak AER , Min#" xstr(aer_min_ix),
		"Kalibracija nije moguæa",
	"Kalibracija pH#303",
		"Merna vrednost,pH#" xstr(ph_ix),
		"Nagib,mV/pH#" xstr(ph_sth_in),
		"Nulta_taèka,mV#" xstr(ph_null_in),
		"Ulazni_napon,mV#" xstr(ph_mv_ix),
		"Kalibracija pH4/7#" xstr(ph_dpd2_in),
		"Reset_kalibracije#" xstr(set_nt),
"željena vrednost merne opreme#304",
	"Odlaganje,Min#" xstr(on_dly),
	"željena vrednost Cl2#305",
		"željena vrednost CL2#306",
			"Vrednost alarma iznad,mg/l#" xstr(cl_alr_ob),
			"Upozoravajuæa vrednost je iznad,mg/l#" xstr(cl_wr_ob),
			"željena_vrednost,mg/l#" xstr(cl_soll),
			"Upozoravajuæa vrednost je ispod,mg/l#" xstr(cl_wr_un),
			"Vrednost alarma ispod,mg/l#" xstr(cl_alr_un),
			"Odlaganje_alarma,Min#" xstr(cl_alr_dly),
		"Regulacija CL2#307",
			"P-podruèje,mg/l#" xstr(cl_p),
			"Sastavni,Sek#" xstr(cl_i),
			"Histerezis,mg/l#" xstr(cl_hys),
		"Podešavanje-doziranja#308",
			"ruè. kontinuirano doziranje,Min#" xstr(cl_man_dos),
			"Prekid na kontinuiranog doziranja#" xstr(set_nt),
			"Nadzor vremena doziranja,Min#" xstr(cl_dos_watch),
	"pH vrednost#309",
		"željena vrednost pH#310",
			"Vrednost alarma iznad,pH#" xstr(ph_alr_ob),
			"Upozoravajuæa vrednost je iznad,pH#" xstr(ph_wr_ob),
			"željena_vrednost,pH#" xstr(ph_soll),
			"Upozoravajuæa vrednost je ispod,pH#" xstr(ph_wr_un),
			"Vrednost alarma ispod,pH#" xstr(ph_alr_un),
			"Odlaganje_alarma,Min#" xstr(alr_dly_ph),
		"Regulacija pH#311",
			"P-podruèje,pH#" xstr(ph_p),
			"Histerezis,pH#" xstr(ph_hys),
			"Sastavni,Sek#" xstr(ph_zi),
			"Prazno_podruèje,pH#" xstr(totband_ph),
		"Podešavanje-doziranja#312",
			"ruè. kontinuirano doziranje,Min#" xstr(ph_man_dos),
			"Prekid na kontinuiranog doziranja#" xstr(set_nt),
			"Nadzor vremena doziranja,Min#" xstr(ph_dos_watch),
	"Redox#313",
		"željena vrednost Redox#314",
			"Merna vrednost,mV#" xstr(rx_ix),
			"željena_vrednost,mV#" xstr(rx_soll),
			"Upozoravajuæa vrednost je ispod,mV#" xstr(rx_wr_un),
			"Vrednost alarma ispod,mV#" xstr(rx_alr_un),
			"Odlaganje_alarma,Min#" xstr(alr_dly_rx),
		"Regulacija Redox#315",
			"P-podruèje,mV#" xstr(rx_p),
			"Histerezis,mV#" xstr(rx_hys),
		"Podešavanje-doziranja#316",
			"ruè. kontinuirano doziranje,Min#" xstr(rx_man_dos),
			"Prekid na kontinuiranog doziranja#" xstr(set_nt),
			"Nadzor vremena doziranja,Min#" xstr(rx_dos_watch),
	"Nadzor_uzorkovane_vode#317",
		"šifra#" xstr(mw_art_t),
		"Protok,l/h#" xstr(fl_aktl_mw_ix),
		"Stepen protoka,P/l#" xstr(fl_rate_mw),
		"minimalni protok,l/h#" xstr(min_fl_mw),
		"Kompenzacija,l/h#" xstr(flow_komp),
	"Datum i vreme#318",
		"Sati#" xstr(std_1),
		"Minuti#" xstr(min_1),
		"Dan#" xstr(day),
		"Mesec#" xstr(mon),
		"Godina#" xstr(year),
	"AER#319",
		"Sati#" xstr(asr_std),
		"Minuti#" xstr(asr_min),
		"Kolièina AER po danu#" xstr(asr_day),
		"AER ruèno pokretanje#" xstr(set_nt),
	"Temperatura#320",
		"Kompenzacija#" xstr(t_comp_t),
		"Ruèna kompenzacija,°C#" xstr(t_man_comp),
		"Korekcija,°C#" xstr(t_korr),
"željena vrednost Elektrolizer#321",
	"Elektrolizer#322",
		"Doziranje soli,%#" xstr(sole_dos),
		"Nadzor soli,Min#" xstr(sole_nspw),
		"Temperaturni limit,°C#" xstr(temp_lim_t),
		"Max. temperatura proizvoda.°C#" xstr(maxt),
		"CL2-koncentracija,g/l#" xstr(cl_konz),
	"Proizvodni rezervoar#323",
		"Nivo prelivanja,cm#" xstr(prodlev_ovfl),
		"Max nivo,cm#" xstr(prodlev_max),
		"Min nivo,cm#" xstr(prodlev_min),
"Relej#324",
	"Relais 3 [#325",
		"Zadatak#" xstr(r3_strg_t),
		"Tip_regulatora#" xstr(r3_art_t),
		"Frekventni_impuls,P/h#" xstr(r3_frq),
		"Period_trajanje,Sek#" xstr(r3_pp),
		"Minimalni_impuls,Sek#" xstr(r3_min),
	"Relais 4 §#326",
		"Zadatak#" xstr(r4_strg_t),
		"Tip_regulatora#" xstr(r4_art_t),
		"Frekventni_impuls,P/h#" xstr(r4_frq),
		"Period_trajanje,Sek#" xstr(r4_pp),
		"Minimalni_impuls,Sek#" xstr(r4_min),
"Jezik#" xstr(sprache_t),
"Fabrièka_podešavanja#" xstr(set_nt),
"Datum_ureðaja#327",
	"Broj_ureðaja#" xstr(dev_nr_ix),
	"Verzija_softvera#" xstr(softver_in),
	"Datum_proizvodnje#" xstr(mdate_in),
	"Proizvodjaè#328",
		"dinotec GmbH",
		"Spessartstr. 7",
		"D-63477 Maintal",
		"Tel:0049-(0)6109-6011-0",
		"Hotline:0049-(0)6109-6011-72",
		"www.dinotec.de",
		"service@dinotec.de",
"Frei",
"Ureðaj je u radu",
"Alarm",
"ph smanjivanje",
"ph poveæavanje",
"Redox",
"CL2",
"CL2,pH",
"CL2,pH,Redox",
"pH",
"pH,Redox",
"bez merne opreme",
"30",
"60",
"90",
"150",
"200",
"300",
"odreðivanje",
"resetovanje",
"Iskljuèivanje",
"Normalan rad",
"Rezervoar slanice se puni",
"æelija se puni",
"Ureðaj se puni",
"Ureðaj je spreman",
"Rezervoar slanice je napunjen",
"æelija je napunjena",
"Ureðaj je popunjen",
"Ureðaj proizvodi",
"Regeneracija omekšivaèa",
"Alarm oprema u radu",
"Upozorenje DES-ureðaja proveriti",
"Alarm nivoa kod proizvod.rezervoara",
"Alarm prelivanje proizv.rezervoara",
"Alarm napon u æeliji je previsok",
"Alarm struja je previše jaka",
"Alarm struja je slaba",
"Alarm protok je previsok",
"Alarm protok je previše mali",
"Alarm nivoa kod rezerv.za slanicu",
"OD-DO",
"Frekventni_impuls",
"Puls-Pauza",
"Da",
"Ne",
"ruèno",
"automatski",
"Upozorenje CL2 iznad",
"Upozorenje ispod CL2",
"Upozorenje POT-elektrode proveriti",
"Alarm CL2 iznad",
"Alarm CL2 ispod",
"Alarm pH iznad",
"Alarm pH ispod",
"Alarm Redox",
"Upozorenje Redox",
"Upozorenje pH iznad",
"Upozorenje pH ispod",
"Manjak_uzorkovane_vode",
"Plivajuæi_prekidaè",
"Merenje protoka",
"Završetak spoljnog doziranja",
"Ne postoji veza sa upravljaèk.delom",
"Greška nagiba Cl2",
"Greška nagiba pH",
"Greška_kod_nulte_taèke",
"kanister pH je prazan",
"Prekoraèeno je doziranje dezinfic.",
"Prekor.je dozir.sredst.za poveæ.pH",
"Prekor.je dozir.sredst.za sman.pH",
"Odlaganje ukljuèivanja aktivirano",
"Kontinuirano dozir.dezinfic.u toku",
"Kontinuirano doziranje pH u toku",
"Granièna vrednost dezinfekc.iznad",
"Granièna vrednost dezinfekc.ispod",
"Granièna vrednost pH iznad",
"Granièna vrednost pH ispod",
"Alarm temperat.produkta previsoka",
"Upozorenje temper.produk.je visoka",
"Upozorenje temper.produk.je niska",
"Alarm napon u æeliji je prenizak",
"Uživanje u najèistijoj vodi",
"Nemaèki",
"Engleski",
"Francuski",
"španski",
"Poljski",
"Ukrajinski",
"Ruski",
"Italijanski",
"èeški",
"Slovenaèki",
"Hrvatski",
"Maðarski",
"Rumunski",
"Holandski",
"Srpski",
