enum {
/*   0 */ sh_adr,
/*   1 */ contr,
/*   2 */ on_dly,
/*   3 */ cl_alr_ob,
/*   4 */ cl_wr_ob,
/*   5 */ cl_soll,
/*   6 */ cl_wr_un,
/*   7 */ cl_alr_un,
/*   8 */ cl_alr_dly,
/*   9 */ cl_p,
/*  10 */ cl_i,
/*  11 */ cl_hys,
/*  12 */ cl_man_dos,
/*  13 */ cl_dos_watch,
/*  14 */ ph_alr_ob,
/*  15 */ ph_wr_ob,
/*  16 */ ph_soll,
/*  17 */ ph_wr_un,
/*  18 */ ph_alr_un,
/*  19 */ alr_dly_ph,
/*  20 */ ph_p,
/*  21 */ ph_hys,
/*  22 */ ph_zi,
/*  23 */ totband_ph,
/*  24 */ ph_man_dos,
/*  25 */ ph_dos_watch,
/*  26 */ rx_soll,
/*  27 */ rx_wr_un,
/*  28 */ rx_alr_un,
/*  29 */ alr_dly_rx,
/*  30 */ rx_p,
/*  31 */ rx_hys,
/*  32 */ rx_man_dos,
/*  33 */ rx_dos_watch,
/*  34 */ fl_rate_mw,
/*  35 */ min_fl_mw,
/*  36 */ flow_komp,
/*  37 */ std_int,
/*  38 */ min_int,
/*  39 */ day_int,
/*  40 */ mon_int,
/*  41 */ year_int,
/*  42 */ asr_std,
/*  43 */ asr_min,
/*  44 */ asr_day,
/*  45 */ t_man_comp,
/*  46 */ t_korr,
/*  47 */ sole_dos,
/*  48 */ sole_nspw,
/*  49 */ maxt,
/*  50 */ cl_konz,
/*  51 */ flow_ely,
/*  52 */ t0_korr,
/*  53 */ prodlev_ovfl,
/*  54 */ prodlev_max,
/*  55 */ prodlev_min,
/*  56 */ not_zeit,
/*  57 */ luft_vor,
/*  58 */ luft_nach,
/*  59 */ r3_frq,
/*  60 */ r3_pp,
/*  61 */ r3_min,
/*  62 */ r4_frq,
/*  63 */ r4_pp,
/*  64 */ r4_min,
/*  65 */ btr_art_t,
/*  66 */ anl_typ_t,
/*  67 */ msr_t,
/*  68 */ mgl_t,
/*  69 */ mw_art_t,
/*  70 */ t_comp_t,
/*  71 */ temp_lim_t,
/*  72 */ v_monitus_t,
/*  73 */ lev_art_t,
/*  74 */ not_btr_t,
/*  75 */ r3_strg_t,
/*  76 */ r3_art_t,
/*  77 */ r4_strg_t,
/*  78 */ r4_art_t,
/*  79 */ sprache_t,
/*  80 */ set_nt,
/*  81 */ code0_x,
/*  82 */ cl_sth_in,
/*  83 */ cl_mv0_in,
/*  84 */ cl_dpd_in,
/*  85 */ ph_sth_in,
/*  86 */ ph_null_in,
/*  87 */ ph_dpd2_in,
/*  88 */ mdate_in,
/*  89 */ U7_in,
/*  90 */ U4_in,
/*  91 */ cl_1_sth_in,
/*  92 */ komm_t,
/*  93 */ cl_val_ix,
/*  94 */ cl_mv_ix,
/*  95 */ uin_saved_ix,
/*  96 */ aer_min_ix,
/*  97 */ ph_ix,
/*  98 */ ph_mv_ix,
/*  99 */ rx_ix,
/* 100 */ fl_aktl_mw_ix,
/* 101 */ dev_nr_ix,
/* 102 */ softver_ix,
/* 103 */ soft_strg_ix,
/* 104 */ flow0_ix,
/* 105 */ flow0_alr_ob_ix,
/* 106 */ flow0_soll_ix,
/* 107 */ flow0_alr_un_ix,
/* 108 */ t0_ix,
/* 109 */ t1_ix,
/* 110 */ el_V_mv_ix,
/* 111 */ el_A_mv_ix,
/* 112 */ lev_prod_ix,
/* 113 */ sole_puls_ix,
/* 114 */ flow_komp_ix,
/* 115 */ cur_ix,
/* 116 */ wrteptr_ix,
/* 117 */ modbus_in,
/* 118 */ prv_ch0_ix,
/* 119 */ prv_ch1_ix,
/* 120 */ status_ix,
//------------------
/* 121 */ ssid_en,
/* 122 */ sign_en,
/* 123 */ conn_en,
/* 124 */ server_en,
/* 125 */ wreset_en,
/* 126 */ stat_1,
/* 127 */ stat_ely,
/* 128 */ ip_en
/**/
};

enum {bus_strom_prc=status_ix+1, bus_flow0_prc, bus_status, cl_ph_saved};

enum {
frei_txt=151, 
ventilator_txt, 
aimb_txt, 
alarm_txt, 
ph_down_txt,	
ph_up_txt,
redox_txt,
cl_txt,
cl_ph_txt,
cl_ph_rx_txt,
ph_txt,
ph_rx_txt,
no_msr_txt,
a30_txt,
a60_txt,
a90_txt,
a150_txt,
a200_txt,
a300_txt,
set_txt, 
reset_txt, 
aus_txt,
run_txt,
solefill_txt,
cellfill_txt, 
anl_fill_txt,
standby_txt,
solevoll_txt,
cellvoll_txt,
anl_voll_txt,
work_txt,
enth_txt,
h2_alr_txt,
warn_des_txt,
alr_prod_txt,
ovfl_txt,
alr_UH_txt,
alr_iH_txt,
alr_iL_txt,
alr_flH_txt, 
alr_flL_txt, 
alr_sole_txt,
an_aus_txt,
puls_frq_txt, 
puls_pause_txt,
ja_txt,
nein_txt,
man_txt,
auto_txt,
warn_ob_cl_txt, 
warn_un_cl_txt, 
warn_aer_txt,
alr_ob_cl_txt, 
alr_un_cl_txt, 
alr_ob_ph_txt,
alr_un_ph_txt,
alr_rx_txt,
warn_rx_txt,
warn_ob_ph_txt,
warn_un_ph_txt,
wass_mangl_txt,
clm_txt,
swimm_txt,
flow_txt,
ext_stop_txt,
no_connect_txt,
pot_sth_err_txt,
ph_sth_err_txt,
null_err_txt,
ph_leer_txt,
dos_des_ovfl_txt,
dos_phh_ovfl_txt,
dos_phs_ovfl_txt,
on_dly_txt,
ddos_des_txt,
ddos_ph_txt,
des_lim_up_txt,
des_lim_down_txt,
ph_lim_up_txt,
ph_lim_down_txt,
alr_t_txt,
wrn_tH_txt,
wrn_tL_txt,
alr_UL_txt,
ok_txt,
tank_leer_txt,
dos_aus_txt,
ely_aus_txt,
vent_vor_txt,
vent_nach_txt,
notbtr_txt,
mgl_1_txt,
mgl_10_txt,
start_vgang_txt,
sprachen_txt,
en_txt,
fr_txt,
sp_txt,
pl_txt,
ua_txt,
ru_txt,
it_txt,
cz_txt,
sl_txt,
co_txt,
hu_txt,
ro_txt,
nl_txt,
sr_txt,
modbus_txt=261, 
wlan_txt=262

};

enum {
m_rangeCL2_txt =  9,
CL_pH_txt     =  10,
calibr_txt    =  11,
cal_CL2_txt   =  12,
Uein_save_txt =  16,
Uein_saved_txt=  17,
U0_set_txt    =  19,
cal_rsCL_txt  =  21,
ende_AER_txt  =  22,
val_low1_txt  =  24,
val_low2_txt  =  25,
cal_pH_txt    =  26,
cal_rspH_txt  =  32,
soll_mess_txt =  33,	
soll_Cl2_txt  =  35,
ddosCl2_txt   =  49,
soll_pH_txt   =  51,
ddosPH_txt    =  66,
soll_rx_txt   =  68, 
ddosRX_txt    =  80,
flow_mess_txt =  84,	
flow_rate_txt =  85,	
flow_min_txt  =  86,	
flow_cmp_txt  =  87,	
datum_txt     =  88,	
aer_txt       =  94,	
aer_start_txt =  98,
t_kompens_txt = 100, 	
sole_dos_txt  = 105,	
cl_konz_txt   = 109,
prodlev_ovfl_txt = 115,	
prodlev_max_txt  = 116,	
prodlev_min_txt  = 117,	
notbetrieb_txt   = 118,	
notlaufzeit_txt  = 119,	
ventil_txt = 120,	
r3_art_txt    = 126,
r3_frq_txt    = 127,
r3_pp_txt     = 128,
r3_min_txt    = 129,
r4_art_txt    = 132,
r4_frq_txt    = 133,
r4_pp_txt     = 134,
r4_min_txt    = 135,
werk_rs_txt   = 137
};

enum {vbw_30, vbw_60, vbw_90, vbw_150, vbw_200, vbw_300};

enum{frei_rl, vent_rl, aimb_rl, alarm_rl, phdown_rl, phup_rl,rx_rl, cl_rl};

//~ enum {
//~ i_ob_alr,
//~ i_ob_wrn,
//~ i_soll,
//~ i_un_wrn,	
//~ i_un_alr,	
//~ sole_ms, 
//~ zelle_fill_sek,	
//~ anl_fill_sek,	
//~ zelle_fill_flow,
//~ sole_nachsp,
//~ i_anf		
//~ };
enum {
i_ob_alr,
i_soll,
i_un_alr,	
u_alr,	
u_max,	
sole_ms, 
zelle_fill_sek,	
anl_fill_sek,	
zelle_fill_flow,
sole_nachsp,
i_anf,
flow_l_h		
};

/*
enum {
EMPTY_CL     = 0x0001, 	// Leermeldung Desinfektion   
EMPTY_PHS    = 0x0002, 	// PH-Senken leer		   
EMPTY_PHH    = 0x0004, 	// PH-Heben leer   
EXT_STOP     = 0x0008, 	// Eingang Abschaltung der Dosierung   
FLOW0_FAIL   = 0x0010,	// Messwassermangel 		   
FLOW1_FAIL   = 0x0020, 		   
LED_CELL_BUS = 0x0040, 	//vom Bus LED_CELL einschalten		   
DOS_DES_AUS  = 0x0080,  // Abschaltung Dosiertechnik		   
//~ DOS_PH_AUS   = 0x0100, 		   
SCHWIMMER   = 0x0200, 		   
//~ REDOX_FAIL   = 0x0400, 		   
//~ PH_FAIL      = 0x0800, 		   
//~ TEMP0_FAIL   = 0x1000,  		   
//~ TEMP1_FAIL   = 0x2000  		   
POT_FAIL     = 0x1000  		   
};
*/
enum {
	rx_mv_min = 50,
	rx_mv_max = 950
};
