char* text_pl[] = {
"MENU g£ówne",
"kod#" xstr(code0_in),
"Praca Elektroliza#" xstr(btr_art_t),
"Konfiguracja urz¹dzenia#300",
	"Typ urz¹dzenia,g/h#" xstr(anl_typ_t),
	"Adres BUS#" xstr(sh_adr),
	"Kontrast#" xstr(contr),
	"Obliczanie œredniej#" xstr(mttl),
	"Technika pomiarowa#" xstr(msr_t),
"Kalibracja#301",
	"Kalibracja sondy chloru#302",
		"Wart. pomiar.,mg/l#" xstr(cl_val_ix),
		"Stromoœæ,mV#" xstr(cl_sth_in),
		"Napiêcie wejœciowe,mV#" xstr(cl_mv_ix),
		"Zapisz Uwe:#" xstr(set_nt),
		"Uwe zapisany,mV#" xstr(uin_saved_ix),
		"Punkt zerowy,mV#" xstr(cl_mv0_in),
		"Ustawianie punktu zerowego#" xstr(set_nt),
		"Wartoœæ DPD,mg/l#" xstr(cl_dpd_in),
		"Reset kalibracji#" xstr(set_nt),
		"Koniec ACE za, Min#" xstr(aer_min_ix),
		"Kalibracja_niemo¿liwa",
	"Kalibracja pH#303",
		"Wart. pomiar.,pH#" xstr(ph_ix),
		"Stromoœæ,mV/pH#" xstr(ph_sth_in),
		"Punkt zerowy,mV#" xstr(ph_null_in),
		"Napiêcie wejœciowe,mV#" xstr(ph_mv_ix),
		"Kalibracja pH 4/7#" xstr(ph_dpd2_in),
		"Reset kalibracji#" xstr(set_nt),
"Wartoœci zadane Technika pomiarowa#304",
	"OpóŸnianie w³¹czenia,Min#" xstr(on_dly),
	"Wartoœci zadane CL2#305",
		"Wartoœci zadane CL2#306",
			"Górna wartoœæ alarmowa,mg/l#" xstr(cl_alr_ob),
			"Górna wartoœæ ostrzegawcza,mg/l#" xstr(cl_wr_ob),
			"Wartoœæ zadana,mg/l#" xstr(cl_soll),
			"Dolna wartoœæ ostrzegawcza,mg/l#" xstr(cl_wr_un),
			"Dolna wartoœæ alarmowa,mg/l#" xstr(cl_alr_un),
			"OpóŸnienie alarmu,Min#" xstr(cl_alr_dly),
		"Regulacja CL2#307",
			"Zakres regulacji P,mg/l#" xstr(cl_p),
			"Czas ca³kowania,Sek#" xstr(cl_i),
			"Histereza,mg/l#" xstr(cl_hys),
		"Ustawienia dozowania#308",
			"Dozowanie ci¹g³e rêczne,Min#" xstr(cl_man_dos),
			"W³¹cz dozowanie ci¹g³e#" xstr(set_nt),
			"Kontrola czasu dozowania,Min#" xstr(cl_dos_watch),
	"Wartoœci pH#309",
		"Wartoœæi zadane pH#310",
			"Górna wartoœæ alarmowa,pH#" xstr(ph_alr_ob),
			"Górna wartoœæ ostrzegawcza,pH#" xstr(ph_wr_ob),
			"Wartoœæ zadana,pH#" xstr(ph_soll),
			"Dolna wartoœæ ostrzegawcza,pH#" xstr(ph_wr_un),
			"Dolna wartoœæ alarmowa,pH#" xstr(ph_alr_un),
			"OpóŸnienie alarmu,Min#" xstr(alr_dly_ph),
		"Regulacja pH#311",
			"Zakres regulacji P,pH#" xstr(ph_p),
			"Histereza,pH#" xstr(ph_hys),
			"Czas ca³kowania,Sek#" xstr(ph_zi),
			"Zakres martwy,pH#" xstr(totband_ph),
		"Ustawienia dozowania#312",
			"Dozowanie ci¹g³e rêczne,Min#" xstr(ph_man_dos),
			"W³¹cz dozowanie ci¹g³e#" xstr(set_nt),
			"Kontrola czasu dozowania,Min#" xstr(ph_dos_watch),
	"Redox#313",
		"Wartoœæi zadane redox#314",
			"Wart. pomiar.,mV#" xstr(rx_ix),
			"Wartoœæ zadana,mV#" xstr(rx_soll),
			"Dolna wartoœæ ostrzegawcza,mV#" xstr(rx_wr_un),
			"Dolna wartoœæ alarmowa,mV#" xstr(rx_alr_un),
			"OpóŸnienie alarmu,Min#" xstr(alr_dly_rx),
		"Regulacja Redox#315",
			"Zakres regulacji P,mV#" xstr(rx_p),
			"Histereza,mV#" xstr(rx_hys),
		"Ustawienia dozowania#316",
			"Dozowanie ci¹g³e rêczne,Min#" xstr(rx_man_dos),
			"W³¹cz dozowanie ci¹g³e#" xstr(set_nt),
			"Kontrola czasu dozowania,Min#" xstr(rx_dos_watch),
	"Kontrola wody pomiarowej#317",
		"Rodzaj#" xstr(mw_art_t),
		"Przep³yw,l/h#" xstr(fl_aktl_mw_ix),
		"WskaŸnik przep³ywu,P/l#" xstr(fl_rate_mw),
		"Minimalny przep³yw,l/h#" xstr(min_fl_mw),
		"Kompensacja,l/h#" xstr(flow_komp),
	"Data i czas#318",
		"Godziny#" xstr(std_1),
		"minuty#" xstr(min_1),
		"Dzieñ#" xstr(day),
		"miesi¹c#" xstr(mon),
		"rok#" xstr(year),
	"ACE#319",
		"Godziny#" xstr(asr_std),
		"minuty#" xstr(asr_min),
		"Liczba operacji ACE dziennie#" xstr(asr_day),
		"Rêczne w³¹czanie ACE#" xstr(set_nt),
	"Temperatura#320",
		"Kompensacja#" xstr(t_comp_t),
		"Kompensacja rêczna,°C#" xstr(t_man_comp),
		"Korekta,°C#" xstr(t_korr),
"Wartoœci zadane Elektroliza#321",
	"Elektroliza#322",
		"Dozowanie solanki,%#" xstr(sole_dos),
		"Kontrola zasilania solank¹,Min#" xstr(sole_nspw),
		"Ograniczanie temperatury,°C#" xstr(temp_lim_t),
		"Maks. temperatura produktu °C#" xstr(maxt),
		"Stê¿enie CL2,g/l#" xstr(cl_konz),
	"Zbiornik produktu#323",
		"Poziom przelewu,cm#" xstr(prodlev_ovfl),
		"Poziom maks.,cm#" xstr(prodlev_max),
		"Poziom min.,cm#" xstr(prodlev_min),
"PrzekaŸnik#324",
	"Relais 3 [#325",
		"Przyporz¹dkowanie#" xstr(r3_strg_t),
		"Rodzaj regulacji#" xstr(r3_art_t),
		"Czêstotliwoœæ impulsów,P/h#" xstr(r3_frq),
		"D³ugoœæ cyklu,Sek#" xstr(r3_pp),
		"Minimalny impuls,Sek#" xstr(r3_min),
	"Relais 4 §#326",
		"Przyporz¹dkowanie#" xstr(r4_strg_t),
		"Rodzaj regulacji#" xstr(r4_art_t),
		"Czêstotliwoœæ impulsów,P/h#" xstr(r4_frq),
		"D³ugoœæ cyklu,Sek#" xstr(r4_pp),
		"Minimalny impuls,Sek#" xstr(r4_min),
"Jêzyk#" xstr(sprache_t),
"Ustawienie fabryczne#" xstr(set_nt),
"Dane urz¹dzenia#327",
	"Numer urz¹dzenia#" xstr(dev_nr_ix),
	"Wersja oprogramow.#" xstr(softver_in),
	"Data produkcji#" xstr(mdate_in),
	"Producent#328",
		"dinotec GmbH",
		"Spessartstr. 7",
		"D-63477 Maintal",
		"Tel:0049-(0)6109-6011-0",
		"Hotline:0049-(0)6109-6011-72",
		"www.dinotec.de",
		"service@dinotec.de",
"Frei",
"Praca urz¹dzenia",
"Alarm",
"Obni¿anie pH",
"podnoszenie pH",
"Redox",
"CL2",
"CL2,pH",
"CL2,pH,Redox",
"pH",
"pH,Redox",
"Bez techniki pomiarowej",
"30",
"60",
"90",
"150",
"200",
"300",
"Ustaw",
"Cofnij",
"Wy³¹czone",
"Tryb normalny",
"Nape³nij zbiornik solanki",
"Nape³nij celê",
"Nape³nij urz¹dzenie",
"Urz¹dz. gotowe",
"Zbiornik solanki nape³niony",
"Cela nape³niona",
"Urz¹dzenie nape³nione",
"Urz¹dzenie produkuje",
"Zmiêkczacz zregenerowany",
"Alarm Instalacja",
"Ostrze¿enie SprawdŸ dezynfekcjê DES",
"Alarm Pomiar poziomu Zbior.produktu",
"Alarm Zbiornik produktu Przelew",
"Alarm Napiêcie celi za niskie",
"Alarm Pr¹d za wysoki",
"Alarm Pr¹d za niski",
"Alarm Przep³yw za wysoki",
"Alarm Przep³yw za niski",
"Alarm Poziom Zbiornik solanki",
"W³¹cz / Wy³¹cz",
"Czêstotliwoœæ impulsów",
"impuls / przerwa",
"tak",
"nie",
"rêczne",
"Automatycznie",
"Ostrze¿enie Wysoka wartoœæ CL2",
"Ostrze¿enie Niska wartoœæ CL2",
"Ostrze¿enie SprawdŸ sondê POT",
"Alarm CL2 Poziom górny",
"Alarm CL2 Poziom dolny",
"Alarm pH Poziom górny",
"Alarm pH Poziom dolny",
"Alarm Redox",
"Ostrze¿enie Redox",
"Ostrze¿enie górna wartoœæ pH",
"Ostrze¿enie dolna wartoœæ pH",
"Brak wody pomiar.",
"£¹cznik p³ywakowy",
"Pomiar przep³ywu",
"Zewnêtrzne zatrzymanie dozowania",
"Brak po³¹czenia ze sterownikiem",
"B³¹d nachylenia charakterystyki CL2",
"B³¹d nachylenia charakter.sondy pH ",
"B³¹d punktu zerowego",
"Kanister pH pusty",
"Czas dozow. dezynf. przekroczony",
"Czas dozow. podnosz. pH przekrocz",
"Czas dozow. obni¿. pH przekrocz.",
"OpóŸnianie w³¹czenia aktywne",
"Dzia³a dozowanie ci¹g³e",
"Dzia³a dozowanie ci¹g³e pH",
"Górna granica dezynf. przekrocz.",
"Dolna granica dezynf. przekrocz.",
"Górna granica pH przekroczona",
"Dolna granica pH przekroczona",
"Alarm Temperat.produktu za wysoka",
"Ostrze¿en.Temperat.produk.za wysoka",
"Ostrze¿en.Temperat.produk.za niska",
"Alarm Napiêcie celi za niskie",
"Po prostu ciesz siê czyst¹ wod¹!",
"Niemiecki",
"Angielski",
"Francuski",
"Hiszpañski",
"Polski",
"Ukraiñski",
"Rosyjski",
"W³oski",
"Czeski",
"S³oweñski",
"Chorwacki",
"Wêgierski",
"Rumuñski",
"Niederlandzki",
"Serbski",
};