char* text_hu[] = {
"Fõmenû",
"Kódok#" xstr(code0_in),
"Eletrolizis üzemel#" xstr(btr_art_t),
"Készülék felépítése#300",
	"Berendezés típusa,g/h#" xstr(anl_typ_t),
	"BUS cím#" xstr(sh_adr),
	"Kontraszt#" xstr(contr),
	"átlagérték számítás#" xstr(mttl),
	"Mérési lehetõségek#" xstr(msr_t),
"Kalibráció#301",
	"Klórszonda kalibráció#302",
		"Mér térték,mg/l#" xstr(cl_val_ix),
		"Meredékség,mV#" xstr(cl_sth_in),
		"Bemeneti feszültség,mV#" xstr(cl_mv_ix),
		"Tárolás U be:#" xstr(set_nt),
		"U be tárolva,mV#" xstr(uin_saved_ix),
		"Nullpont,mV#" xstr(cl_mv0_in),
		"Nullpont beállítás#" xstr(set_nt),
		"DPD-érték,mg/l#" xstr(cl_dpd_in),
		"Kalibráció visszaállítása#" xstr(set_nt),
		"AER vége be, Min#" xstr(aer_min_ix),
		"Kalibráció nem lehetséges",
	"kalibráció pH-szonda#303",
		"Mér térték,pH#" xstr(ph_ix),
		"Meredékség,mV/pH#" xstr(ph_sth_in),
		"Nullpont,mV#" xstr(ph_null_in),
		"Bemeneti feszültség,mV#" xstr(ph_mv_ix),
		"Kalibráció pH4/7#" xstr(ph_dpd2_in),
		"Kalibráció visszaállítása#" xstr(set_nt),
"Kívánt érték mérési lehetõségek#304",
	"bekapcsolási késleltetés,Min#" xstr(on_dly),
	"Kívánt érték Cl2#305",
		"Kívánt érték CL2#306",
			"Felsõ riadó érték,mg/l#" xstr(cl_alr_ob),
			"Figyelmeztetõ érték magas,mg/l#" xstr(cl_wr_ob),
			"Ideális érték,mg/l#" xstr(cl_soll),
			"Figyelmeztetõ érték alacsony,mg/l#" xstr(cl_wr_un),
			"Alsó Riadó érték ,mg/l#" xstr(cl_alr_un),
			"Riasztási késleltetés,Min#" xstr(cl_alr_dly),
		"Szabályozás CL2#307",
			"P-tartomány,mg/l#" xstr(cl_p),
			"Utánállítási idõ,Sek#" xstr(cl_i),
			"Hiszterézis ,mg/l#" xstr(cl_hys),
		"Adagolási beállítások#308",
			"Kézi folyamatos adagolás,Min#" xstr(cl_man_dos),
			"Folyamatos adagolást bekapcsolni#" xstr(set_nt),
			"Adagolási idõ felügyelete,Min#" xstr(cl_dos_watch),
	"pH értékek#309",
		"Ideális érték pH#310",
			"Felsõ riadó érték,pH#" xstr(ph_alr_ob),
			"Figyelmeztetõ érték magas,pH#" xstr(ph_wr_ob),
			"Ideális érték,pH#" xstr(ph_soll),
			"Figyelmeztetõ érték alacsony,pH#" xstr(ph_wr_un),
			"Alsó Riadó érték ,pH#" xstr(ph_alr_un),
			"Riasztási késleltetés,Min#" xstr(alr_dly_ph),
		"Szabályozás pH#311",
			"P-tartomány,pH#" xstr(ph_p),
			"Hiszterézis ,pH#" xstr(ph_hys),
			"Utánállítási idõ,Sek#" xstr(ph_zi),
			"Holt szakasz,pH#" xstr(totband_ph),
		"Adagolási beállítások#312",
			"Kézi folyamatos adagolás,Min#" xstr(ph_man_dos),
			"Folyamatos adagolást bekapcsolni#" xstr(set_nt),
			"Adagolási idõ felügyelete,Min#" xstr(ph_dos_watch),
	"Redox#313",
		"Ideális érték redox#314",
			"Mér térték,mV#" xstr(rx_ix),
			"Ideális érték,mV#" xstr(rx_soll),
			"Figyelmeztetõ érték alacsony,mV#" xstr(rx_wr_un),
			"Alsó Riadó érték ,mV#" xstr(rx_alr_un),
			"Riasztási késleltetés,Min#" xstr(alr_dly_rx),
		"Szabályozás Redox#315",
			"P-tartomány,mV#" xstr(rx_p),
			"Hiszterézis ,mV#" xstr(rx_hys),
		"Adagolási beállítások#316",
			"Kézi folyamatos adagolás,Min#" xstr(rx_man_dos),
			"Folyamatos adagolást bekapcsolni#" xstr(set_nt),
			"Adagolási idõ felügyelete,Min#" xstr(rx_dos_watch),
	"Mérõvíz mennyiség figyelés#317",
		"Cikkszám#" xstr(mw_art_t),
		"átfolyás,l/h#" xstr(fl_aktl_mw_ix),
		"átfolyási mennyiség,P/l#" xstr(fl_rate_mw),
		"minimális átfolyás,l/h#" xstr(min_fl_mw),
		"Kompenzáció,l/h#" xstr(flow_komp),
	"Dátum és idõ#318",
		"órák#" xstr(std_1),
		"Perc#" xstr(min_1),
		"Nap#" xstr(day),
		"Hónap#" xstr(mon),
		"év#" xstr(year),
	"AER#319",
		"órák#" xstr(asr_std),
		"Perc#" xstr(asr_min),
		"AER napi száma#" xstr(asr_day),
		"AER kézi indítása#" xstr(set_nt),
	"Hõmérséklet#320",
		"Kompenzáció#" xstr(t_comp_t),
		"Kézi kompenzáció,°C#" xstr(t_man_comp),
		"Korrekció,°C#" xstr(t_korr),
"Kívánt érték elektrolízis#321",
	"Elektrolizís#322",
		"Sólé adagolás,%#" xstr(sole_dos),
		"Sólé utánpótlás felügyelete,Min#" xstr(sole_nspw),
		"Hõmérsékletet behatárolni,°C#" xstr(temp_lim_t),
		"Max. termék hõmérséklet#" xstr(maxt),
		"CL2-koncentráció,g/l#" xstr(cl_konz),
	"Terméktartály#323",
		"Szint túltöltve,cm#" xstr(prodlev_ovfl),
		"Szint max.,cm#" xstr(prodlev_max),
		"Szint min.,cm#" xstr(prodlev_min),
"Relék#324",
	"Relais 3 [#325",
		"Hozzárendelés#" xstr(r3_strg_t),
		"Szabályozási forma#" xstr(r3_art_t),
		"Inpulzus_frekvencia,P/h#" xstr(r3_frq),
		"Periódusidõ,Sek#" xstr(r3_pp),
		"Minimum impulzus,Sek#" xstr(r3_min),
	"Relais 4 §#326",
		"Hozzárendelés#" xstr(r4_strg_t),
		"Szabályozási forma#" xstr(r4_art_t),
		"Inpulzus_frekvencia,P/h#" xstr(r4_frq),
		"Periódusidõ,Sek#" xstr(r4_pp),
		"Minimum impulzus,Sek#" xstr(r4_min),
"Nyelv#" xstr(sprache_t),
"Gyári beállítás#" xstr(set_nt),
"Készülékadatok#327",
	"Gyátási szám#" xstr(dev_nr_ix),
	"Software készítés ideje#" xstr(softver_in),
	"Gyártás ideje#" xstr(mdate_in),
	"Gyártó#328",
		"dinotec GmbH",
		"Spessartstr. 7",
		"D-63477 Maintal",
		"Tel:0049-(0)6109-6011-0",
		"Hotline:0049-(0)6109-6011-72",
		"www.dinotec.de",
		"service@dinotec.de",
"Frei",
"Berendezés üzemel",
"Riasztás",
"pH csökkentés",
"pH-emelés",
"Redox",
"CL2",
"CL2,pH",
"CL2,pH,Redox",
"pH",
"pH,Redox",
"Méréstechnika nélkül",
"30",
"60",
"90",
"150",
"200",
"300",
"elfogad/tárol",
"visszaállít",
"Lekapcsolva",
"Normálüzem",
"Sólé tartályt tölteni",
"Cellát tölteni",
"Berendezés töltése",
"A készülék kész",
"Sólé tartály feltöltve",
"Cella feltöltve",
"Berendezés feltöltve",
"Berendezés termel",
"Vízlágyítót regenerálni",
"Rendszer riasztás",
"Figyelmezt.DES ellenõrizni",
"Riasztás szintjelzés a terméktan.",
"Riasztás terméktank túltöltve",
"Riasztás calla hõmérsékl.túl magas",
"Riasztás túlfeszültség",
"Riasztás alacsony feszültség",
"Riasztás túl magas átfolyás",
"Riasztás túl alacson átfolyás",
"Riasztás sóléoldótrtály szintje",
"Be-Ki",
"Inpulzus_frekvencia",
"Impulzus_szünet",
"Igen",
"Nem",
"kézi",
"automatikus",
"Figyelmeztetés CL2 magas",
"Figyelmeztetés CL2 alacsony",
"Figyelmezt.POT szondát ellenõrizni",
"Riasztás CL2 felsõérték",
"Riasztás CL2 alsóérték",
"Riasztás pH felsõérték ",
"Riasztás pH alsóérték ",
"Riasztás Redox",
"Figyelem Redox érték ",
"Figyelem pH felsõérték ",
"Figyelem pH alsóérték ",
"Mérõvízhiány",
"úszókapcsoló",
"átfolyás mérése",
"Külsõ adagolási tiltás",
"Nincs kapcsolat a vezérlõegységhez",
"CL2 meredekségi hiba",
"Meredékségi hiba pH",
"Nullponthiba",
"pH kanna üres",
"Adagolásiidõ fertõtlenítés túllépve",
"Adagolásiidõ pH emelés túllépve",
"Adagolásiidõ pH csökk. túllépve",
"bekapcsolási késleltetés aktiv",
"Folyamatos adagol.fertõtlenítés-fut",
"Folyamatos adagolás pH-fut",
"Fertõtlenít.szabályoz.határ túllépv",
"Fertõtlenít.szabályoz.határ túllépv",
"pH szabályozási határ túllépve",
"pH szabályozási határ alacsony",
"Riasztás termék hõmérsék.túl magas",
"Figyelmezt.termékhõmérséklet magas",
"Figyelmezt.termékhõmérs.alacsony",
"Riasztás cellafeszûltség alacsony",
"Legyen az ön vize a legjobb",
"Német",
"Angol",
"Francia",
"Spanyol",
"Lengyel",
"Ukrán",
"Orosz",
"Olasz",
"Cseh",
"Slovén",
"Horváth",
"Magyar",
"Román",
"Holland",
"Szerb",
};
