char* text_fr[] = {
"MENU PRINCIPAL",
"Code#" xstr(code0_in),
"Mode l'électrolys.#" xstr(btr_art_t),
"Configuration appareil#300",
	"Type d'installation,g/h#" xstr(anl_typ_t),
	"Adresse bus#" xstr(sh_adr),
	"Contraste#" xstr(contr),
	"Calcul de moyenne#" xstr(mttl),
	"Technique de mesure#" xstr(msr_t),
"étalonnage#301",
	"étalonnage sonde de chlore#302",
		"Valeur mesurée,mg/l#" xstr(cl_val_ix),
		"Pente,mV#" xstr(cl_sth_in),
		"Tension d'entrée,mV#" xstr(cl_mv_ix),
		"Sauvegarder Uentrée#" xstr(set_nt),
		"Uentrée sauvegardée,mV#" xstr(uin_saved_ix),
		"Point zéro,mV#" xstr(cl_mv0_in),
		"Définition du point zéro#" xstr(set_nt),
		"Valeur DPD,mg/l#" xstr(cl_dpd_in),
		"RAZ étalonnage#" xstr(set_nt),
		"Fin NAE en, Min#" xstr(aer_min_ix),
		"étalonnage pas possible",
	"étalonnage pH#303",
		"Valeur mesurée,pH#" xstr(ph_ix),
		"Pente,mV/pH#" xstr(ph_sth_in),
		"Point zéro,mV#" xstr(ph_null_in),
		"Tension d'entrée,mV#" xstr(ph_mv_ix),
		"étalonnage pH4/7#" xstr(ph_dpd2_in),
		"RAZ étalonnage#" xstr(set_nt),
"Valeurs de consigne syst.de mesure#304",
	"Temporisation de mise en marche,Min#" xstr(on_dly),
	"Valeurs de consigne Cl2#305",
		"Valeurs de consigne CL2#306",
			"Seuil d'alarme supérieur,mg/l#" xstr(cl_alr_ob),
			"Seuil d'avertis.supérieur,mg/l#" xstr(cl_wr_ob),
			"Valeur de consigne,mg/l#" xstr(cl_soll),
			"Seuil d'avertis.inférieur,mg/l#" xstr(cl_wr_un),
			"Seuil d'alarme inférieur,mg/l#" xstr(cl_alr_un),
			"Temporisation d'alarme,Min#" xstr(cl_alr_dly),
		"Régulation CL2#307",
			"Bande P,mg/l#" xstr(cl_p),
			"Temps de correction ,Sek#" xstr(cl_i),
			"Hystérésis,mg/l#" xstr(cl_hys),
		"Réglages de dosage#308",
			"Dosage continu manuel,Min#" xstr(cl_man_dos),
			"Mett.en marche le dosag.cont.#" xstr(set_nt),
			"Surveillance du temps de dosage,Min#" xstr(cl_dos_watch),
	"Valeurs pH#309",
		"Valeurs de consigne pH#310",
			"Seuil d'alarme supérieur,pH#" xstr(ph_alr_ob),
			"Seuil d'avertis.supérieur,pH#" xstr(ph_wr_ob),
			"Valeur de consigne,pH#" xstr(ph_soll),
			"Seuil d'avertis.inférieur,pH#" xstr(ph_wr_un),
			"Seuil d'alarme inférieur,pH#" xstr(ph_alr_un),
			"Temporisation d'alarme,Min#" xstr(alr_dly_ph),
		"Régulation pH#311",
			"Bande P,pH#" xstr(ph_p),
			"Hystérésis,pH#" xstr(ph_hys),
			"Temps de correction ,Sek#" xstr(ph_zi),
			"Zone morte,pH#" xstr(totband_ph),
		"Réglages de dosage#312",
			"Dosage continu manuel,Min#" xstr(ph_man_dos),
			"Mett.en marche le dosag.cont.#" xstr(set_nt),
			"Surveillance du temps de dosage,Min#" xstr(ph_dos_watch),
	"Redox#313",
		"Valeurs de consigne Redox#314",
			"Valeur mesurée,mV#" xstr(rx_ix),
			"Valeur de consigne,mV#" xstr(rx_soll),
			"Seuil d'avertis.inférieur,mV#" xstr(rx_wr_un),
			"Seuil d'alarme inférieur,mV#" xstr(rx_alr_un),
			"Temporisation d'alarme,Min#" xstr(alr_dly_rx),
		"Régulation Redox#315",
			"Bande P,mV#" xstr(rx_p),
			"Hystérésis,mV#" xstr(rx_hys),
		"Réglages de dosage#316",
			"Dosage continu manuel,Min#" xstr(rx_man_dos),
			"Mett.en marche le dosag.cont.#" xstr(set_nt),
			"Surveillance du temps de dosage,Min#" xstr(rx_dos_watch),
	"Surveillance de l'eau de mesure#317",
		"Mode#" xstr(mw_art_t),
		"Débit,l/h#" xstr(fl_aktl_mw_ix),
		"Taux de débit,P/l#" xstr(fl_rate_mw),
		"Débit mini,l/h#" xstr(min_fl_mw),
		"Compensation,l/h#" xstr(flow_komp),
	"Date et heure#318",
		"Heures#" xstr(std_1),
		"Minutes#" xstr(min_1),
		"Jour#" xstr(day),
		"Mois#" xstr(mon),
		"an#" xstr(year),
	"NAE#319",
		"Heures#" xstr(asr_std),
		"Minutes#" xstr(asr_min),
		"Nombre NAE par jour#" xstr(asr_day),
		"Démarrage manuel NAE#" xstr(set_nt),
	"Température#320",
		"Compensation#" xstr(t_comp_t),
		"Compensation manuelle,°C#" xstr(t_man_comp),
		"Correction,°C#" xstr(t_korr),
"Valeurs de consigne électrolyse#321",
	"Electrolyse#322",
		"Dosage de saumure,%#" xstr(sole_dos),
		"Surveil.réalimentat.saumure,Min#" xstr(sole_nspw),
		"Limiter la température,°C#" xstr(temp_lim_t),
		"Temp.produit maxi,°C#" xstr(maxt),
		"Concentration en CL2,g/l#" xstr(cl_konz),
	"Bac de stockage#323",
		"Niveau trop-plein,cm#" xstr(prodlev_ovfl),
		"Niveau maxi,cm#" xstr(prodlev_max),
		"Niveau mini,cm#" xstr(prodlev_min),
"potentiel#324",
	"Relais 3 [#325",
		"Affectation#" xstr(r3_strg_t),
		"Mode de régulation#" xstr(r3_art_t),
		"Fréquence d'impulsion,P/h#" xstr(r3_frq),
		"Durée de période,Sek#" xstr(r3_pp),
		"Impulsion mini,Sek#" xstr(r3_min),
	"Relais 4 §#326",
		"Affectation#" xstr(r4_strg_t),
		"Mode de régulation#" xstr(r4_art_t),
		"Fréquence d'impulsion,P/h#" xstr(r4_frq),
		"Durée de période,Sek#" xstr(r4_pp),
		"Impulsion mini,Sek#" xstr(r4_min),
"Langue#" xstr(sprache_t),
"Paramétrages usine#" xstr(set_nt),
"Données de l'appareil:#327",
	"Numéro de l'appareil#" xstr(dev_nr_ix),
	"Version logiciel#" xstr(softver_in),
	"Date de fabrication#" xstr(mdate_in),
	"Fabricant#328",
		"dinotec GmbH",
		"Spessartstr. 7",
		"D-63477 Maintal",
		"Tel:0049-(0)6109-6011-0",
		"Hotline:0049-(0)6109-6011-72",
		"www.dinotec.de",
		"service@dinotec.de",
"Frei",
"Installation en marche",
"Alarme",
"Abaissement du pH",
"Augmentation du pH",
"Redox",
"CL2",
"CL2,pH",
"CL2,pH,Redox",
"pH",
"pH,Redox",
"sans système de mesure",
"30",
"60",
"90",
"150",
"200",
"300",
"définir",
"remettre à zéro",
"Désactivé",
"Régime normal",
"Rempl.bac à saum.",
"Rempl.la cell.",
"Rempl.instal.",
"Installation prête",
"Bac à saumure rempli",
"Cellule remplie",
"Installation remplie",
"L'électrolyseur est en production",
"L'adoucisseur régénère",
"Alarme Fonctionnement du système",
"Avertis. Contrôl.l'instal.DES",
"Alarme Mesure niveau du bac de stoc",
"Alarme Trop-plein bac de stockage",
"Alarme Tension de cell. trop élevée",
"Alarme Courant trop élevé",
"Alarme Courant trop faible",
"Alarme Débit trop élevé",
"Alarme Débit trop faible",
"Alarme Niveau bac à saumure",
"Marche/Arrêt",
"Fréquence d'impulsion",
"Impulsion/Repos",
"Oui",
"Non",
"Manuelle",
"automatique",
"Avertis.CL2 seuil haut",
"Avertis.CL2 seuil bas",
"Avertis. Contrôler sonde POT",
"Alarme CL2 seuil haut",
"Alarme CL2 seuil bas",
"Alarme pH seuil haut",
"Alarme pH seuil bas",
"Alarme Redox",
"Avertis.Redox",
"Avertis.pH seuil haut",
"Avertis.pH seuil bas",
"Manque d'eau de mesure",
"Interrupteur à flotteur",
"Mesure de débit",
"Arrêt dosage externe",
"Pas de liaison à l'unité de comman.",
"Erreur de pente Cl2",
"Erreur de pente du pH ",
"Erreur de zéro",
"Bidon pH est vide",
"Dépassement tps dosage désinfect.",
"Dépassement tps dosage augm. pH",
"Dépassement tps dosage abaiss. pH",
"Temporis. mise en marche activée",
"Dosage continu désinf. en cours",
"Dosage continu pH en cours",
"Dépasse seuil régulation désinf.",
"Sous seuil régulation désinfect.",
"Dépasse seuil de régulation pH",
"Sous seuil de régulation pH",
"Alarme Températ.du prod.trop élevée",
"Avertis.Tempér.du prod.élevée",
"Avertis.Tempér.du prod.basse",
"Alarme Tension de cell. trop basse",
"Tout simpl.le plaisir la meil.des eaux!",
"Allemand",
"Anglais",
"Français",
"Espagnol",
"Polonais",
"Ukrainien",
"Russe",
"Italien",
"Tchèque",
"Slovène",
"Croate",
"Hongrois",
"Roumain",
"Néerlandais",
"Serbe",
