#define sh_adr 0 	   		
#define contr 1         
#define mttl 2	   		
#define cl_dpd 3			
#define cl_alr_ob 4	 
#define cl_wr_ob 5		
#define cl_wr_un 6		
#define cl_alr_un 7		
#define cl_alr_dly 8		
#define on_dly 9	    	
#define cl_p 10			
#define cl_i 11			
#define cl_hys 12			
#define cl_soll 13			
#define fl_rate_mw 14  		
#define min_fl_mw 15		
#define std_1 16				
#define min_1 17			
#define day 18				
#define mon 19				
#define year 20			
#define asr_std 21		
#define asr_min 22			
#define asr_day 23			
#define t_man_comp 24 		
#define t_korr 25			
#define sole_dos 26		
#define max_t 27			
#define cl_konz 28			
#define prodlev_ovfl 29 	
#define prodlev_max 30		
#define prodlev_min 31		
#define r3_frq 32        
#define r3_pp 33         
#define r3_min 34        
#define r4_frq  35       
#define r4_pp 36         
#define r4_min  37       
#define sprache   38     
#define temp_lim 	39	
#define anl_typ 40			
#define btr_art 41			
#define msr 42	 			
#define t_comp  43 		
#define r3_strg  44      
#define r3_art  45       
#define r4_strg  46      
#define r4_art 47        
#define set_0 48	 		
#define set  49 			
#define code0 50			
#define softver 51        
#define mdate 52         
#define cl_sth 53			
#define cl_val 54			
#define cl_mv 55			
#define cl_mv_null 56     
#define aer_min 57
#define fl_aktl_mw 58    
#define dev_nr 59

#define xstr(s) str(s)
#define str(s) #s
