const char* text_nl[] = {
"HOOFDMENU",
"Code#" xstr(code0_in),
"Bedrijf elektrol.#" xstr(btr_art_t),
"Apparaatconfiguratie#300",
	"Installatietype,g/h#" xstr(anl_typ_t),
	"Busadres#" xstr(sh_adr),
	"Contrast#" xstr(contr),
	"Meettechniek#" xstr(msr_t),
	"Meetbereik Cl2#" xstr(mgl_t),
	"Cl2 PH-gecompenseerde#" xstr(set_nt),
"Kalibratie#301",
	"Kalibratie chloorsonde#302",
		"Meetwaarde,mg/l#" xstr(cl_val_ix),
		"Steilheid,mV#" xstr(cl_sth_in),
		"Ingangsspanning,mV#" xstr(cl_mv_ix),
		"Opslaan Uaan#" xstr(set_nt),
		"Uaan opgeslagen,mV#" xstr(uin_saved_ix),
		"Nulpunt,mV#" xstr(cl_mv0_in),
		"Nulpunt instellen#" xstr(set_nt),
		"DPD-waarde,mg/l#" xstr(cl_dpd_in),
		"Kalibratiereset#" xstr(set_nt),
		"Einde AER over, Min#" xstr(aer_min_ix),
		"Kalibratie niet mogelijk",
		"Meetwaarde < 0,1 mg/l",
		"Meetwaarde < 0,05 mg/l",
	"Kalibratie pH#303",
		"Meetwaarde,pH#" xstr(ph_ix),
		"Steilheid,mV/pH#" xstr(ph_sth_in),
		"Nulpunt,mV#" xstr(ph_null_in),
		"Ingangsspanning,mV#" xstr(ph_mv_ix),
		"Kalibratie pH4/7#" xstr(ph_dpd2_in),
		"Kalibratiereset#" xstr(set_nt),
"Instelwaarde meettechniek#304",
	"Inschakelvertraging,Min#" xstr(on_dly),
	"Instelwaarde Cl2#305",
		"Instelwaarde CL2#306",
			"Alarmwaarde boven,mg/l#" xstr(cl_alr_ob),
			"Waarschuwingswaarde boven,mg/l#" xstr(cl_wr_ob),
			"Instelwaarde,mg/l#" xstr(cl_soll),
			"Waarschuwingswaarde onder,mg/l#" xstr(cl_wr_un),
			"Alarmwaarde onder,mg/l#" xstr(cl_alr_un),
			"Alarmvertraging,Min#" xstr(cl_alr_dly),
		"Regeling CL2#307",
			"P-bereik,mg/l#" xstr(cl_p),
			"Integratietijd,Sek#" xstr(cl_i),
			"Hysterese,mg/l#" xstr(cl_hys),
		"Doseringsinstellingen#308",
			"Handm. continue dosering,Min#" xstr(cl_man_dos),
			"Continue dosering inschakelen#" xstr(set_nt),
			"Doseertijdbewaking,Min#" xstr(cl_dos_watch),
	"pH-waarden#309",
		"Instelwaarden pH#310",
			"Alarmwaarde boven,pH#" xstr(ph_alr_ob),
			"Waarschuwingswaarde boven,pH#" xstr(ph_wr_ob),
			"Instelwaarde,pH#" xstr(ph_soll),
			"Waarschuwingswaarde onder,pH#" xstr(ph_wr_un),
			"Alarmwaarde onder,pH#" xstr(ph_alr_un),
			"Alarmvertraging,Min#" xstr(alr_dly_ph),
		"Regeling pH#311",
			"P-bereik,pH#" xstr(ph_p),
			"Hysterese,pH#" xstr(ph_hys),
			"Integratietijd,Sek#" xstr(ph_zi),
			"Dode band,pH#" xstr(totband_ph),
		"Doseringsinstellingen#312",
			"Handm. continue dosering,Min#" xstr(ph_man_dos),
			"Continue dosering inschakelen#" xstr(set_nt),
			"Doseertijdbewaking,Min#" xstr(ph_dos_watch),
	"Redox#313",
		"Nominale waarden Redox#314",
			"Meetwaarde,mV#" xstr(rx_ix),
			"Instelwaarde,mV#" xstr(rx_soll),
			"Waarschuwingswaarde onder,mV#" xstr(rx_wr_un),
			"Alarmwaarde onder,mV#" xstr(rx_alr_un),
			"Alarmvertraging,Min#" xstr(alr_dly_rx),
		"Regeling redox#315",
			"P-bereik,mV#" xstr(rx_p),
			"Hysterese,mV#" xstr(rx_hys),
		"Doseringsinstellingen#316",
			"Handm. continue dosering,Min#" xstr(rx_man_dos),
			"Continue dosering inschakelen#" xstr(set_nt),
			"Doseertijdbewaking,Min#" xstr(rx_dos_watch),
	"Meetwaterbewaking#317",
		"Soort#" xstr(mw_art_t),
		"Debiet,l/h#" xstr(fl_aktl_mw_ix),
		"Debietpercentage,P/l#" xstr(fl_rate_mw),
		"minimaal debiet,l/h#" xstr(min_fl_mw),
		"Compensatie,l/h#" xstr(flow_komp),
	"Datum en tijd#318",
		"Uren#" xstr(std_1),
		"Minuten#" xstr(min_1),
		"Dag#" xstr(day),
		"Maand#" xstr(mon),
		"Jaar#" xstr(year),
	"AER#319",
		"Uren#" xstr(asr_std),
		"Minuten#" xstr(asr_min),
		"Aantal AER per dag#" xstr(asr_day),
		"AER handmatig starten#" xstr(set_nt),
	"Temperatuur#320",
		"Compensatie#" xstr(t_comp_t),
		"Handmatige compensatie,C#" xstr(t_man_comp),
		"Correctie,C#" xstr(t_korr),
"Instelwaarde elektrolyse#321",
	"Elektrolyse#322",
		"Dosering zout water,%#" xstr(sole_dos),
		"Bewakin.bijvoed.zout water,Min#" xstr(sole_nspw),
		"Temperatuur begrenzen,C#" xstr(temp_lim_t),
		"Max. producttemp. C#" xstr(maxt),
		"CL2-concentratie,g/l#" xstr(cl_konz),
		"Debiet,l/h#" xstr(flow_ely),
		"Correctie,C#" xstr(t0_korr),
		"Spanningbewakingsproces#" xstr(v_monitus_t),
	"Producttank#323",
		"Niveau controle#" xstr(lev_art_t),
		"Niveau overloop,cm#" xstr(prodlev_ovfl),
		"Niveau max,cm#" xstr(prodlev_max),
		"Niveau min,cm#" xstr(prodlev_min),
		"Noodbediening#" xstr(not_btr_t),
		"Noodloopeigenschappen,min#" xstr(not_zeit),
	"Ventilator#324",
		"Voorlooptijd,sec#" xstr(luft_vor),
		"Nalooptijd,min#" xstr(luft_nach),
"Relais#325",
	"Relais 2 [#326",
		"Toekenning#" xstr(r3_strg_t),
		"Regelmodus#" xstr(r3_art_t),
		"Pulsfrequentie,P/h#" xstr(r3_frq),
		"Periodeduur,Sek#" xstr(r3_pp),
		"Minimum impuls,Sek#" xstr(r3_min),
	"Relais 3 §#327",
		"Toekenning#" xstr(r4_strg_t),
		"Regelmodus#" xstr(r4_art_t),
		"Pulsfrequentie,P/h#" xstr(r4_frq),
		"Periodeduur,Sek#" xstr(r4_pp),
		"Minimum impuls,Sek#" xstr(r4_min),
"Taal#" xstr(sprache_t),
"Fabrieksinstelling#" xstr(set_nt),
"Apparaatgegevens#328",
	"Apparaatnummer#" xstr(dev_nr_ix),
	"Softwareversie#" xstr(softver_ix),
	"Software versiebeheer#" xstr(soft_strg_ix),
	"Fabricagedatum#" xstr(mdate_in),
	"Fabrikant#329",
		"dinotec GmbH",
		"Phillipp-Reis Str. 28",
		"D-61130 Nidderau",
		"Tel: 0049 (0)6187 41379-0",
		"Hotline: 0049 (0)6187 41379-72",
		"www.dinotec.de",
		"service@dinotec.de",
"Frei",
"Ventilator",
"Installatie in bedrijf",
"Alarm",
"pH verlagen",
"pH verhogen",
"Redox",
"CL2",
"CL2,pH",
"CL2,pH,Redox",
"pH",
"pH,Redox",
"Zonder meettechniek",
"30",
"60",
"90",
"150",
"200",
"300",
"Instellen",
"Resetten",
"Uitgeschakeld",
"Normaal bedrijf",
"Zoutwatert.vullen",
"Cel vullen",
"Installatie vullen",
"Installatie klaar",
"Zoutwatertank gevuld",
"Cel gevuld",
"Installatie gevuld",
"Installatie produceert",
"Weekmaker geregenereerd",
"Alarm installatiebedrijf",
"Waarschuwing DES-installat.control.",
"Alarm niveaumeting producttank",
"Alarm producttank overloop",
"Alarm celspanning te hoog",
"Alarm stroom te hoog",
"Alarm stroom te laag",
"Alarm debiet te hoog",
"Alarm debiet te laag",
"Alarm niveau zoutwatertank",
"Aan-uit",
"Pulsfrequentie",
"Impulspauze",
"Ja",
"Nee",
"Handmatig",
"Automatisch",
"Waarschuwing boven CL2",
"Waarschuwing onder CL2",
"Waarschuwing POT-sonde controleren",
"Alarm boven CL2",
"Alarm onder CL2",
"Alarm pH boven",
"Alarm pH onder",
"Alarm Redox",
"Waarschuwing Redox",
"Waarschuwing pH boven",
"Waarschuwing pH onder",
"Gebrek aan meetwater",
"Niveaumeting",
"Vlotterschakelaar",
"Debietmeting",
"Externe doseerstop",
"Geen verbinding met besturing",
"Steilheidsfout Cl2",
"Fout steilheid pH",
"Nulpuntsfout",
"pH jerrycan is leeg",
"Doseertijd desinfectie overschreden",
"Doseertijd pH verhogen overschreden",
"Doseertijd pH verlagen overschreden",
"Inschakelvertraging actief",
"Continue dosering desinfectie loopt",
"Continue dosering pH loopt",
"Grenzen regelbereik desinf.overschr.",
"Grenzen regelbereik desinf.ondersch.",
"Grenzen regelbereik pH overschreden",
"Grenzen regelbereik pH onderschred.",
"Alarm producttemperatuur te hoog",
"Waarschuwing producttemperat.hoog",
"Waarschuwing producttemperat.laag",
"Alarm celspanning te laag",
"Geniet van het beste water!",
"Producttank is leeg",
"Dosering uitgeschakeld", 
"Elektrolyse uitgeschakeld",
"Ventilator voorloop",					//   =vent_vor_txt
"Ventilator naloop",					//   =vent_nach_txt
"Waarschuwing noodbedrijf",					
"0 - 1 mg/l",
"0 - 10 mg/l",
"Opstartproces, even geduld",
"Duits",
"Engels",
"Frans",
"Spaans",
"Pools",
"Oekraïens",
"Russisch",
"Italiaans",
"Tsjechisch",
"Sloveens",
"Kroatisch",
"Hongaars",
"Roemeens",
"Nederlands",
"Servisch",
};
