char* text_ro[] = {
"MENIU BAZă",
"Cod#" xstr(code0_in),
"Funcționare electroliză#" xstr(btr_art_t),
"Configurare aparat#300",
	"Tip instalație,g/h#" xstr(anl_typ_t),
	"Adresă bus#" xstr(sh_adr),
	"Contrast#" xstr(contr),
	"Tehnică măsură#" xstr(msr_t),
	"Interval masurăre Cl2#" xstr(mgl_t),
	"Cl2 compensat pH#" xstr(set_nt),
"Calibrare#301",
	"Calibrare sondă clor#302",
		"Val. măsură,mg/l#" xstr(cl_val_ix),
		"Pantă,mV#" xstr(cl_sth_in),
		"Tensiune intrare,mV#" xstr(cl_mv_ix),
		"Memorare Uein:#" xstr(set_nt),
		"Uein memorat,mV#" xstr(uin_saved_ix),
		"Punct nul,mV#" xstr(cl_mv0_in),
		"setare punct nul#" xstr(set_nt),
		"Valoare-DPD,mg/l#" xstr(cl_dpd_in),
		"Reset calibrare #" xstr(set_nt),
		"Final AER in, Min#" xstr(aer_min_ix),
		"Calibrarea nu e posibilă",
		"Val. măsură < 0,1 mg/l",
		"Val. măsură < 0,05 mg/l",
	"Calibrare pH#303",
		"Val. măsură,pH#" xstr(ph_ix),
		"Pantă,mV/pH#" xstr(ph_sth_in),
		"Punct nul,mV#" xstr(ph_null_in),
		"Tensiune intrare,mV#" xstr(ph_mv_ix),
		"Calibrare pH4/7#" xstr(ph_dpd2_in),
		"Reset calibrare #" xstr(set_nt),
"Val neces tehnică măsură#304",
	"Delay conectare,Min#" xstr(on_dly),
	"Val necesare Cl2#305",
		"Val necesare CL2#306",
			"Valoare alarmă sus,mg/l#" xstr(cl_alr_ob),
			"Val avertizare sus,mg/l#" xstr(cl_wr_ob),
			"Val. necesară,mg/l#" xstr(cl_soll),
			"Val. avertiz. jos,mg/l#" xstr(cl_wr_un),
			"Valoare alarmă jos,mg/l#" xstr(cl_alr_un),
			"Delay alarmă,Min#" xstr(cl_alr_dly),
		"Reglare CL2#307",
			"Interval-P,mg/l#" xstr(cl_p),
			"Timp de ajustare,Sek#" xstr(cl_i),
			"Histereză,mg/l#" xstr(cl_hys),
		"Setări-Dozare#308",
			"Dozare const. man. ,Min#" xstr(cl_man_dos),
			"Pornire dozare temporară#" xstr(set_nt),
			"Monitorizare timp dozare,Min#" xstr(cl_dos_watch),
	"Valori pH#309",
		"Val necesare pH#310",
			"Valoare alarmă sus,pH#" xstr(ph_alr_ob),
			"Val avertizare sus,pH#" xstr(ph_wr_ob),
			"Val. necesară,pH#" xstr(ph_soll),
			"Val. avertiz. jos,pH#" xstr(ph_wr_un),
			"Valoare alarmă jos,pH#" xstr(ph_alr_un),
			"Delay alarmă,Min#" xstr(alr_dly_ph),
		"Reglare pH#311",
			"Interval-P,pH#" xstr(ph_p),
			"Histereză,pH#" xstr(ph_hys),
			"Timp de ajustare,Sek#" xstr(ph_zi),
			"Bandă moartă,pH#" xstr(totband_ph),
		"Setări-Dozare#312",
			"Dozare const. man. ,Min#" xstr(ph_man_dos),
			"Pornire dozare temporară#" xstr(set_nt),
			"Monitorizare timp dozare,Min#" xstr(ph_dos_watch),
	"Redox#313",
		"Val. necesar Redox#314",
			"Val. măsură,mV#" xstr(rx_ix),
			"Val. necesară,mV#" xstr(rx_soll),
			"Val. avertiz. jos,mV#" xstr(rx_wr_un),
			"Valoare alarmă jos,mV#" xstr(rx_alr_un),
			"Delay alarmă,Min#" xstr(alr_dly_rx),
		"Reglare Redox#315",
			"Interval-P,mV#" xstr(rx_p),
			"Histereză,mV#" xstr(rx_hys),
		"Setări-Dozare#316",
			"Dozare const. man. ,Min#" xstr(rx_man_dos),
			"Pornire dozare temporară#" xstr(set_nt),
			"Monitorizare timp dozare,Min#" xstr(rx_dos_watch),
	"Monitorizare apă măsură#317",
		"Tip#" xstr(mw_art_t),
		"Flux,l/h#" xstr(fl_aktl_mw_ix),
		"Rată flux,P/l#" xstr(fl_rate_mw),
		"flux minim,l/h#" xstr(min_fl_mw),
		"Compensare,l/h#" xstr(flow_komp),
	"Data ți ora#318",
		"Ore#" xstr(std_1),
		"Minute#" xstr(min_1),
		"Zi#" xstr(day),
		"Lună#" xstr(mon),
		"An#" xstr(year),
	"AER#319",
		"Ore#" xstr(asr_std),
		"Minute#" xstr(asr_min),
		"Contor AER pe zi#" xstr(asr_day),
		"AER pornire manuală#" xstr(set_nt),
	"Temperatură#320",
		"Compensare#" xstr(t_comp_t),
		"Compensare manuală,°C#" xstr(t_man_comp),
		"Corectare,°C#" xstr(t_korr),
"Val necesare electroliză#321",
	"Electroliză#322",
		"Dozare saramură,%#" xstr(sole_dos),
		"Monitor.reumplere saram.,Min#" xstr(sole_nspw),
		"Limitare temperatură,°C#" xstr(temp_lim_t),
		"Temp. produs max.°C#" xstr(maxt),
		"Concentrație CL2,g/l#" xstr(cl_konz),
		"Flux,l/h#" xstr(flow_ely),
		"Corectare,°C#" xstr(t0_korr),
		"Monitorizare a tensiunii#" xstr(v_monitus_t),
	"Vas produs#323",
		"Monitor.nivelului#" xstr(lev_art_t),
		"Nivel supraplin,cm#" xstr(prodlev_ovfl),
		"Nivel max,cm#" xstr(prodlev_max),
		"Nivel min,cm#" xstr(prodlev_min),
	"Ventilator#324",
		"Timp funcţionare prelabilă,sec#" xstr(luft_vor),
		"Timp funcţ.inerţială, min#" xstr(luft_nach),
"Releu#325",
	"Releu 3 [#326",
		"Atribuire#" xstr(r3_strg_t),
		"Tip control#" xstr(r3_art_t),
		"Frecvență puls,P/h#" xstr(r3_frq),
		"Durată perioadă,Sek#" xstr(r3_pp),
		"Impuls minim,Sek#" xstr(r3_min),
	"Releu 4 ]#327",
		"Atribuire#" xstr(r4_strg_t),
		"Tip control#" xstr(r4_art_t),
		"Frecvență puls,P/h#" xstr(r4_frq),
		"Durată perioadă,Sek#" xstr(r4_pp),
		"Impuls minim,Sek#" xstr(r4_min),
"Limbă#" xstr(sprache_t),
"Setări fabrică#" xstr(set_nt),
"Date aparat#328",
	"Număr aparat#" xstr(dev_nr_ix),
	"Stadiu software#" xstr(softver_in),
	"Data fabricării#" xstr(mdate_in),
	"Producător#329",
		"dinotec GmbH",
		"Phillipp-Reis Str. 28",
		"D-61130 Nidderau",
		"Tel: 0049 (0)6187 41379-0",
		"Hotline: 0049 (0)6187 41379-72",
		"www.dinotec.de",
		"service@dinotec.de",
"Frei",
"Ventilator",
"Instalație in funcțiune",
"Alarmă",
"Scădere pH",
"Ridicare pH",
"Redox",
"CL2",
"CL2,pH",
"CL2,pH,Redox",
"pH",
"pH,Redox",
"fără tehnică măsură",
"30",
"60",
"90",
"150",
"200",
"300",
"setare",
"resetare",
"Oprit",
"Funcționare normală",
"Umplere vas saramură",
"Umplere celulă",
"Umplere instalație",
"Instal pregătită",
"Vas saramură umplut",
"Celulă plină",
"Instalație plină",
"Instalația produce",
"Regenerare dedurizator",
"Alarmă funcționare aparat",
"Avertizare verif instal DES",
"Alarmă măsurare nivel vas produs",
"Alarmă supraplin vas produs",
"Alarmă tensiune celulă prea mică",
"Alarmă curent prea mare",
"Alarmă curent prea mic",
"Alarmă flux prea mare",
"Alarmă flux prea mic",
"Alarmă nivel vas saramură",
"ON-OFF",
"Frecvență puls",
"Pauză-Puls",
"Da",
"Nu",
"manual",
"Automat",
"Avertizare CL2 sus",
"Avertizare CL2 jos",
"Avertizare verif sondă-POT",
"Alarmă Cl2 prea mult",
"Alarmă Cl2 prea puțin",
"Alarmă pH sus",
"Alarmă pH jos",
"Alarmă Redox",
"Avertizare Redox",
"Avertizare pH sus",
"Avertizare pH jos",
"Lipsă apă măsură",
"Măsurarea nivelului",
"Contactor plutitor",
"Măsurare flux",
"Stop dozare externă",
"Fără conexiune terminal comandă",
"Eroare pantă Cl2",
"Eroare pantă pH",
"Eroare punct nul",
"Canistra pH este goală",
"Durată dozare dezinfectare depățită ",
"Durată dozare pH ridicare depățită",
"Durată dozare pH scădere depățită",
"Delay pornire activ",
"Dozare constantă dezinfectare fcț",
"Dozare contantă pH fcț",
"Nivel reglare dezinfectare depățit",
"Nivel reglare dezinfectare sub limită",
"Nivel reglare pH depățit",
"Nivel reglare pH sub limită ",
"Alarmă temparatură produs prea mare",
"Avertizare temp produs mare",
"Avertizare temp produs mic",
"Alarmă tensiune celulă prea mică",
"Pur ți simplu apa perfectă!",
"Vas produs este goală",
"Dozare oprit", 
"Electroliză oprit",
"Funcţ.prealabilă ventilator",					//   =vent_vor_txt
"Postfuncţionare ventilator",					//   =vent_nach_txt
"0 - 1 mg/l",
"0 - 10 mg/l",
"Germană",
"Engleză",
"Franceză",
"Spaniolă",
"Poloneză",
"Ucraineană",
"Rusă",
"Italiană",
"Cehă",
"Slovenă",
"Croată",
"Ungară",
"Română",
"Olandeză",
"Sârbă",
};
