char* text_pl[] = {
"MENU glówne",
"kod#" xstr(code0_in),
"Praca Elektroliza#" xstr(btr_art_t),
"Konfiguracja urządzenia#300",
	"Typ urządzenia,g/h#" xstr(anl_typ_t),
	"Adres BUS#" xstr(sh_adr),
	"Kontrast#" xstr(contr),
	"Technika pomiarowa#" xstr(msr_t),
	"Zakres pomiarowy Cl2#" xstr(mgl_t),
	"Cl2 pH z kompensacja#" xstr(set_nt),
"Kalibracja#301",
	"Kalibracja sondy chloru#302",
		"Wart. pomiar.,mg/l#" xstr(cl_val_ix),
		"Stromość,mV#" xstr(cl_sth_in),
		"Napiêcie wejeciowe,mV#" xstr(cl_mv_ix),
		"Zapisz Uwe#" xstr(set_nt),
		"Uwe zapisany,mV#" xstr(uin_saved_ix),
		"Punkt zerowy,mV#" xstr(cl_mv0_in),
		"Ustawianie punktu zerowego#" xstr(set_nt),
		"Wartość DPD,mg/l#" xstr(cl_dpd_in),
		"Reset kalibracji#" xstr(set_nt),
		"Koniec ACE za, Min#" xstr(aer_min_ix),
		"Kalibracja niemożliwa",
		"Wart. pomiar. < 0,1 mg/l",
		"Wart. pomiar. < 0,05 mg/l",
	"Kalibracja pH#303",
		"Wart. pomiar.,pH#" xstr(ph_ix),
		"Stromość,mV/pH#" xstr(ph_sth_in),
		"Punkt zerowy,mV#" xstr(ph_null_in),
		"Napiêcie wejeciowe,mV#" xstr(ph_mv_ix),
		"Kalibracja pH 4/7#" xstr(ph_dpd2_in),
		"Reset kalibracji#" xstr(set_nt),
"Wartoeci zadane Technika pomiarowa#304",
	"Opóźnianie włączenia,Min#" xstr(on_dly),
	"Wartoeci zadane CL2#305",
		"Wartoeci zadane CL2#306",
			"Górna wartość alarmowa,mg/l#" xstr(cl_alr_ob),
			"Górna wartość ostrzegawcza,mg/l#" xstr(cl_wr_ob),
			"Wartość zadana,mg/l#" xstr(cl_soll),
			"Dolna wartość ostrzegawcza,mg/l#" xstr(cl_wr_un),
			"Dolna wartość alarmowa,mg/l#" xstr(cl_alr_un),
			"Opóźnienie alarmu,Min#" xstr(cl_alr_dly),
		"Regulacja CL2#307",
			"Zakres regulacji P,mg/l#" xstr(cl_p),
			"Czas całkowania,Sek#" xstr(cl_i),
			"Histereza,mg/l#" xstr(cl_hys),
		"Ustawienia dozowania#308",
			"Dozowanie ciągłe rêczne,Min#" xstr(cl_man_dos),
			"Włącz dozowanie ciągłe#" xstr(set_nt),
			"Kontrola czasu dozowania,Min#" xstr(cl_dos_watch),
	"Wartoeci pH#309",
		"Wartośći zadane pH#310",
			"Górna wartość alarmowa,pH#" xstr(ph_alr_ob),
			"Górna wartość ostrzegawcza,pH#" xstr(ph_wr_ob),
			"Wartość zadana,pH#" xstr(ph_soll),
			"Dolna wartość ostrzegawcza,pH#" xstr(ph_wr_un),
			"Dolna wartość alarmowa,pH#" xstr(ph_alr_un),
			"Opóźnienie alarmu,Min#" xstr(alr_dly_ph),
		"Regulacja pH#311",
			"Zakres regulacji P,pH#" xstr(ph_p),
			"Histereza,pH#" xstr(ph_hys),
			"Czas całkowania,Sek#" xstr(ph_zi),
			"Zakres martwy,pH#" xstr(totband_ph),
		"Ustawienia dozowania#312",
			"Dozowanie ciągłe rêczne,Min#" xstr(ph_man_dos),
			"Włącz dozowanie ciągłe#" xstr(set_nt),
			"Kontrola czasu dozowania,Min#" xstr(ph_dos_watch),
	"Redox#313",
		"Wartośći zadane redox#314",
			"Wart. pomiar.,mV#" xstr(rx_ix),
			"Wartość zadana,mV#" xstr(rx_soll),
			"Dolna wartość ostrzegawcza,mV#" xstr(rx_wr_un),
			"Dolna wartość alarmowa,mV#" xstr(rx_alr_un),
			"Opóźnienie alarmu,Min#" xstr(alr_dly_rx),
		"Regulacja Redox#315",
			"Zakres regulacji P,mV#" xstr(rx_p),
			"Histereza,mV#" xstr(rx_hys),
		"Ustawienia dozowania#316",
			"Dozowanie ciągłe rêczne,Min#" xstr(rx_man_dos),
			"Włącz dozowanie ciągłe#" xstr(set_nt),
			"Kontrola czasu dozowania,Min#" xstr(rx_dos_watch),
	"Kontrola wody pomiarowej#317",
		"Rodzaj#" xstr(mw_art_t),
		"Przepływ,l/h#" xstr(fl_aktl_mw_ix),
		"Wskaźnik przepływu,P/l#" xstr(fl_rate_mw),
		"Minimalny przepływ,l/h#" xstr(min_fl_mw),
		"Kompensacja,l/h#" xstr(flow_komp),
	"Data i czas#318",
		"Godziny#" xstr(std_1),
		"minuty#" xstr(min_1),
		"Dzieñ#" xstr(day),
		"miesiąc#" xstr(mon),
		"rok#" xstr(year),
	"ACE#319",
		"Godziny#" xstr(asr_std),
		"minuty#" xstr(asr_min),
		"Liczba operacji ACE dziennie#" xstr(asr_day),
		"Rêczne włączanie ACE#" xstr(set_nt),
	"Temperatura#320",
		"Kompensacja#" xstr(t_comp_t),
		"Kompensacja rêczna,°C#" xstr(t_man_comp),
		"Korekta,°C#" xstr(t_korr),
"Wartoeci zadane Elektroliza#321",
	"Elektroliza#322",
		"Dozowanie solanki,%#" xstr(sole_dos),
		"Kontrola zasilania solanką,Min#" xstr(sole_nspw),
		"Ograniczanie temperatury,°C#" xstr(temp_lim_t),
		"Maks. temperatura produktu °C#" xstr(maxt),
		"Stêżenie CL2,g/l#" xstr(cl_konz),
		"Przepływ,l/h#" xstr(flow_ely),
		"Poprawka,°C#" xstr(t1_korr),
		"Monitorowanie napięcia#" xstr(v_monitus_t),
	"Zbiornik produktu#323",
		"Monitor. poziomu#" xstr(lev_art_t),
		"Poziom przelewu,cm#" xstr(prodlev_ovfl),
		"Poziom maks.,cm#" xstr(prodlev_max),
		"Poziom min.,cm#" xstr(prodlev_min),
	"Wentylator#324",
		"Czas rozbiegu,sek#" xstr(luft_vor),
		"Czas wybiegu,min#" xstr(luft_nach),
"Przekaźnik#325",
	"Przekaźnik 3 [#326",
		"Przyporządkowanie#" xstr(r3_strg_t),
		"Rodzaj regulacji#" xstr(r3_art_t),
		"Czêstotliwość impulsów,P/h#" xstr(r3_frq),
		"Długość cyklu,Sek#" xstr(r3_pp),
		"Minimalny impuls,Sek#" xstr(r3_min),
	"RPrzekaźnik 4 ]#327",
		"Przyporządkowanie#" xstr(r4_strg_t),
		"Rodzaj regulacji#" xstr(r4_art_t),
		"Czêstotliwość impulsów,P/h#" xstr(r4_frq),
		"Długość cyklu,Sek#" xstr(r4_pp),
		"Minimalny impuls,Sek#" xstr(r4_min),
"Jêzyk#" xstr(sprache_t),
"Ustawienie fabryczne#" xstr(set_nt),
"Dane urządzenia#328",
	"Numer urządzenia#" xstr(dev_nr_ix),
	"Wersja oprogramow.#" xstr(softver_in),
	"Data produkcji#" xstr(mdate_in),
	"Producent#329",
		"dinotec GmbH",
		"Phillipp-Reis Str. 28",
		"D-61130 Nidderau",
		"Tel: 0049 (0)6187 41379-0",
		"Hotline: 0049 (0)6187 41379-72",
		"www.dinotec.de",
		"service@dinotec.de",
"Frei",
"Wentylator",
"Praca urządzenia",
"Alarm",
"Obniżanie pH",
"podnoszenie pH",
"Redox",
"CL2",
"CL2,pH",
"CL2,pH,Redox",
"pH",
"pH,Redox",
"Bez techniki pomiarowej",
"30",
"60",
"90",
"150",
"200",
"300",
"Ustaw",
"Cofnij",
"Wyłączone",
"Tryb normalny",
"Napełn.zbior.sol.",
"Napełnij celê",
"Napełnij urządzenie",
"Urządz. gotowe",
"Zbiornik solanki napełniony",
"Cela napełniona",
"Urządzenie napełnione",
"Urządzenie produkuje",
"Zmiêkczacz zregenerowany",
"Alarm Instalacja",
"Ostrzeżenie Sprawdź dezynfekcjê DES",
"Alarm Pomiar poziomu Zbior.produktu",
"Alarm Zbiornik produktu Przelew",
"Alarm Napiêcie celi za niskie",
"Alarm Prąd za wysoki",
"Alarm Prąd za niski",
"Alarm Przepływ za wysoki",
"Alarm Przepływ za niski",
"Alarm Poziom Zbiornik solanki",
"Włącz / Wyłącz",
"Czêstotliwość impulsów",
"impuls / przerwa",
"tak",
"nie",
"rêczne",
"Automatycznie",
"Ostrzeżenie Wysoka wartość CL2",
"Ostrzeżenie Niska wartość CL2",
"Ostrzeżenie Sprawdź sondê POT",
"Alarm CL2 Poziom górny",
"Alarm CL2 Poziom dolny",
"Alarm pH Poziom górny",
"Alarm pH Poziom dolny",
"Alarm Redox",
"Ostrzeżenie Redox",
"Ostrzeżenie górna wartość pH",
"Ostrzeżenie dolna wartość pH",
"Brak wody pomiar.",
"Pomiar poziomu",
"lącznik pływakowy",
"Pomiar przepływu",
"Zewnêtrzne zatrzymanie dozowania",
"Brak połączenia ze sterownikiem",
"Błąd nachylenia charakterystyki CL2",
"Błąd nachylenia charakter.sondy pH ",
"Błąd punktu zerowego",
"Kanister pH pusty",
"Czas dozow. dezynf. przekroczony",
"Czas dozow. podnosz. pH przekrocz",
"Czas dozow. obniż. pH przekrocz.",
"Opóźnianie włączenia aktywne",
"Działa dozowanie ciągłe",
"Działa dozowanie ciągłe pH",
"Górna granica dezynf. przekrocz.",
"Dolna granica dezynf. przekrocz.",
"Górna granica pH przekroczona",
"Dolna granica pH przekroczona",
"Alarm Temperat.produktu za wysoka",
"Ostrzeżen.Temperat.produk.za wysoka",
"Ostrzeżen.Temperat.produk.za niska",
"Alarm Napiêcie celi za niskie",
"Po prostu ciesz siê czystą wodą!",
"Zbiornik produktu pusty",
"Dozowanie wyłączone", 
"Elektroliza wyłączone",
"Rozbieg wentylatora",					//   =vent_vor_txt
"Wybieg wentylatora",					//   =vent_nach_txt
"0 - 1 mg/l",
"0 - 10 mg/l",
"Niemiecki",
"Angielski",
"Francuski",
"Hiszpañski",
"Polski",
"Ukraiñski",
"Rosyjski",
"Włoski",
"Czeski",
"Słoweñski",
"Chorwacki",
"Wêgierski",
"Rumuñski",
"Niederlandzki",
"Serbski",
};
