const char* text_ru[] = {
"‚ˆABHOE MEH”",
"Ko™#" xstr(code0_in),
"Pa–.pešœ  ¬Ÿež£-›a#" xstr(btr_art_t),
"Ko¡¤œ˜ypa¥œ®#300",
	"Tœ¢ yc£a¡o—žœ,˜/¦#" xstr(anl_typ_t),
	"A™pec §œ¡ª #" xstr(sh_adr),
	"Ko¡£pac£¡oc£«#" xstr(contr),
	"†› epœ£.o–opy™-¡œe#" xstr(msr_t),
	"ƒœa¢a›o¡ œ› epe¡œ® Cl2#" xstr(mgl_t),
	"Cl2 pH žo ¢e¡cœpo—a¡#" xstr(set_nt),
"KaŸœ–po—ža#301",
	"KaŸœ–po—ža xŸop¡o˜o ¬Ÿež£po™a#302",
		"†› . ›¡a¦e¡œe, ˜/Ÿ#" xstr(cl_val_ix),
		"Kpy£œ›¡a, B#" xstr(cl_sth_in),
		"Bxo™¡oe ¡a¢p®še¡œe, B#" xstr(cl_mv_ix),
		"Coxpa¡œ£« U—xo™#" xstr(set_nt),
		"U—xo™ coxpa¡e¡o, B#" xstr(uin_saved_ix),
		"HyŸe—a® £o¦ža, B#" xstr(cl_mv0_in),
		"…a™a£« ¡yŸe—y­ £o¦žy#" xstr(set_nt),
		"…¡a¦e¡œe DPD, ˜/Ÿ#" xstr(cl_dpd_in),
		"C–poc žaŸœ–po—žœ#" xstr(set_nt),
		"Ko¡e¥ AER ¦epe›, œ¡#" xstr(aer_min_ix),
		"KaŸœ–po—ža ¡e—o› oš¡a",
		"†› . ›¡a¦e¡œe < 0,1  ˜/Ÿ",
		"†› . ›¡a¦e¡œe < 0,05  ˜/Ÿ",
	"KaŸœ–po—ža pH#303",
		"†› . ›¡a¦e¡œe,pH#" xstr(ph_ix),
		"Kpy£œ›¡a, B/pH#" xstr(ph_sth_in),
		"HyŸe—a® £o¦ža, B#" xstr(ph_null_in),
		"Bxo™¡oe ¡a¢p®še¡œe, B#" xstr(ph_mv_ix),
		"KaŸœ–po—ža pH4/7#" xstr(ph_dpd2_in),
		"C–poc žaŸœ–po—žœ#" xstr(set_nt),
"Ho œ¡.›¡a¦e¡œ® †› ep.o–opy™-e#304",
	"…a™epšža —žŸ­¦e¡œ®, œ¡#" xstr(on_dly),
	"Ho œ¡aŸ«¡ªe ›¡a¦e¡œ® CL2#305",
		"Ho œ¡aŸ«¡ªe ›¡a¦e¡œ® CL2#306",
			"Bepx.£pe—oš.›¡a¦e¡œe, ˜/Ÿ#" xstr(cl_alr_ob),
			"Bepx.¢pe™y¢pe™œ£.›¡a¦e¡œe, ˜/Ÿ#" xstr(cl_wr_ob),
			"Ho .›¡a¦e¡œe, ˜/Ÿ#" xstr(cl_soll),
			"Hœš¡.¢pe™y¢pe™œ£.›¡a¦e¡œe, ˜/Ÿ#" xstr(cl_wr_un),
			"Hœš¡.£pe—oš.›¡a¦e¡œe, ˜/Ÿ#" xstr(cl_alr_un),
			"…a™epšža £pe—oš.cœ˜¡aŸ-¥œœ, œ¡#" xstr(cl_alr_dly),
		"Pe˜yŸœpo—a¡œe CL2#307",
			"P-™œa¢a›o¡, ˜/Ÿ#" xstr(cl_p),
			"Bpe ® ™o¢oŸ.cpa–a£ª—a¡œ®,cež#" xstr(cl_i),
			"‚œc£epe›œc, ˜/Ÿ#" xstr(cl_hys),
		"Hac£požœ ™o›œp.#308",
			"Py¦¡.¡e¢pepª—.™o›œp., œ¡#" xstr(cl_man_dos),
			"BžŸ­¦œ£« ¡e¢pepª—.™o›œpo—a¡œe#" xstr(set_nt),
			"Ko¡£poŸ« —pe e¡œ ™o›œpo—., œ¡#" xstr(cl_dos_watch),
	"…¡a¦e¡œ® pH#309",
		"Ho .›¡a¦e¡œ® pH#310",
			"Bepx.£pe—oš.›¡a¦e¡œe,pH#" xstr(ph_alr_ob),
			"Bepx.¢pe™y¢pe™œ£.›¡a¦e¡œe,pH#" xstr(ph_wr_ob),
			"Ho .›¡a¦e¡œe,pH#" xstr(ph_soll),
			"Hœš¡.¢pe™y¢pe™œ£.›¡a¦e¡œe,pH#" xstr(ph_wr_un),
			"Hœš¡.£pe—oš.›¡a¦e¡œe,pH#" xstr(ph_alr_un),
			"…a™epšža £pe—oš.cœ˜¡aŸ-¥œœ, œ¡#" xstr(alr_dly_ph),
		"Pe˜yŸœpo—a¡œe pH#311",
			"P-™œa¢a›o¡,pH#" xstr(ph_p),
			"‚œc£epe›œc,pH#" xstr(ph_hys),
			"Bpe ® ™o¢oŸ¡.cpa–a£ª—a¡œ®,cež#" xstr(ph_zi),
			"Mep£—a® ›o¡a,pH#" xstr(totband_ph),
		"Hac£požœ ™o›œp.#312",
			"Py¦¡.¡e¢pepª—.™o›œp., œ¡#" xstr(ph_man_dos),
			"BžŸ­¦œ£« ¡e¢pepª—.™o›œpo—a¡œe#" xstr(set_nt),
			"Ko¡£poŸ« —pe e¡œ ™o›œpo—., œ¡#" xstr(ph_dos_watch),
	"Redox#313",
		"Ho œ¡aŸ«¡ªe ›¡a¦e¡œ® Redox#314",
			"†› .›¡a¦e¡œe, B#" xstr(rx_ix),
			"Ho .›¡a¦e¡œe, B#" xstr(rx_soll),
			"Hœš¡.¢pe™y¢pe™œ£. ›¡a¦e¡œe, B#" xstr(rx_wr_un),
			"Hœš¡.£pe—oš.›¡a¦e¡œe, B#" xstr(rx_alr_un),
			"…a™epšža £pe—oš.cœ˜¡aŸœ›., œ¡#" xstr(alr_dly_rx),
		"Pe˜yŸœpo—a¡œe Redox#315",
			"P-™œa¢a›o¡, B#" xstr(rx_p),
			"‚œc£epe›œc, B#" xstr(rx_hys),
		"Hac£požœ ™o›œp.#316",
			"Py¦¡.¡e¢pepª—.™o›œp., œ¡#" xstr(rx_man_dos),
			"BžŸ­¦œ£« ¡e¢pepª—¡oe ™o›œpo—.#" xstr(set_nt),
			"Ko¡£poŸ« —pe e¡œ ™o›œpo—., œ¡#" xstr(rx_dos_watch),
	"Ko¡£poŸ« œ› epœ£eŸ«¡o —o™ª#317",
		"Tœ¢#" xstr(mw_art_t),
		"‰po£ož,Ÿ/¦#" xstr(fl_aktl_mw_ix),
		"Cžopoc£« ¢o£oža,‰/Ÿ#" xstr(fl_rate_mw),
		"Mœ¡œ aŸ«¡ª ¢o£ož,Ÿ/¦#" xstr(min_fl_mw),
		"Ko ¢e¡ca¥œ®,Ÿ/¦#" xstr(flow_komp),
	"ƒa£a œ —pe ®#318",
		"acª#" xstr(std_1),
		"Mœ¡y£ª#" xstr(min_1),
		"ƒe¡«#" xstr(day),
		"Mec®¥#" xstr(mon),
		"‚o™#" xstr(year),
	"AER#319",
		"acª#" xstr(asr_std),
		"Mœ¡y£ª#" xstr(asr_min),
		"KoŸ-o— AER — cy£žœ#" xstr(asr_day),
		"…a¢yc£œ£« AER —py¦¡.#" xstr(set_nt),
	"Te ¢epa£ypa#320",
		"Ko ¢e¡ca¥œ®#" xstr(t_comp_t),
		"Py¦¡a® žo ¢e¡ca¥œ®,C#" xstr(t_man_comp),
		"Koppež£œpo—ža,C#" xstr(t_korr),
"Ho œ¡aŸ«¡ªe ›¡a¦e¡œ® “Ÿež£poŸœ›#321",
	"“Ÿež£poŸœ›#322",
		"ƒo›œpo—a¡œe coŸe—.pac£-pa,%#" xstr(sole_dos),
		"Ko¡£poŸ« ™oŸœ—a coŸ.pac£—., œ¡#" xstr(sole_nspw),
		"O˜pa¡œ¦œ£« £e ¢epa£ypy,C#" xstr(temp_lim_t),
		"Mažc.Te ¢epa£.¢po™yž£a,C#" xstr(maxt),
		"Ko¡¥e¡£pa¥œ® CL2,˜/Ÿ#" xstr(cl_konz),
		"‰po£ož,Ÿ/¦#" xstr(flow_ely),
		"Koppež£œpo—ža,C#" xstr(t0_korr),
		"Ko¡£poŸ« ¡a¢p®še¡œ®#" xstr(v_monitus_t),
	"E žoc£« ˜o£o—o˜o ¢po™yž£a#323",
		"Ko¡£poŸ« ypo—¡®#" xstr(lev_art_t),
		"Špo—e¡« ‰epeŸœ—,c #" xstr(prodlev_ovfl),
		"Špo—e¡«  ažc,c #" xstr(prodlev_max),
		"Špo—e¡«  œ¡,c #" xstr(prodlev_min),
		"A—apœ¡ª pešœ #" xstr(not_btr_t),
		"A—apœ¡ª xo™, œ¡#" xstr(not_zeit),
	"Be¡£œŸ®£op#324",
		"Bpe ® ¢pe™›a¢ycža,cež#" xstr(luft_vor),
		"Bpe ® ›a™epšžœ, œ¡#" xstr(luft_nach),
"PeŸe#325",
	"PeŸe 2 [#326",
		"Pac¢pe™eŸe¡œe#" xstr(r3_strg_t),
		"Tœ¢ pe˜yŸ®£opa#" xstr(r3_art_t),
		"ac£o£a œ ¢yŸ«co—,‰/¦#" xstr(r3_frq),
		"ƒŸœ£eŸ«¡oc£« ¢epœo™a,cež#" xstr(r3_pp),
		"Mœ¡œ aŸ«¡ª œ ¢yŸ«c,cež#" xstr(r3_min),
	"PeŸe 3 ]#327",
		"Pac¢pe™eŸe¡œe#" xstr(r4_strg_t),
		"Tœ¢ pe˜yŸ®£opa#" xstr(r4_art_t),
		"ac£o£a œ ¢yŸ«co—,‰/¦#" xstr(r4_frq),
		"ƒŸœ£eŸ«¡oc£« ¢epœo™a,cež#" xstr(r4_pp),
		"Mœ¡œ aŸ«¡ª œ ¢yŸ«c,cež#" xstr(r4_min),
"•›ªž#" xstr(sprache_t),
"…a—o™cža® ¡ac£poža#" xstr(set_nt),
"ƒa¡¡ªe ¢pœ–opa#328",
	"…a—o™cžo ¡o ep#" xstr(dev_nr_ix),
	"Bepcœ® ‰O#" xstr(softver_ix),
	"Bepcœ® ‰O y¢pa—Ÿ.¦ac£œ#" xstr(soft_strg_ix),
	"ƒa£a œ›˜o£o—Ÿe¡œ®#" xstr(mdate_in),
	"†›˜o£o—œ£eŸ«#329",
		"dinotec GmbH",
		"Phillipp-Reis Str. 28",
		"D-61130 Nidderau",
		"Tel: 0049 (0)6187 41379-0",
		"Hotline: 0049 (0)6187 41379-72",
		"www.dinotec.de",
		"service@dinotec.de",
"c—o–o™¡o",
"Be¡£œŸ®£op",
"Šc£a¡o—ža — pa–.pešœ e",
"Tpe—o˜a",
"‰o¡œ›œ£« pH",
"‰o—ªcœ£« pH",
"Redox",
"CL2",
"CL2,pH",
"CL2,pH,Redox",
"pH",
"pH,Redox",
"–e› œ› epœ£.o–opy™.",
"30",
"60",
"90",
"150",
"200",
"300",
"yc£a¡o—œ£«",
"c–pocœ£«",
"BªžŸ­¦e¡o",
"Hop - pešœ ",
"Ha¢.e ž.coŸ.pac£.",
"…a¢oŸ¡e¡.®¦ežœ",
"Ha¢oŸ¡e¡.yc£-—žœ",
"‚o£o—¡oc£« ž pa–o£e",
"E žoc£« coŸe—o˜o pac£—opa ¡a¢oŸ¡e¡a",
"•¦eža ¡a¢oŸ¡e¡a",
"Šc£a¡o—ža ¡a¢oŸe¡a",
"Šc£a¡o—ža ¢poœ›—o™œ£ ¢po™yž£",
"Pe˜e¡epa¥œ® y ®˜¦œ£eŸ®",
"Tpe—o˜a Pa–o¦œ pešœ ",
"‰pe™y¢peš™.‰po—epœ£« ƒE…-yc£a¡o—žy",
"Tpe—o˜a †› ep.ypo—¡® — e ž.¢po™yž£a",
"Tpe—o˜a ‰epeŸœ— e žoc£œ ¢po™yž£a",
"Tpe—o˜a Ha¢p®š.®¦ežœ cŸœ§.—ªcožoe",
"Tpe—o˜a Tož cŸœ§žo  —ªcožœ",
"Tpe—o˜a Tož cŸœ§žo  ¡œ›žœ",
"Tpe—o˜a ‰po£ož cŸœ§žo  —ªcožœ",
"Tpe—o˜a ‰po£ož cŸœ§žo  ¡œ›žœ",
"Tpe—o˜a Špo—e¡« e žoc£œ coŸe—. p-pa",
"BKˆ / B‘Kˆ",
"ac£o£a œ ¢yŸ«co—",
"† ¢yŸ«c-‰ay›a",
"ƒa",
"He£",
"py¦¡.",
"a—£o a£œ¦ecža®",
"‰pe™y¢peš™e¡œe CL2 —ªcožœ ",
"‰pe™y¢peš™e¡œe CL2 ¡œ›žœ ",
"‰pe™y¢p-e ¢po—epœ£« ‰OT-¬Ÿež£po™",
"Tpe—o˜a CL2 —ªcožœ",
"Tpe—o˜a CL2 ¡œ›žœ",
"Tpe—o˜a pH —ªcožœ",
"Tpe—o˜a pH ¡œ›žœ",
"Tpe—o˜a Redox",
"‰pe™y¢peš™e¡œe Redox",
"‰pe™y¢peš™e¡œe pH —ªcožœ",
"‰pe™y¢peš™e¡œe pH ¡œ›žœ",
"He™oc£a£ož œ› . —o™ª",
"†› epe¡œe",
"‰o¢Ÿa—ž.¢epežŸ.",
"†› epe¡œe ¢o£oža",
"B¡e§¡ee ¢pepª—a¡œe ™o›œpo—a¡œ®",
"He£ c—®›œ c y¢pa—Ÿ®­¨e ¦ac£«­",
"O§œ–ža žpy£œ›¡ª Cl2",
"O§œ–ža žpy£œ›¡ª ¬Ÿež£po™a pH ",
"O§œ–ža ¡yŸe—o £o¦žœ",
"Ka¡œc£pa pH ¢yc£a®",
"Bpe ® ™o›œpo—a¡œ® ƒE… ¢pe—ª§e¡o",
"Bpe ® ™o›œpo—a¡œ® pH+ ¢pe—ª§e¡o",
"Bpe ® ™o›œpo—a¡œ® pH- ¢pe—ª§e¡o",
"…a™epšža —žŸ­¦e¡œ® až£œ—œpo—a¡a",
"†™e£ ¡e¢pepª—¡oe ™o›œpo—a¡œe ƒE…",
"†™e£ ¡e¢pepª—¡oe ™o›œpo—a¡œe pH",
"‰pe—ª§e¡œe ™œa¢a›o¡a pe˜yŸ. ƒE…",
"He™oc£œše¡œe ™œa¢a›o¡a pe˜yŸ. ƒE…",
"‰pe—ª§e¡œe ™œa¢a›o¡a pe˜yŸ. pH",
"He™oc£œše¡œe ™œa¢a›o¡a pe˜yŸ. pH",
"Tpe—o˜a Te ¢ep.¢po™.cŸœ§žo  —ªcoža®",
"‰pe™y¢peš™.Te ¢ep.¢po™yž£a —ªcoža®",
"‰pe™y¢peš™.Te ¢ep.¢po™yž£a ¡œ›ža®",
"Tpe—o˜a Ha¢p®š.®¦ežœ cŸœ§ž.¡œ›žoe",
"‰poc£o ¡acŸaš™a£ec« Ÿy¦§e —o™o!",
"E žoc£« ˜o£o—o˜o ¢po™yž£a ¢yc£a®",
"ƒo›œpo—a¡œ® ožŸ­¦e¡o", 
"EŸež£poŸœ› o£žŸ­¦e¡", 
"‰pe™›a¢ycž —e¡£œŸ®£opa",					//   =vent_vor_txt
"…a™epšža o£žŸ. —e¡£œŸ®£opa",					//   =vent_nach_txt
"‰pe™y¢peš™e¡œe a—apœ¡o˜o pešœ a",
"0 - 1  ˜/Ÿ",
"0 - 10  ˜/Ÿ",
"‰po¥ecc ›a¢ycža,¢ošaŸyc£a,¢o™oš™.",
"¡e e¥žœ",
"a¡˜Ÿœcžœ",
"¤pa¡¥y›cžœ",
"œc¢a¡cžœ",
"¢oŸ«cžœ",
"yžpaœ¡cžœ",
"pyccžœ",
"œ£aŸ«®¡cžœ",
"¦e§cžœ",
"cŸo—e¡cžœ",
"xop—a£cžœ",
"—e¡˜epcžœ",
"py ª¡cžœ",
"˜oŸŸa¡™cžœ",
"cep–cžœ",
};
