const char* text_sl[] = {
"HAUPTMENU",
"Code#" xstr(code0_in),
"Betrieb Elektrolyse#" xstr(btr_art_t),
"Ger‚tekonfiguration#300",
	"Anlagetyp,g/h#" xstr(anl_typ_t),
	"Busadresse#" xstr(sh_adr),
	"Kontrast#" xstr(contr),
	"Messtechnik#" xstr(msr_t),
	"Messbereich Cl2#" xstr(mgl_t),
	"Cl2 pH-kompensiert#" xstr(set_nt),
"Kalibrierung#301",
	"Kalibrierung Clorsonde#302",
		"Messwert,mg/l#" xstr(cl_val_ix),
		"Steilheit,mV#" xstr(cl_sth_in),
		"Eingangsspannung,mV#" xstr(cl_mv_ix),
		"Speichern Uein:#" xstr(set_nt),
		"Uein gespeichert,mV#" xstr(uin_saved_ix),
		"Nullpunkt,mV#" xstr(cl_mv0_in),
		"Nullpunkt setzen#" xstr(set_nt),
		"DPD-Wert,mg/l#" xstr(cl_dpd_in),
		"Kalibrierungsreset#" xstr(set_nt),
		"Ende AER in Min#" xstr(aer_min_ix),
		"Kalibrierung nicht m†glich",
		"Messwert < 0,1 mg/l",
		"Messwert < 0,05 mg/l",
	"Kalibrierung pH#303",
		"Messwert,pH#" xstr(ph_ix),
		"Steilheit,mV/pH#" xstr(ph_sth_in),
		"Nullpunkt,mV#" xstr(ph_null_in),
		"Eingangsspannung,mV#" xstr(ph_mv_ix),
		"Kalibrierung pH4/7#" xstr(ph_dpd2_in),
		"Kalibrierungsreset#" xstr(set_nt),
"Sollwerte Messtechnik#304",
	"Einschaltverz†gerung,Min#" xstr(on_dly),
	"Sollwerte Cl2#305",
		"Sollwerte CL2#306",
			"Alarmwert oben,mg/l#" xstr(cl_alr_ob),
			"Warnwert oben,mg/l#" xstr(cl_wr_ob),
			"Sollwert,mg/l#" xstr(cl_soll),
			"Warnwert unten,mg/l#" xstr(cl_wr_un),
			"Alarmwert unten,mg/l#" xstr(cl_alr_un),
			"Alarmverz†gerung,Min#" xstr(cl_alr_dly),
		"Regelung CL2#307",
			"P-Bereich,mg/l#" xstr(cl_p),
			"Nachstellzeit,Sek#" xstr(cl_i),
			"Hysterese,mg/l#" xstr(cl_hys),
		"Dosier-Einstellungen#308",
			"man. Dauerdosierung,Min#" xstr(cl_man_dos),
			"Dauerdosierung einschalten#" xstr(set_nt),
			"Dosierzeit„berwachung,Min#" xstr(cl_dos_watch),
	"pH-Werte#309",
		"Sollwerte pH#310",
			"Alarmwert oben,pH#" xstr(ph_alr_ob),
			"Warnwert oben,pH#" xstr(ph_wr_ob),
			"Sollwert,pH#" xstr(ph_soll),
			"Warnwert unten,pH#" xstr(ph_wr_un),
			"Alarmwert unten,pH#" xstr(ph_alr_un),
			"Alarmverz†gerung,Min#" xstr(alr_dly_ph),
		"Regelung pH#311",
			"P-Bereich,pH#" xstr(ph_p),
			"Hysterese,pH#" xstr(ph_hys),
			"Nachstellzeit,Sek#" xstr(ph_zi),
			"Totband,pH#" xstr(totband_ph),
		"Dosier-Einstellungen#312",
			"man. Dauerdosierung,Min#" xstr(ph_man_dos),
			"Dauerdosierung einschalten#" xstr(set_nt),
			"Dosierzeit„berwachung,Min#" xstr(ph_dos_watch),
	"Redox#313",
		"Sollwerte Redox#314",
			"Messwert,mV#" xstr(rx_ix),
			"Sollwert,mV#" xstr(rx_soll),
			"Warnwert unten,mV#" xstr(rx_wr_un),
			"Alarmwert unten,mV#" xstr(rx_alr_un),
			"Alarmverz†gerung,Min#" xstr(alr_dly_rx),
		"Regelung Redox#315",
			"P-Bereich,mV#" xstr(rx_p),
			"Hysterese,mV#" xstr(rx_hys),
		"Dosier-Einstellungen#316",
			"man. Dauerdosierung,Min#" xstr(rx_man_dos),
			"Dauerdosierung einschalten#" xstr(set_nt),
			"Dosierzeit„berwachung,Min#" xstr(rx_dos_watch),
	"Messwasser„berwachung#317",
		"Art#" xstr(mw_art_t),
		"Durchfluss,l/h#" xstr(fl_aktl_mw_ix),
		"Durchflussrate,P/l#" xstr(fl_rate_mw),
		"mininmale Durchfluss,l/h#" xstr(min_fl_mw),
		"Kompensation,l/h#" xstr(flow_komp),
	"Datum und Uhrzeit#318",
		"Stunden#" xstr(std_1),
		"Minuten#" xstr(min_1),
		"Tag#" xstr(day),
		"Monat#" xstr(mon),
		"Jahr#" xstr(year),
	"AER#319",
		"Stunden#" xstr(asr_std),
		"Minuten#" xstr(asr_min),
		"Anzahl AER pro Tag#" xstr(asr_day),
		"AER manuell starten#" xstr(set_nt),
	"Temperatur#320",
		"Kompensation#" xstr(t_comp_t),
		"Manuelle Kompensation,C#" xstr(t_man_comp),
		"Korrektur,C#" xstr(t_korr),
"Sollwerte Elektrolyse#321",
	"Elektrolyse#322",
		"Soledosierung,%#" xstr(sole_dos),
		"Solenachspeise„berwachung,Min#" xstr(sole_nspw),
		"Temperatur begrenzen,C#" xstr(temp_lim_t),
		"Max. Produkttemp.C#" xstr(maxt),
		"CL2-Konzentration,g/l#" xstr(cl_konz),
		"Durchfluss,l/h#" xstr(flow_ely),
		"Korrektur,C#" xstr(t0_korr),
		"Spannungs„berwachung#" xstr(v_monitus_t),
	"Produkttank#323",
		"Niveau„berwachung#" xstr(lev_art_t),
		"Niveau ƒberlauf,cm#" xstr(prodlev_ovfl),
		"Niveau max,cm#" xstr(prodlev_max),
		"Niveau min,cm#" xstr(prodlev_min),
		"Notbetrieb#" xstr(not_btr_t),
		"Notlaufzeit,Min#" xstr(not_zeit),
	"Ventilator#324",
		"Vorlaufzeit,Sek#" xstr(luft_vor),
		"Nachlaufzeit,Min#" xstr(luft_nach),
"Relais#325",
	"Relais 2 [#326",
		"Zuordnung#" xstr(r3_strg_t),
		"Reglerart#" xstr(r3_art_t),
		"Pulsfrequenz,P/h#" xstr(r3_frq),
		"Periodendauer,Sek#" xstr(r3_pp),
		"Mindestimpuls,Sek#" xstr(r3_min),
	"Relais 3 ]#327",
		"Zuordnung#" xstr(r4_strg_t),
		"Reglerart#" xstr(r4_art_t),
		"Pulsfrequenz,P/h#" xstr(r4_frq),
		"Periodendauer,Sek#" xstr(r4_pp),
		"Mindestimpuls,Sek#" xstr(r4_min),
"Sprache#" xstr(sprache_t),
"Werkeinstellung#" xstr(set_nt),
"Ger‚tedaten#328",
	"Ger‚tenummer#" xstr(dev_nr_ix),
	"Softwarestand#" xstr(softver_ix),
	"Softwarestand-Steuerung#" xstr(soft_strg_ix),
	"Herstelldatum#" xstr(mdate_in),
	"Hersteller#329",
		"dinotec GmbH",
		"Phillipp-Reis Str. 28",
		"D-61130 Nidderau",
		"Tel: 0049 (0)6187 41379-0",
		"Hotline: 0049 (0)6187 41379-72",
		"www.dinotec.de",
		"service@dinotec.de",
"Frei",
"Ventilator",
"Anlage im Betrieb",
"Alarm",
"pH-senken",
"pH-heben",
"Redox",
"CL2",
"CL2,pH",
"CL2,pH,Redox",
"pH",
"pH,Redox",
"ohne Messtechnik",
"30",
"60",
"90",
"150",
"200",
"300",
"setzen",
"zur„cksetzen",
"abgeschaltet",
"Normalbetrieb",
"Soletank f„llen",
"Zelle f„llen",
"Anlage f„llen",
"Anlage bereit",
"Soletank gef„llt",
"Zelle gef„llt",
"Anlage gef„llt",
"Anlage produziert",
"Enth‚rter regeneriert",
"Alarm Anlagenbetrieb",
"Warnung DES-Anlage pr„fen",
"Alarm Niveaumessung Produkttank",
"Alarm Produkttank ƒberlauf",
"Alarm Zellenspannung zu hoch",
"Alarm Strom zu hoch",
"Alarm Strom zu niedrig",
"Alarm Durchfluss zu hoch",
"Alarm Durchfluss zu niedrig",
"Alarm Niveau Soletank",
"AN-AUS",
"Pulsfrequenz",
"Puls-Pause",
"Ja",
"Nein",
"manuell",
"automatisch",
"Warnung oben CL2",
"Warnung unten CL2",
"Warnung POT-Sonde pr„fen",
"Alarm oben CL2",
"Alarm unten CL2",
"Alarm pH oben",
"Alarm pH unten",
"Alarm Redox",
"Warnung Redox",
"Warnung pH oben",
"Warnung pH unten",
"Messwassermangel",
"Niveaumessung",
"Schwimmerschalter",
"Durchflu‡messung",
"Externer Dosierstopp",
"Keine Verbindung zu Steurteil",
"Steilheitsfehler Cl2",
"Steilheitsfehler pH",
"Nullpunktfehler",
"pH Kanister ist leer",
"Dosierzeit Desinfektion „berschritten",
"Dosierzeit pH heben „berschritten",
"Dosierzeit pH senken „berschritten",
"Einschaltverz†gerung aktiv",
"Dauerdosierung Desinfektion l‚uft",
"Dauerdosierung pH l‚uft",
"Regelgrenze Desinfektion „berschritten",
"Regelgrenze Desinfektion unterschritten",
"Regelgrenze pH „berschritten",
"Regelgrenze pH unterschritten",
"Alarm Produkttemperatur zu hoch",
"Warnung Produkttemperatur hoch",
"Warnung Produkttemperatur niedrig",
"Alarm Zellenspannung zu niedrig",
"Einfach bestes Wasser genie‡en",
"Produkttank ist leer",
"Dosierung abgeschaltet",
"Elektrolyse abgeschaltet",
"Ventilator Vorlauf",					//   =vent_vor_txt
"Ventilator Nachlauf",					//   =vent_nach_txt
"Warnung Notbetrieb",
"0 - 1 mg/l",
"0 - 10 mg/l",
"Startvorgang, bitte warten",
"Deutsch",
"Englisch",
"Franz†sisch",
"Spanisch",
"Polnisch",
"Ukrainisch",
"Russisch",
"Italienisch",
"Tschechisch",
"Slovenisch",
"Kroatisch",
"Ungarisch",
"Rum‚nisch",
"Niederl‚ndisch",
"Serbisch",
};
