const char* text_hu[] = {
"F©menÑ",
"Kèdok#" xstr(code0_in),
"Eletrolizis Ñzemel#" xstr(btr_art_t),
"KåszÑlåk felåpítåse#300",
	"Berendezås típusa,g/h#" xstr(anl_typ_t),
	"BUS cím#" xstr(sh_adr),
	"Kontraszt#" xstr(contr),
	"Måråsi lehet©sågek#" xstr(msr_t),
	"Måråsi tartomàny Cl2#" xstr(mgl_t),
	"Cl2 pH-kompenzàlt#" xstr(set_nt),
"Kalibràciè#301",
	"Klèrszonda kalibràciè#302",
		"Mår tårtåk,mg/l#" xstr(cl_val_ix),
		"Meredåksåg,mV#" xstr(cl_sth_in),
		"Bemeneti feszÑltsåg,mV#" xstr(cl_mv_ix),
		"Tàrolàs U be:#" xstr(set_nt),
		"U be tàrolva,mV#" xstr(uin_saved_ix),
		"Nullpont,mV#" xstr(cl_mv0_in),
		"Nullpont beàllítàs#" xstr(set_nt),
		"DPD-årtåk,mg/l#" xstr(cl_dpd_in),
		"Kalibràciè visszaàllítàsa#" xstr(set_nt),
		"AER våge be, Min#" xstr(aer_min_ix),
		"Kalibràciè nem lehetsåges",
		"Mår tårtåk < 0,1 mg/l",
		"Mår tårtåk < 0,05 mg/l",
	"kalibràciè pH-szonda#303",
		"Mår tårtåk,pH#" xstr(ph_ix),
		"Meredåksåg,mV/pH#" xstr(ph_sth_in),
		"Nullpont,mV#" xstr(ph_null_in),
		"Bemeneti feszÑltsåg,mV#" xstr(ph_mv_ix),
		"Kalibràciè pH4/7#" xstr(ph_dpd2_in),
		"Kalibràciè visszaàllítàsa#" xstr(set_nt),
"Kívànt årtåk måråsi lehet©sågek#304",
	"bekapcsolàsi kåsleltetås,Min#" xstr(on_dly),
	"Kívànt årtåk Cl2#305",
		"Kívànt årtåk CL2#306",
			"Fels© riadè årtåk,mg/l#" xstr(cl_alr_ob),
			"Figyelmeztet© årtåk magas,mg/l#" xstr(cl_wr_ob),
			"Ideàlis årtåk,mg/l#" xstr(cl_soll),
			"Figyelmezt.årtåk alacsony,mg/l#" xstr(cl_wr_un),
			"Alsè Riadè årtåk ,mg/l#" xstr(cl_alr_un),
			"Riasztàsi kåsleltetås,Min#" xstr(cl_alr_dly),
		"Szabàlyozàs CL2#307",
			"P-tartomàny,mg/l#" xstr(cl_p),
			"Utànàllítàsi id©,Sek#" xstr(cl_i),
			"Hiszteråzis ,mg/l#" xstr(cl_hys),
		"Adagolàsi beàllítàsok#308",
			"Kåzi folyamatos adagolàs,Min#" xstr(cl_man_dos),
			"Folyamatos adagolàst bekapcs.#" xstr(set_nt),
			"Adagolàsi id© felÑgyelete,Min#" xstr(cl_dos_watch),
	"pH årtåkek#309",
		"Ideàlis årtåk pH#310",
			"Fels© riadè årtåk,pH#" xstr(ph_alr_ob),
			"Figyelmeztet© årtåk magas,pH#" xstr(ph_wr_ob),
			"Ideàlis årtåk,pH#" xstr(ph_soll),
			"Figyelmeztet© årtåk alacs.,pH#" xstr(ph_wr_un),
			"Alsè Riadè årtåk ,pH#" xstr(ph_alr_un),
			"Riasztàsi kåsleltetås,Min#" xstr(alr_dly_ph),
		"Szabàlyozàs pH#311",
			"P-tartomàny,pH#" xstr(ph_p),
			"Hiszteråzis ,pH#" xstr(ph_hys),
			"Utànàllítàsi id©,Sek#" xstr(ph_zi),
			"Holt szakasz,pH#" xstr(totband_ph),
		"Adagolàsi beàllítàsok#312",
			"Kåzi folyamatos adagolàs,Min#" xstr(ph_man_dos),
			"Folyamatos adagolàst bekapcs.#" xstr(set_nt),
			"Adagolàsi id© felÑgyelete,Min#" xstr(ph_dos_watch),
	"Redox#313",
		"Ideàlis årtåk redox#314",
			"Mår tårtåk,mV#" xstr(rx_ix),
			"Ideàlis årtåk,mV#" xstr(rx_soll),
			"Figyelmeztet© årtåk alacs.,mV#" xstr(rx_wr_un),
			"Alsè Riadè årtåk ,mV#" xstr(rx_alr_un),
			"Riasztàsi kåsleltetås,Min#" xstr(alr_dly_rx),
		"Szabàlyozàs Redox#315",
			"P-tartomàny,mV#" xstr(rx_p),
			"Hiszteråzis ,mV#" xstr(rx_hys),
		"Adagolàsi beàllítàsok#316",
			"Kåzi folyamatos adagolàs,Min#" xstr(rx_man_dos),
			"Folyamatos adagolàst bekapcs.#" xstr(set_nt),
			"Adagolàsi id© felÑgyelete,Min#" xstr(rx_dos_watch),
	"Mår©víz mennyisåg figyelås#317",
		"Cikkszàm#" xstr(mw_art_t),
		"àtfolyàs,l/h#" xstr(fl_aktl_mw_ix),
		"àtfolyàsi mennyisåg,P/l#" xstr(fl_rate_mw),
		"minimàlis àtfolyàs,l/h#" xstr(min_fl_mw),
		"Kompenzàciè,l/h#" xstr(flow_komp),
	"Dàtum ås id©#318",
		"èràk#" xstr(std_1),
		"Perc#" xstr(min_1),
		"Nap#" xstr(day),
		"Hènap#" xstr(mon),
		"åv#" xstr(year),
	"AER#319",
		"èràk#" xstr(asr_std),
		"Perc#" xstr(asr_min),
		"AER napi szàma#" xstr(asr_day),
		"AER kåzi indítàsa#" xstr(set_nt),
	"H©mårsåklet#320",
		"Kompenzàciè#" xstr(t_comp_t),
		"Kåzi kompenzàciè,C#" xstr(t_man_comp),
		"Korrekciè,C#" xstr(t_korr),
"Kívànt årtåk elektrolízis#321",
	"Elektrolizís#322",
		"Sèlå adagolàs,%#" xstr(sole_dos),
		"Sèlå utànpètlàs felÑgyel.,Min#" xstr(sole_nspw),
		"H©mårsåkletet behatàrolni,C#" xstr(temp_lim_t),
		"Max. termåk h©mårsåklet#" xstr(maxt),
		"CL2-koncentràciè,g/l#" xstr(cl_konz),
		"àtfolyàs,l/h#" xstr(flow_ely),
		"Korrekciè,C#" xstr(t0_korr),
		"FeszÑltsåg figyelåse#" xstr(v_monitus_t),
	"Termåktartàly#323",
		"Szintjånek monitorozàsa#" xstr(lev_art_t),
		"Szint tîltÜltve,cm#" xstr(prodlev_ovfl),
		"Szint max.,cm#" xstr(prodlev_max),
		"Szint min.,cm#" xstr(prodlev_min),
		"VåszÑzem#" xstr(not_btr_t),
		"Ilyenkor,min#" xstr(not_zeit),
	"Ventilàtor#324",
		"El©refutàsi id©,s#" xstr(luft_vor),
		"Utànfutàsi id©,min#" xstr(luft_nach),
"Relåk#325",
	"Relais 2 [#326",
		"Hozzàrendelås#" xstr(r3_strg_t),
		"Szabàlyozàsi forma#" xstr(r3_art_t),
		"Inpulzus_frekvencia,P/h#" xstr(r3_frq),
		"Perièdusid©,Sek#" xstr(r3_pp),
		"Minimum impulzus,Sek#" xstr(r3_min),
	"Relais 3 ]#327",
		"Hozzàrendelås#" xstr(r4_strg_t),
		"Szabàlyozàsi forma#" xstr(r4_art_t),
		"Inpulzus_frekvencia,P/h#" xstr(r4_frq),
		"Perièdusid©,Sek#" xstr(r4_pp),
		"Minimum impulzus,Sek#" xstr(r4_min),
"Nyelv#" xstr(sprache_t),
"Gyàri beàllítàs#" xstr(set_nt),
"KåszÑlåkadatok#328",
	"Gyàtàsi szàm#" xstr(dev_nr_ix),
	"Software kåszítås ideje#" xstr(softver_ix),
	"Software verzièvezårl© råsz#" xstr(soft_strg_ix),
	"Gyàrtàs ideje#" xstr(mdate_in),
	"Gyàrtè#329",
		"dinotec GmbH",
		"Phillipp-Reis Str. 28",
		"D-61130 Nidderau",
		"Tel: 0049 (0)6187 41379-0",
		"Hotline: 0049 (0)6187 41379-72",
		"www.dinotec.de",
		"service@dinotec.de",
"Ingyenes",
"Ventilàtor",
"Berendezås Ñzemel",
"Riasztàs",
"pH csÜkkentås",
"pH-emelås",
"Redox",
"CL2",
"CL2,pH",
"CL2,pH,Redox",
"pH",
"pH,Redox",
"Måråstechnika nålkÑl",
"30",
"60",
"90",
"150",
"200",
"300",
"elfogad/tàrol",
"visszaàllít",
"Lekapcsolva",
"NormàlÑzem",
"Sèlåoldè tartàlyt tÜltse fel",
"Cellàt tÜlteni",
"Berendezås tÜltåse",
"A kåszÑlåk hasznàlatra kåszen àll",
"Sèlå tartàly feltÜltve",
"Cella feltÜltve",
"Berendezås feltÜltve",
"Berendezås termel",
"Vízlàgyítèt regeneràlni",
"Rendszer riasztàs",
"Figyelmezt.DES ellen©rizni",
"Riasztàs szintjelzås a termåktan.",
"Riasztàs termåktank tîltÜltve",
"Riasztàsi cella feszÑltsåge tîl magas",
"Riasztàs àramfelvåtel tîl magas",
"Riasztàs àramfelvåtel tîl alacsony",
"Riasztàs tîl magas àtfolyàs",
"Riasztàs tîl alacson àtfolyàs",
"Riasztàs sèlåoldètrtàly szintje",
"Be-Ki",
"Inpulzus frekvencia",
"Impulzus szÑnet",
"Igen",
"Nem",
"kåzi",
"automatikus",
"Figyelmezt. CL2 årtåk tîl magas",
"Figyelmezt. CL2 årtåk tîl alacsony",
"Figyelmezt.POT szondàt ellen©rizni",
"Riasztàs CL2 fels©årtåk",
"Riasztàs CL2 alsèårtåk",
"Riasztàs pH fels©årtåk ",
"Riasztàs pH alsèårtåk ",
"Riasztàs Redox",
"Figyelem Redox årtåk ",
"Figyelem pH fels©årtåk ",
"Figyelem pH alsèårtåk ",
"Mår©vízhiàny",
"Szintmårås",
"îszèkapcsolè",
"àtfolyàs måråse",
"KÑls© adagolàsi tiltàs",
"Nincs kapcsolat a vezårl©egysåghez",
"CL2 meredeksågi hiba",
"Meredåksågi hiba pH",
"Nullponthiba",
"pH kanna Ñres",
"Adagolàsiid© fert©tlenítås tîllåpve",
"Adagolàsiid© pH emelås tîllåpve",
"Adagolàsiid© pH csÜkk. tîllåpve",
"bekapcsolàsi kåsleltetås aktiv",
"Fertotlenít.folyamatos adagolàsa",
"pH szabàlyzè folyamatos adagolàsa",
"Fert©tlenít.szabàlyoz.hatàr tîllåpv",
"Fert©tlenít.szabàlyoz.hatàr tîllåpv",
"pH szabàlyozàsi hatàr tîllåpve",
"pH szabàlyozàsi hatàr alacsony",
"Riasztàs termåk h©mårsåk.tîl magas",
"Figyelmezt.termåk h©mårsåklet magas",
"Figyelmezt.termåkh©mårs.alacsony",
"Riasztàs cella fesz˚ltsåg alacsony",
"Legyen az Ün vize a legjobb",
"Termåktartàly Ñres",
"Adagolàs lekapcsolva", 
"Eletrolizis lekapcsolva",
"Ventilàtor el©refutàs",					//   =vent_vor_txt
"Ventilàtor utànfutàs",					//   =vent_nach_txt
"Våszhelyzeti figyelmeztetås",					
"0 - 1 mg/l",
"0 - 10 mg/l",
"Indítàsi folyamat, kårjÑk vàrjon",
"Nåmet",
"Angol",
"Francia",
"Spanyol",
"Lengyel",
"Ukràn",
"Orosz",
"Olasz",
"Cseh",
"Slovån",
"Horvàth",
"Magyar",
"Romàn",
"Holland",
"Szerb",
};
