const char* text_ro[] = {
"MENIU BAZ ",
"Cod#" xstr(code0_in),
"Func¢ionare electroliz #" xstr(btr_art_t),
"Configurare aparat#300",
	"Tip instala¢ie,g/h#" xstr(anl_typ_t),
	"Adres  bus#" xstr(sh_adr),
	"Contrast#" xstr(contr),
	"Tehnic  m sur #" xstr(msr_t),
	"Interval masur re Cl2#" xstr(mgl_t),
	"Cl2 compensat pH#" xstr(set_nt),
"Calibrare#301",
	"Calibrare sond  clor#302",
		"Val. m sur ,mg/l#" xstr(cl_val_ix),
		"Pant ,mV#" xstr(cl_sth_in),
		"Tensiune intrare,mV#" xstr(cl_mv_ix),
		"Memorare Uein:#" xstr(set_nt),
		"Uein memorat,mV#" xstr(uin_saved_ix),
		"Punct nul,mV#" xstr(cl_mv0_in),
		"setare punct nul#" xstr(set_nt),
		"Valoare-DPD,mg/l#" xstr(cl_dpd_in),
		"Reset calibrare #" xstr(set_nt),
		"Final AER in, Min#" xstr(aer_min_ix),
		"Calibrarea nu e posibil ",
		"Val. m sur  < 0,1 mg/l",
		"Val. m sur  < 0,05 mg/l",
	"Calibrare pH#303",
		"Val. m sur ,pH#" xstr(ph_ix),
		"Pant ,mV/pH#" xstr(ph_sth_in),
		"Punct nul,mV#" xstr(ph_null_in),
		"Tensiune intrare,mV#" xstr(ph_mv_ix),
		"Calibrare pH4/7#" xstr(ph_dpd2_in),
		"Reset calibrare #" xstr(set_nt),
"Val neces tehnic  m sur #304",
	"Delay conectare,Min#" xstr(on_dly),
	"Val necesare Cl2#305",
		"Val necesare CL2#306",
			"Valoare alarm  sus,mg/l#" xstr(cl_alr_ob),
			"Val avertizare sus,mg/l#" xstr(cl_wr_ob),
			"Val. necesar ,mg/l#" xstr(cl_soll),
			"Val. avertiz. jos,mg/l#" xstr(cl_wr_un),
			"Valoare alarm  jos,mg/l#" xstr(cl_alr_un),
			"Delay alarm ,Min#" xstr(cl_alr_dly),
		"Reglare CL2#307",
			"Interval-P,mg/l#" xstr(cl_p),
			"Timp de ajustare,Sek#" xstr(cl_i),
			"Histerez ,mg/l#" xstr(cl_hys),
		"Set ri-Dozare#308",
			"Dozare const. man. ,Min#" xstr(cl_man_dos),
			"Pornire dozare temporar #" xstr(set_nt),
			"Monitorizare timp dozare,Min#" xstr(cl_dos_watch),
	"Valori pH#309",
		"Val necesare pH#310",
			"Valoare alarm  sus,pH#" xstr(ph_alr_ob),
			"Val avertizare sus,pH#" xstr(ph_wr_ob),
			"Val. necesar ,pH#" xstr(ph_soll),
			"Val. avertiz. jos,pH#" xstr(ph_wr_un),
			"Valoare alarm  jos,pH#" xstr(ph_alr_un),
			"Delay alarm ,Min#" xstr(alr_dly_ph),
		"Reglare pH#311",
			"Interval-P,pH#" xstr(ph_p),
			"Histerez ,pH#" xstr(ph_hys),
			"Timp de ajustare,Sek#" xstr(ph_zi),
			"Band  moart ,pH#" xstr(totband_ph),
		"Set ri-Dozare#312",
			"Dozare const. man. ,Min#" xstr(ph_man_dos),
			"Pornire dozare temporar #" xstr(set_nt),
			"Monitorizare timp dozare,Min#" xstr(ph_dos_watch),
	"Redox#313",
		"Val. necesar Redox#314",
			"Val. m sur ,mV#" xstr(rx_ix),
			"Val. necesar ,mV#" xstr(rx_soll),
			"Val. avertiz. jos,mV#" xstr(rx_wr_un),
			"Valoare alarm  jos,mV#" xstr(rx_alr_un),
			"Delay alarm ,Min#" xstr(alr_dly_rx),
		"Reglare Redox#315",
			"Interval-P,mV#" xstr(rx_p),
			"Histerez ,mV#" xstr(rx_hys),
		"Set ri-Dozare#316",
			"Dozare const. man. ,Min#" xstr(rx_man_dos),
			"Pornire dozare temporar #" xstr(set_nt),
			"Monitorizare timp dozare,Min#" xstr(rx_dos_watch),
	"Monitorizare ap  m sur #317",
		"Tip#" xstr(mw_art_t),
		"Flux,l/h#" xstr(fl_aktl_mw_ix),
		"Rat  flux,P/l#" xstr(fl_rate_mw),
		"flux minim,l/h#" xstr(min_fl_mw),
		"Compensare,l/h#" xstr(flow_komp),
	"Data ¢i ora#318",
		"Ore#" xstr(std_1),
		"Minute#" xstr(min_1),
		"Zi#" xstr(day),
		"Lun #" xstr(mon),
		"An#" xstr(year),
	"AER#319",
		"Ore#" xstr(asr_std),
		"Minute#" xstr(asr_min),
		"Contor AER pe zi#" xstr(asr_day),
		"AER pornire manual #" xstr(set_nt),
	"Temperatur #320",
		"Compensare#" xstr(t_comp_t),
		"Compensare manual ,C#" xstr(t_man_comp),
		"Corectare,C#" xstr(t_korr),
"Val necesare electroliz #321",
	"Electroliz #322",
		"Dozare saramur ,%#" xstr(sole_dos),
		"Monitor.reumplere saram.,Min#" xstr(sole_nspw),
		"Limitare temperatur ,C#" xstr(temp_lim_t),
		"Temp. produs max.C#" xstr(maxt),
		"Concentra¢ie CL2,g/l#" xstr(cl_konz),
		"Flux,l/h#" xstr(flow_ely),
		"Corectare,C#" xstr(t0_korr),
		"Monitorizare a tensiunii#" xstr(v_monitus_t),
	"Vas produs#323",
		"Monitor.nivelului#" xstr(lev_art_t),
		"Nivel supraplin,cm#" xstr(prodlev_ovfl),
		"Nivel max,cm#" xstr(prodlev_max),
		"Nivel min,cm#" xstr(prodlev_min),
		"Opera¢iune de urgen¢ #" xstr(not_btr_t),
		"Func¢ionare de urgen¢ ,min#" xstr(not_zeit),
	"Ventilator#324",
		"Timp func¢ionare prelabil ,sec#" xstr(luft_vor),
		"Timp func¢.iner¢ial , min#" xstr(luft_nach),
"Releu#325",
	"Releu 2 [#326",
		"Atribuire#" xstr(r3_strg_t),
		"Tip control#" xstr(r3_art_t),
		"Frecven¢  puls,P/h#" xstr(r3_frq),
		"Durat  perioad ,Sek#" xstr(r3_pp),
		"Impuls minim,Sek#" xstr(r3_min),
	"Releu 3 ]#327",
		"Atribuire#" xstr(r4_strg_t),
		"Tip control#" xstr(r4_art_t),
		"Frecven¢  puls,P/h#" xstr(r4_frq),
		"Durat  perioad ,Sek#" xstr(r4_pp),
		"Impuls minim,Sek#" xstr(r4_min),
"Limb #" xstr(sprache_t),
"Set ri fabric #" xstr(set_nt),
"Date aparat#328",
	"Num r aparat#" xstr(dev_nr_ix),
	"Stadiu software#" xstr(softver_ix),
	"Control.versiunii softw.#" xstr(soft_strg_ix),
	"Data fabric rii#" xstr(mdate_in),
	"Produc tor#329",
		"dinotec GmbH",
		"Phillipp-Reis Str. 28",
		"D-61130 Nidderau",
		"Tel: 0049 (0)6187 41379-0",
		"Hotline: 0049 (0)6187 41379-72",
		"www.dinotec.de",
		"service@dinotec.de",
"Frei",
"Ventilator",
"Instala¢ie in func¢iune",
"Alarm ",
"Sc dere pH",
"Ridicare pH",
"Redox",
"CL2",
"CL2,pH",
"CL2,pH,Redox",
"pH",
"pH,Redox",
"f r  tehnic  m sur ",
"30",
"60",
"90",
"150",
"200",
"300",
"setare",
"resetare",
"Oprit",
"Func¢ionare normal ",
"Umplere vas saramur ",
"Umplere celul ",
"Umplere instala¢ie",
"Instal preg tit ",
"Vas saramur  umplut",
"Celul  plin ",
"Instala¢ie plin ",
"Instala¢ia produce",
"Regenerare dedurizator",
"Alarm  func¢ionare aparat",
"Avertizare verif instal DES",
"Alarm  m surare nivel vas produs",
"Alarm  supraplin vas produs",
"Alarm  tensiune celul  prea mic ",
"Alarm  curent prea mare",
"Alarm  curent prea mic",
"Alarm  flux prea mare",
"Alarm  flux prea mic",
"Alarm  nivel vas saramur ",
"ON-OFF",
"Frecven¢  puls",
"Pauz -Puls",
"Da",
"Nu",
"manual",
"Automat",
"Avertizare CL2 sus",
"Avertizare CL2 jos",
"Avertizare verif sond -POT",
"Alarm  Cl2 prea mult",
"Alarm  Cl2 prea pu¢in",
"Alarm  pH sus",
"Alarm  pH jos",
"Alarm  Redox",
"Avertizare Redox",
"Avertizare pH sus",
"Avertizare pH jos",
"Lips  ap  m sur ",
"M surarea nivelului",
"Contactor plutitor",
"M surare flux",
"Stop dozare extern ",
"F r  conexiune terminal comand ",
"Eroare pant  Cl2",
"Eroare pant  pH",
"Eroare punct nul",
"Canistra pH este goal ",
"Durat  dozare dezinfectare dep ¢it  ",
"Durat  dozare pH ridicare dep ¢it ",
"Durat  dozare pH sc dere dep ¢it ",
"Delay pornire activ",
"Dozare constant  dezinfectare fc¢",
"Dozare contant  pH fc¢",
"Nivel reglare dezinfectare dep ¢it",
"Nivel reglare dezinfectare sub limit ",
"Nivel reglare pH dep ¢it",
"Nivel reglare pH sub limit  ",
"Alarm  temparatur  produs prea mare",
"Avertizare temp produs mare",
"Avertizare temp produs mic",
"Alarm  tensiune celul  prea mic ",
"Pur ¢i simplu apa perfect !",
"Vas produs este goal ",
"Dozare oprit", 
"Electroliz  oprit",
"Func¢.prealabil  ventilator",					//   =vent_vor_txt
"Postfunc¢ionare ventilator",					//   =vent_nach_txt
"Avertisment de operare de urgen¢ ",					
"0 - 1 mg/l",
"0 - 10 mg/l",
"Proces.de pornire,v  rug.s  a¡tept.",
"German ",
"Englez ",
"Francez ",
"Spaniol ",
"Polonez ",
"Ucrainean ",
"Rus ",
"Italian ",
"Ceh ",
"Sloven ",
"Croat ",
"Ungar ",
"RomŠn ",
"Olandez ",
"SŠrb ",
};
