char* text_hu[] = {
"Főmenü",
"Kódok#" xstr(code0_in),
"Eletrolizis üzemel#" xstr(btr_art_t),
"Készülék felépítése#300",
	"Berendezés típusa,g/h#" xstr(anl_typ_t),
	"BUS cím#" xstr(sh_adr),
	"Kontraszt#" xstr(contr),
	"Mérési lehetőségek#" xstr(msr_t),
	"Mérési tartomány Cl2#" xstr(mgl_t),
	"Cl2 pH-kompenzált#" xstr(set_nt),
"Kalibráció#301",
	"Klórszonda kalibráció#302",
		"Mér térték,mg/l#" xstr(cl_val_ix),
		"Meredékség,mV#" xstr(cl_sth_in),
		"Bemeneti feszültség,mV#" xstr(cl_mv_ix),
		"Tárolás U be:#" xstr(set_nt),
		"U be tárolva,mV#" xstr(uin_saved_ix),
		"Nullpont,mV#" xstr(cl_mv0_in),
		"Nullpont beállítás#" xstr(set_nt),
		"DPD-érték,mg/l#" xstr(cl_dpd_in),
		"Kalibráció visszaállítása#" xstr(set_nt),
		"AER vége be, Min#" xstr(aer_min_ix),
		"Kalibráció nem lehetséges",
		"Mér térték < 0,1 mg/l",
		"Mér térték < 0,05 mg/l",
	"kalibráció pH-szonda#303",
		"Mér térték,pH#" xstr(ph_ix),
		"Meredékség,mV/pH#" xstr(ph_sth_in),
		"Nullpont,mV#" xstr(ph_null_in),
		"Bemeneti feszültség,mV#" xstr(ph_mv_ix),
		"Kalibráció pH4/7#" xstr(ph_dpd2_in),
		"Kalibráció visszaállítása#" xstr(set_nt),
"Kívánt érték mérési lehetőségek#304",
	"bekapcsolási késleltetés,Min#" xstr(on_dly),
	"Kívánt érték Cl2#305",
		"Kívánt érték CL2#306",
			"Felső riadó érték,mg/l#" xstr(cl_alr_ob),
			"Figyelmeztető érték magas,mg/l#" xstr(cl_wr_ob),
			"Ideális érték,mg/l#" xstr(cl_soll),
			"Figyelmezt.érték alacsony,mg/l#" xstr(cl_wr_un),
			"Alsó Riadó érték ,mg/l#" xstr(cl_alr_un),
			"Riasztási késleltetés,Min#" xstr(cl_alr_dly),
		"Szabályozás CL2#307",
			"P-tartomány,mg/l#" xstr(cl_p),
			"Utánállítási idő,Sek#" xstr(cl_i),
			"Hiszterézis ,mg/l#" xstr(cl_hys),
		"Adagolási beállítások#308",
			"Kézi folyamatos adagolás,Min#" xstr(cl_man_dos),
			"Folyamatos adagolást bekapcs.#" xstr(set_nt),
			"Adagolási idő felügyelete,Min#" xstr(cl_dos_watch),
	"pH értékek#309",
		"Ideális érték pH#310",
			"Felső riadó érték,pH#" xstr(ph_alr_ob),
			"Figyelmeztető érték magas,pH#" xstr(ph_wr_ob),
			"Ideális érték,pH#" xstr(ph_soll),
			"Figyelmeztető érték alacs.,pH#" xstr(ph_wr_un),
			"Alsó Riadó érték ,pH#" xstr(ph_alr_un),
			"Riasztási késleltetés,Min#" xstr(alr_dly_ph),
		"Szabályozás pH#311",
			"P-tartomány,pH#" xstr(ph_p),
			"Hiszterézis ,pH#" xstr(ph_hys),
			"Utánállítási idő,Sek#" xstr(ph_zi),
			"Holt szakasz,pH#" xstr(totband_ph),
		"Adagolási beállítások#312",
			"Kézi folyamatos adagolás,Min#" xstr(ph_man_dos),
			"Folyamatos adagolást bekapcs.#" xstr(set_nt),
			"Adagolási idő felügyelete,Min#" xstr(ph_dos_watch),
	"Redox#313",
		"Ideális érték redox#314",
			"Mér térték,mV#" xstr(rx_ix),
			"Ideális érték,mV#" xstr(rx_soll),
			"Figyelmeztető érték alacs.,mV#" xstr(rx_wr_un),
			"Alsó Riadó érték ,mV#" xstr(rx_alr_un),
			"Riasztási késleltetés,Min#" xstr(alr_dly_rx),
		"Szabályozás Redox#315",
			"P-tartomány,mV#" xstr(rx_p),
			"Hiszterézis ,mV#" xstr(rx_hys),
		"Adagolási beállítások#316",
			"Kézi folyamatos adagolás,Min#" xstr(rx_man_dos),
			"Folyamatos adagolást bekapcs.#" xstr(set_nt),
			"Adagolási idő felügyelete,Min#" xstr(rx_dos_watch),
	"Mérővíz mennyiség figyelés#317",
		"Cikkszám#" xstr(mw_art_t),
		"átfolyás,l/h#" xstr(fl_aktl_mw_ix),
		"átfolyási mennyiség,P/l#" xstr(fl_rate_mw),
		"minimális átfolyás,l/h#" xstr(min_fl_mw),
		"Kompenzáció,l/h#" xstr(flow_komp),
	"Dátum és idő#318",
		"órák#" xstr(std_1),
		"Perc#" xstr(min_1),
		"Nap#" xstr(day),
		"Hónap#" xstr(mon),
		"év#" xstr(year),
	"AER#319",
		"órák#" xstr(asr_std),
		"Perc#" xstr(asr_min),
		"AER napi száma#" xstr(asr_day),
		"AER kézi indítása#" xstr(set_nt),
	"Hőmérséklet#320",
		"Kompenzáció#" xstr(t_comp_t),
		"Kézi kompenzáció,°C#" xstr(t_man_comp),
		"Korrekció,°C#" xstr(t_korr),
"Kívánt érték elektrolízis#321",
	"Elektrolizís#322",
		"Sólé adagolás,%#" xstr(sole_dos),
		"Sólé utánpótlás felügyel.,Min#" xstr(sole_nspw),
		"Hőmérsékletet behatárolni,°C#" xstr(temp_lim_t),
		"Max. termék hőmérséklet#" xstr(maxt),
		"CL2-koncentráció,g/l#" xstr(cl_konz),
		"átfolyás,l/h#" xstr(flow_ely),
		"Korrekció,°C#" xstr(t0_korr),
		"Feszültség figyelése#" xstr(v_monitus_t),
	"Terméktartály#323",
		"Szintjének monitorozása#" xstr(lev_art_t),
		"Szint túltöltve,cm#" xstr(prodlev_ovfl),
		"Szint max.,cm#" xstr(prodlev_max),
		"Szint min.,cm#" xstr(prodlev_min),
	"Ventilátor#324",
		"Előrefutási idő,s#" xstr(luft_vor),
		"Utánfutási idő,min#" xstr(luft_nach),
"Relék#325",
	"Relais 3 [#326",
		"Hozzárendelés#" xstr(r3_strg_t),
		"Szabályozási forma#" xstr(r3_art_t),
		"Inpulzus_frekvencia,P/h#" xstr(r3_frq),
		"Periódusidő,Sek#" xstr(r3_pp),
		"Minimum impulzus,Sek#" xstr(r3_min),
	"Relais 4 ]#327",
		"Hozzárendelés#" xstr(r4_strg_t),
		"Szabályozási forma#" xstr(r4_art_t),
		"Inpulzus_frekvencia,P/h#" xstr(r4_frq),
		"Periódusidő,Sek#" xstr(r4_pp),
		"Minimum impulzus,Sek#" xstr(r4_min),
"Nyelv#" xstr(sprache_t),
"Gyári beállítás#" xstr(set_nt),
"Készülékadatok#328",
	"Gyátási szám#" xstr(dev_nr_ix),
	"Software készítés ideje#" xstr(softver_in),
	"Gyártás ideje#" xstr(mdate_in),
	"Gyártó#329",
		"dinotec GmbH",
		"Phillipp-Reis Str. 28",
		"D-61130 Nidderau",
		"Tel: 0049 (0)6187 41379-0",
		"Hotline: 0049 (0)6187 41379-72",
		"www.dinotec.de",
		"service@dinotec.de",
"Ingyenes",
"Ventilátor",
"Berendezés üzemel",
"Riasztás",
"pH csökkentés",
"pH-emelés",
"Redox",
"CL2",
"CL2,pH",
"CL2,pH,Redox",
"pH",
"pH,Redox",
"Méréstechnika nélkül",
"30",
"60",
"90",
"150",
"200",
"300",
"elfogad/tárol",
"visszaállít",
"Lekapcsolva",
"Normálüzem",
"Sóléoldó tartályt töltse fel",
"Cellát tölteni",
"Berendezés töltése",
"A készülék használatra készen áll",
"Sólé tartály feltöltve",
"Cella feltöltve",
"Berendezés feltöltve",
"Berendezés termel",
"Vízlágyítót regenerálni",
"Rendszer riasztás",
"Figyelmezt.DES ellenőrizni",
"Riasztás szintjelzés a terméktan.",
"Riasztás terméktank túltöltve",
"Riasztási cella feszültsége túl magas",
"Riasztás áramfelvétel túl magas",
"Riasztás áramfelvétel túl alacsony",
"Riasztás túl magas átfolyás",
"Riasztás túl alacson átfolyás",
"Riasztás sóléoldótrtály szintje",
"Be-Ki",
"Inpulzus frekvencia",
"Impulzus szünet",
"Igen",
"Nem",
"kézi",
"automatikus",
"Figyelmezt. CL2 érték túl magas",
"Figyelmezt. CL2 érték túl alacsony",
"Figyelmezt.POT szondát ellenőrizni",
"Riasztás CL2 felsőérték",
"Riasztás CL2 alsóérték",
"Riasztás pH felsőérték ",
"Riasztás pH alsóérték ",
"Riasztás Redox",
"Figyelem Redox érték ",
"Figyelem pH felsőérték ",
"Figyelem pH alsóérték ",
"Mérővízhiány",
"Szintmérés",
"úszókapcsoló",
"átfolyás mérése",
"Külső adagolási tiltás",
"Nincs kapcsolat a vezérlőegységhez",
"CL2 meredekségi hiba",
"Meredékségi hiba pH",
"Nullponthiba",
"pH kanna üres",
"Adagolásiidő fertőtlenítés túllépve",
"Adagolásiidő pH emelés túllépve",
"Adagolásiidő pH csökk. túllépve",
"bekapcsolási késleltetés aktiv",
"Fertotlenít.folyamatos adagolása",
"pH szabályzó folyamatos adagolása",
"Fertőtlenít.szabályoz.határ túllépv",
"Fertőtlenít.szabályoz.határ túllépv",
"pH szabályozási határ túllépve",
"pH szabályozási határ alacsony",
"Riasztás termék hőmérsék.túl magas",
"Figyelmezt.termék hőmérséklet magas",
"Figyelmezt.termékhőmérs.alacsony",
"Riasztás cella feszûltség alacsony",
"Legyen az ön vize a legjobb",
"Terméktartály üres",
"Adagolás lekapcsolva", 
"Eletrolizis lekapcsolva",
"Ventilátor előrefutás",					//   =vent_vor_txt
"Ventilátor utánfutás",					//   =vent_nach_txt
"0 - 1 mg/l",
"0 - 10 mg/l",
"Német",
"Angol",
"Francia",
"Spanyol",
"Lengyel",
"Ukrán",
"Orosz",
"Olasz",
"Cseh",
"Slovén",
"Horváth",
"Magyar",
"Román",
"Holland",
"Szerb",
};
