char* text_es[] = {
"MENú PRINCIPAL",
"Código#" xstr(code0_in),
"Electról.funcion.#" xstr(btr_art_t),
"Configuración del aparato#300",
	"Tipo de equipo,g/h#" xstr(anl_typ_t),
	"Dirección BUS#" xstr(sh_adr),
	"Contraste#" xstr(contr),
	"Técnicas de medición#" xstr(msr_t),
	"Rango de medición Cl2#" xstr(mgl_t),
	"Cl2 pH-kompensiert#" xstr(set_nt),
"Calibración#301",
	"Calibración sonda de cloro#302",
		"Valor de medición,mg/l#" xstr(cl_val_ix),
		"Transconductancia,mV#" xstr(cl_sth_in),
		"Tensión de entrada,mV#" xstr(cl_mv_ix),
		"Almacenar Uein#" xstr(set_nt),
		"Uein guardado,mV#" xstr(uin_saved_ix),
		"Punto cero,mV#" xstr(cl_mv0_in),
		"Ajuste de punto cero#" xstr(set_nt),
		"Valor DPD,mg/l#" xstr(cl_dpd_in),
		"Reinicio calibración#" xstr(set_nt),
		"Fin ciclo AER, Min#" xstr(aer_min_ix),
		"No puede efectuarse la calibración",
		"Valor de medición < 0,1 mg/l",
		"Valor de medición < 0,05 mg/l",
	"Calibración de pH#303",
		"Valor de medición,pH#" xstr(ph_ix),
		"Transconductancia,mV/pH#" xstr(ph_sth_in),
		"Punto cero,mV#" xstr(ph_null_in),
		"Tensión de entrada,mV#" xstr(ph_mv_ix),
		"Calibración pH 4/7#" xstr(ph_dpd2_in),
		"Reinicio calibración#" xstr(set_nt),
"Valores nominales de medición#304",
	"Retardo de conexión ,Min#" xstr(on_dly),
	"Valores nominales CL2#305",
		"Valores nominales CL2#306",
			"Valor superior de alarma,mg/l#" xstr(cl_alr_ob),
			"Valor superior de aviso,mg/l#" xstr(cl_wr_ob),
			"Valor nominal:,mg/l#" xstr(cl_soll),
			"Valor inferior de aviso,mg/l#" xstr(cl_wr_un),
			"Valor inferior de alarma,mg/l#" xstr(cl_alr_un),
			"Retardo conexión de alarma,Min#" xstr(cl_alr_dly),
		"Regulación CL2#307",
			"ámbito P,mg/l#" xstr(cl_p),
			"Tiempo de acción integral,Sek#" xstr(cl_i),
			"Histéresis,mg/l#" xstr(cl_hys),
		"Ajustes de dosificación#308",
			"Dosif.manual continua,Min#" xstr(cl_man_dos),
			"Conectar dosificación continua#" xstr(set_nt),
			"Control del tiempo de dosificación ,Min#" xstr(cl_dos_watch),
	"Valores de pH#309",
		"Valores nominales de pH#310",
			"Valor superior de alarma,pH#" xstr(ph_alr_ob),
			"Valor superior de aviso,pH#" xstr(ph_wr_ob),
			"Valor nominal:,pH#" xstr(ph_soll),
			"Valor inferior de aviso,pH#" xstr(ph_wr_un),
			"Valor inferior de alarma,pH#" xstr(ph_alr_un),
			"Retardo conexión de alarma,Min#" xstr(alr_dly_ph),
		"Regulación pH#311",
			"ámbito P,pH#" xstr(ph_p),
			"Histéresis,pH#" xstr(ph_hys),
			"Tiempo de acción integral,Sek#" xstr(ph_zi),
			"Banda muerta,pH#" xstr(totband_ph),
		"Ajustes de dosificación#312",
			"Dosif.manual continua,Min#" xstr(ph_man_dos),
			"Conectar dosificación continua#" xstr(set_nt),
			"Control del tiempo de dosificación ,Min#" xstr(ph_dos_watch),
	"Redox#313",
		"Valores nominales Redox#314",
			"Valor de medición,mV#" xstr(rx_ix),
			"Valor nominal:,mV#" xstr(rx_soll),
			"Valor inferior de aviso,mV#" xstr(rx_wr_un),
			"Valor inferior de alarma,mV#" xstr(rx_alr_un),
			"Retardo conexión de alarma,Min#" xstr(alr_dly_rx),
		"Regulación Redox#315",
			"ámbito P,mV#" xstr(rx_p),
			"Histéresis,mV#" xstr(rx_hys),
		"Ajustes de dosificación#316",
			"Dosif.manual continua,Min#" xstr(rx_man_dos),
			"Conectar dosificación continua#" xstr(set_nt),
			"Control del tiempo de dosificación ,Min#" xstr(rx_dos_watch),
	"Control del agua de medición#317",
		"Tipo#" xstr(mw_art_t),
		"Circulación,l/h#" xstr(fl_aktl_mw_ix),
		"Volumen de circulación:,P/l#" xstr(fl_rate_mw),
		"Circulación mínima,l/h#" xstr(min_fl_mw),
		"Compensación,l/h#" xstr(flow_komp),
	"Fecha y hora#318",
		"Horas#" xstr(std_1),
		"Minutos#" xstr(min_1),
		"Día#" xstr(day),
		"Mes#" xstr(mon),
		"Año#" xstr(year),
	"AER#319",
		"Horas#" xstr(asr_std),
		"Minutos#" xstr(asr_min),
		"Número de ciclos AER al día#" xstr(asr_day),
		"Activ.manual del proceso AER#" xstr(set_nt),
	"Temperatura#320",
		"Compensación#" xstr(t_comp_t),
		"Compensación manual,°C#" xstr(t_man_comp),
		"Corrección,°C#" xstr(t_korr),
"Valores nominales electrolisis#321",
	"Electrolisis#322",
		"Dosificación de salmuera,%#" xstr(sole_dos),
		"Control reposición salmuera,Min#" xstr(sole_nspw),
		"Limitar temperatura,°C#" xstr(temp_lim_t),
		"Máx.termperatura prod.°C#" xstr(maxt),
		"Concentración CL2,g/l#" xstr(cl_konz),
		"Circulación,l/h#" xstr(flow_ely),
		"Corrección,°C#" xstr(t1_korr),
		"Supervisión de la tensión#" xstr(v_monitus_t),
	"Tanque de producto#323",
		"monitor.de niveles#" xstr(lev_art_t),
		"Desbordamiento de nivel,cm#" xstr(prodlev_ovfl),
		"Nivel máx.,cm#" xstr(prodlev_max),
		"Nivel mín.,cm#" xstr(prodlev_min),
	"Ventilador#324",
		"Tiempo de arranque,seg#" xstr(luft_vor),
		"Tiempo funcion.por inercia,min#" xstr(luft_nach),
"Relé#325",
	"Relé 3 [#326",
		"Asignación#" xstr(r3_strg_t),
		"Tipo de regulador#" xstr(r3_art_t),
		"Frecuencia de pulsos,P/h#" xstr(r3_frq),
		"Duración periodos,Sek#" xstr(r3_pp),
		"Impulso mínimo,Sek#" xstr(r3_min),
	"Relé 4 ]#327",
		"Asignación#" xstr(r4_strg_t),
		"Tipo de regulador#" xstr(r4_art_t),
		"Frecuencia de pulsos,P/h#" xstr(r4_frq),
		"Duración periodos,Sek#" xstr(r4_pp),
		"Impulso mínimo,Sek#" xstr(r4_min),
"Idioma#" xstr(sprache_t),
"Ajuste de fábrica#" xstr(set_nt),
"Datos del aparato#328",
	"Número de aparato#" xstr(dev_nr_ix),
	"Versión Software#" xstr(softver_in),
	"Fecha de fabricación#" xstr(mdate_in),
	"Fabricante#329",
		"dinotec GmbH",
		"Phillipp-Reis Str. 28",
		"D-61130 Nidderau",
		"Tel: 0049 (0)6187 41379-0",
		"Hotline: 0049 (0)6187 41379-72",
		"www.dinotec.de",
		"service@dinotec.de",
"Frei",
"Ventilador",
"Equipo en funcion.",
"Alarma",
"Reducir pH",
"Elevar pH",
"Redox",
"CL2",
"CL2,pH",
"CL2,pH,Redox",
"pH",
"pH,Redox",
"Sin equipo de medición",
"30",
"60",
"90",
"150",
"200",
"300",
"fijar",
"reiniciar",
"Desconectado",
"Funcion.normal",
"Llenar tanque salm.",
"Rellenar célula",
"Llenar equipo",
"Equipo preparado",
"Tanque de salmuera lleno",
"Célula llena",
"Equipo lleno",
"Equipo produciendo",
"Regeneración del desendurecedor",
"Alarma funcionamiento de sistema",
"Aviso controlar disposit.DES",
"Alar.nivel de medic.tanque de prod.",
"Alar.desbordam.tanque de producto",
"Alarma tensión en célula demas.alta",
"Alarma corriente demasiado alta",
"Alarma corriente demasiado baja",
"Alarma circulación demasiado alta",
"Alarma circulación demasiado baja",
"Alarma nivel tanque de salmuera",
"Activo/Inactivo",
"Frecuencia de pulsos",
"Pulso / Pausa",
"Si",
"No",
"manual",
"Automática",
"Aviso valor superior de CL2",
"Aviso valor inferior de CL2",
"Aviso verificac.sonda potenc.",
"Alarma superior CL2",
"Alarma inferior CL2",
"Alarma valor superior pH",
"Alarma valor inferior pH",
"Alarma Redox",
"Aviso Redox",
"Aviso valor superior de pH",
"Aviso valor inferior de pH",
"Falta de agua de medición",
"Medición de nivel",
"Conector de boya",
"Medición de caudal",
"Parada de dosificación externa",
"Sin conexión a elemento de control",
"Error de transconductancia CL2",
"Error de transconductancia de pH ",
"Error de punto cero",
"Recipiente de pH vacío",
"Tiempo dosif.desinfectante exced.",
"Tiempo dosif.elevador de pH exced.",
"Tiempo dosif.reductor de pH exced.",
"Retardo conexión activado",
"Dosificación continua desinfectante",
"Dosificación continua de pH",
"Lím.de regul.de desinfec.sobrepas.",
"Lím.de regul.de desinfec.no alcanz.",
"Lím.de regul.de pH sobrepasado",
"Lím.de regul.de pH no alcanzado",
"Alarma temp.del prod.demas.elevada",
"Alarm.temperat.del producto demas.alta",
"Alarm.temperat.del producto demas.baja",
"Alarma tensión en célula demas.baja",
"Disfrute sencil.de la mejor agua!",
"Tanque de producto vacío",
"Dosificación desconectado", 
"Electrólisis desconectado",
"Arranque ventilador",					//   =vent_vor_txt
"Funcion. por inercia ventilador",					//   =vent_nach_txt
"0 - 1 mg/l",
"0 - 10 mg/l",
"Alemán",
"Inglés",
"Francés",
"Español",
"Polaco",
"Ucraniano",
"Ruso",
"Italiano",
"Checo",
"Eslovaco",
"Croata",
"Húngaro",
"Rumano",
"Holandés",
"Serbio",
};
