char* text_hr[] = {
"GLAVNI IZBORNIK",
"Kôd#" xstr(code0_in),
"Rad uređ.za elektrol.#" xstr(btr_art_t),
"Konfiguracija uređaja#300",
	"Vrsta sustava,g/h#" xstr(anl_typ_t),
	"Adresa sabirnice#" xstr(sh_adr),
	"Kontrast#" xstr(contr),
	"Mjerna tehnika#" xstr(msr_t),
	"Raspon mjerenja Cl2#" xstr(mgl_t),
	"Cl2 pH-kompenzirana#" xstr(set_nt),
"Kalibriranje#301",
	"Kalibriranje sonde za klor#302",
		"Mjerna vrijednost,mg/l#" xstr(cl_val_ix),
		"Strmina,mV#" xstr(cl_sth_in),
		"Ulazni napon,mV#" xstr(cl_mv_ix),
		"Spremanje ulaznog napona#" xstr(set_nt),
		"Ulazni napon spremljen,mV#" xstr(uin_saved_ix),
		"Nulta točka,mV#" xstr(cl_mv0_in),
		"Postavljanje nulte točke#" xstr(set_nt),
		"Vrijednost DPD,mg/l#" xstr(cl_dpd_in),
		"Poništavanje kalibriranja#" xstr(set_nt),
		"Kraj AER u, Min#" xstr(aer_min_ix),
		"Kalibriranje nije moguæe",
		"Mjerna vrijednost < 0,1 mg/l",
		"Mjerna vrijednost < 0,05 mg/l",
	"Kalibriranje pH#303",
		"Mjerna vrijednost,pH#" xstr(ph_ix),
		"Strmina,mV/pH#" xstr(ph_sth_in),
		"Nulta točka,mV#" xstr(ph_null_in),
		"Ulazni napon,mV#" xstr(ph_mv_ix),
		"Kalibriranje pH4/7#" xstr(ph_dpd2_in),
		"Poništavanje kalibriranja#" xstr(set_nt),
"Zadane vrijednosti mjerne tehnike#304",
	"Odgoda uključivanja,Min#" xstr(on_dly),
	"Zadane vrijednosti Cl2#305",
		"Zadane vrijednosti CL2#306",
			"Alarmna vrijednost gornja,mg/l#" xstr(cl_alr_ob),
			"Vrijednost upozor.gornja,mg/l#" xstr(cl_wr_ob),
			"Zadana vrijednost,mg/l#" xstr(cl_soll),
			"Vrijednost upozor.donja,mg/l#" xstr(cl_wr_un),
			"Alarmna vrijednost donja,mg/l#" xstr(cl_alr_un),
			"Odgoda alarma,Min#" xstr(cl_alr_dly),
		"Reguliranje CL2#307",
			"P-područje,mg/l#" xstr(cl_p),
			"Nastavno vrijeme ,Sek#" xstr(cl_i),
			"Histereza,mg/l#" xstr(cl_hys),
		"Postavke doziranja#308",
			"ručno stalno doziranje,Min#" xstr(cl_man_dos),
			"Uključiti stalno doziranje#" xstr(set_nt),
			"Nadzor dozirnog vremena,Min#" xstr(cl_dos_watch),
	"pH vrijednosti#309",
		"Zadane vrijednosti pH#310",
			"Alarmna vrijednost gornja,pH#" xstr(ph_alr_ob),
			"Vrijednost upozoren.gornja,pH#" xstr(ph_wr_ob),
			"Zadana vrijednost,pH#" xstr(ph_soll),
			"Vrijednost upozorenja donja,pH#" xstr(ph_wr_un),
			"Alarmna vrijednost donja,pH#" xstr(ph_alr_un),
			"Odgoda alarma,Min#" xstr(alr_dly_ph),
		"Reguliranje pH#311",
			"P-područje,pH#" xstr(ph_p),
			"Histereza,pH#" xstr(ph_hys),
			"Nastavno vrijeme ,Sek#" xstr(ph_zi),
			"Mrtvo područje,pH#" xstr(totband_ph),
		"Postavke doziranja#312",
			"ručno stalno doziranje,Min#" xstr(ph_man_dos),
			"Uključiti stalno doziranje#" xstr(set_nt),
			"Nadzor dozirnog vremena ,Min#" xstr(ph_dos_watch),
	"Redox#313",
		"Zadane vrijednosti Redox#314",
			"Mjerna vrijednost,mV#" xstr(rx_ix),
			"Zadana vrijednost,mV#" xstr(rx_soll),
			"Vrijednost upozorenja donja,mV#" xstr(rx_wr_un),
			"Alarmna vrijednost donja,mV#" xstr(rx_alr_un),
			"Odgoda alarma,Min#" xstr(alr_dly_rx),
		"Reguliranje Redox#315",
			"P-područje,mV#" xstr(rx_p),
			"Histereza,mV#" xstr(rx_hys),
		"Postavke doziranja#316",
			"ručno stalno doziranje,Min#" xstr(rx_man_dos),
			"Uključiti stalno doziranje#" xstr(set_nt),
			"Nadzor dozirnog vremena,Min#" xstr(rx_dos_watch),
	"Nadzor vode za mjerenje#317",
		"Vrsta#" xstr(mw_art_t),
		"Protok,l/h#" xstr(fl_aktl_mw_ix),
		"Stopa protoka,P/l#" xstr(fl_rate_mw),
		"minimalni protok,l/h#" xstr(min_fl_mw),
		"Kompenzacija,l/h#" xstr(flow_komp),
	"Datum i vrijeme #318",
		"Sati#" xstr(std_1),
		"Minute#" xstr(min_1),
		"Dan#" xstr(day),
		"Mjesec#" xstr(mon),
		"Godina#" xstr(year),
	"AER#319",
		"Sati#" xstr(asr_std),
		"Minute#" xstr(asr_min),
		"Broj AER dnevno#" xstr(asr_day),
		"AER ukjučiti ručno#" xstr(set_nt),
	"Temperatura#320",
		"Kompenzacija#" xstr(t_comp_t),
		"Ručna kompenzacija,°C#" xstr(t_man_comp),
		"Ispravak,°C#" xstr(t_korr),
"Zadane vrijednosti elektrolize#321",
	"Elektroliza#322",
		"Doziranje slane vode,%#" xstr(sole_dos),
		"Nadzor naknad.punj.sl.vode,Min#" xstr(sole_nspw),
		"Ograničiti temperaturu,°C#" xstr(temp_lim_t),
		"Maks.temp.proizvoda °C#" xstr(maxt),
		"Koncentracija CL2,g/l#" xstr(cl_konz),
		"Durchfluss,l/h#" xstr(flow_ely),
		"Ispravak,°C#" xstr(t0_korr),
		"Nadzor napona#" xstr(v_monitus_t),
	"Spremnik proizvoda#323",
		"Praćenje razine#" xstr(lev_art_t),
		"Razina preljev,cm#" xstr(prodlev_ovfl),
		"Razina maks.,cm#" xstr(prodlev_max),
		"Razina min.,cm#" xstr(prodlev_min),
	"Ventilator#324",
		"Vrijeme pripremnog rada,s#" xstr(luft_vor),
		"Vrijeme zaustavljanja,min#" xstr(luft_nach),
"Relej#325",
	"Relej 3 [#326",
		"Dodjeljivanje#" xstr(r3_strg_t),
		"Način regulacije#" xstr(r3_art_t),
		"Pulsna frekvencija,P/h#" xstr(r3_frq),
		"Trajanje periode,Sek#" xstr(r3_pp),
		"Minimalni impuls,Sek#" xstr(r3_min),
	"Relej 4 ]#327",
		"Dodjeljivanje#" xstr(r4_strg_t),
		"Način regulacije#" xstr(r4_art_t),
		"Pulsna frekvencija,P/h#" xstr(r4_frq),
		"Trajanje periode,Sek#" xstr(r4_pp),
		"Minimalni impuls,Sek#" xstr(r4_min),
"Jezik#" xstr(sprache_t),
"Tvornička postavka#" xstr(set_nt),
"Podatci o uređaju#328",
	"Broj uređaja#" xstr(dev_nr_ix),
	"Verzija softvera#" xstr(softver_in),
	"Datum proizvodnje#" xstr(mdate_in),
	"Proizvođač#329",
		"dinotec GmbH",
		"Phillipp-Reis Str. 28",
		"D-61130 Nidderau",
		"Tel: 0049 (0)6187 41379-0",
		"Hotline: 0049 (0)6187 41379-72",
		"www.dinotec.de",
		"service@dinotec.de",
"Nevezan",
"Ventilator",
"Sustav u radu",
"Alarm",
"pH-snižavanje",
"pH-poveæanje",
"Redox",
"CL2",
"CL2,pH",
"CL2,pH,Redox",
"pH",
"pH,Redox",
"bez mjerne tehnike",
"30",
"60",
"90",
"150",
"200",
"300",
"postaviti",
"vratiti",
"Isključeno",
"Norm.nači.rada",
"Punj.sprem.sl.vo.",
"Punjenje æelije",
"Punjenje sustava",
"Sustav spreman",
"Spremnik slane vode napunjen",
"æelija napunjena",
"Sustav napunjen",
"Sustav proizvodi",
"Omekšivač regeneriran",
"Alarm rad sustava",
"Upozorenje - provjeriti sustav DES",
"Alarm mjer.raz.spremnika proizvoda",
"Alarm preljev spremnika proizvoda",
"Alarm previsok napon æelije",
"Alarm previsoka struja",
"Alarm preniska struja",
"Alarm prevelik protok",
"Alarm premali protok",
"Alarm razina spremnika slane vode",
"UKLJ.-ISKLJ.",
"Pulsna frekvencija",
"Puls-Pauza",
"Da",
"Ne",
"ručno",
"automatski",
"Upozorenje gore CL2",
"Upozorenje dolje CL2",
"Upozorenje POT sondu provjeriti",
"Alarm gornji CL2",
"Alarm donji CL2",
"Alarm pH gornji",
"Alarm pH donji",
"Alarm Redox",
"Upozorenje Redox",
"Upozorenje pH gore",
"Upozorenje pH dole",
"Manjak vode za mjerenje",
"Mjerenje razine",
"Plivajuæi prekidač",
"Mjerenje protoka",
"Vanjsko zaustavljanje doziranja",
"Ne postoji veza s upravlj. dijelom",
"Pogreška strmine Cl2",
"Pogreška strmine pH",
"Pogreška nulte točke",
"pH spremik je prazan",
"Vrijeme doziran.dezinfekc.premašeno",
"Vrijeme dozir.pH dizanja premašeno",
"Vrijeme dozir.pH spuštanja premaš.",
"Odgoda uključivanja aktivna",
"Stalno doziranje dezinfekcije radi",
"Stalno doziranje pH radi",
"Regulac.granica dezinfek.premašena ",
"Regulacijska granica dezinfek.ispod",
"Regulacijska granica pH premašena ",
"Regulacijska granica pH ispod ",
"Alarm previsoka temp. proizvoda",
"Upozorenje visoka temp.proizvoda",
"Upozorenje niska temp.proizvoda",
"Alarm prenizak napon æelije",
"Jednostavno osjetite nabolju vodu!",
"Spremnik proizvoda je prazan",
"Doziranja isključeno", 
"Elektrolize isključeno",
"Pripremni rad ventilatora",					//   =vent_vor_txt
"Zaustavljanje ventilatora",					//   =vent_nach_txt
"0 - 1 mg/l",
"0 - 10 mg/l",
"Njemački ",
"Engleski",
"Francuski",
"španjolski",
"Poljski",
"Ukrajinski",
"Ruski ",
"Talijanski",
"češki",
"Slovenski ",
"hrvatski",
"Mađarski",
"Rumunjski",
"Nizozemski ",
"Srpski ",
};
