const char* text_en[] = {
"MAIN MENU",
"Code#" xstr(code0_in),
"Electrolysis operation#" xstr(btr_art_t),
"Device configuration#300",
	"Plant type,g/h#" xstr(anl_typ_t),
	"Bus address#" xstr(sh_adr),
	"Contrast#" xstr(contr),
	"Measurement technology#" xstr(msr_t),
	"Measuring range Cl2#" xstr(mgl_t),
	"Cl2 pH-compensated#" xstr(set_nt),
"Calibration#301",
	"Calibration chlorine probe#302",
		"Measured value,mg/l#" xstr(cl_val_ix),
		"Slope,mV#" xstr(cl_sth_in),
		"Input voltage,mV#" xstr(cl_mv_ix),
		"Save input voltage#" xstr(set_nt),
		"Input voltage saved,mV#" xstr(uin_saved_ix),
		"Zero point,mV#" xstr(cl_mv0_in),
		"Set zero point#" xstr(set_nt),
		"DPD value,mg/l#" xstr(cl_dpd_in),
		"Calibration reset#" xstr(set_nt),
		"Finish AER in, min#" xstr(aer_min_ix),
		"Calibration not possible",
		"Measured value < 0,1 mg/l",
		"Measured value < 0,05 mg/l",
	"Calibration pH#303",
		"Measured value,pH#" xstr(ph_ix),
		"Slope,mV/pH#" xstr(ph_sth_in),
		"Zero point,mV#" xstr(ph_null_in),
		"Input voltage,mV#" xstr(ph_mv_ix),
		"Calibration pH4/7#" xstr(ph_dpd2_in),
		"Calibration reset#" xstr(set_nt),
"Setpoints meas. equipm.#304",
	"Switch-on delay,min#" xstr(on_dly),
	"Setpoints Cl2#305",
		"Setpoints Cl2#306",
			"Alarm value upper,mg/l#" xstr(cl_alr_ob),
			"Alert value upper,mg/l#" xstr(cl_wr_ob),
			"Setpoint,mg/l#" xstr(cl_soll),
			"Alert value lower,mg/l#" xstr(cl_wr_un),
			"Alarm value lower,mg/l#" xstr(cl_alr_un),
			"Alarm delay,min#" xstr(cl_alr_dly),
		"Control CL2#307",
			"P-band,mg/l#" xstr(cl_p),
			"Integral action time,sec#" xstr(cl_i),
			"Hysteresis,mg/l#" xstr(cl_hys),
		"Dosing settings#308",
			"Manual continuous dosing,min#" xstr(cl_man_dos),
			"Activate continuous dosing#" xstr(set_nt),
			"Dosing time monitoring,min#" xstr(cl_dos_watch),
	"pH value#309",
		"Setpoints pH#310",
			"Alarm value upper,pH#" xstr(ph_alr_ob),
			"Alert value upper,pH#" xstr(ph_wr_ob),
			"Setpoint,pH#" xstr(ph_soll),
			"Alert value lower,pH#" xstr(ph_wr_un),
			"Alarm value lower,pH#" xstr(ph_alr_un),
			"Alarm delay,min#" xstr(alr_dly_ph),
		"Control pH#311",
			"P-band,pH#" xstr(ph_p),
			"Hysteresis,pH#" xstr(ph_hys),
			"Integral action time,sec#" xstr(ph_zi),
			"Deadband,pH#" xstr(totband_ph),
		"Dosing settings#312",
			"Manual continuous dosing,min#" xstr(ph_man_dos),
			"Activate continuous dosing#" xstr(set_nt),
			"Dosing time monitoring,min#" xstr(ph_dos_watch),
	"Redox#313",
		"Setpoints redox#314",
			"Measured value,mV#" xstr(rx_ix),
			"Setpoint,mV#" xstr(rx_soll),
			"Alert value lower,mV#" xstr(rx_wr_un),
			"Alarm value lower,mV#" xstr(rx_alr_un),
			"Alarm delay,min#" xstr(alr_dly_rx),
		"Control redox#315",
			"P-band,mV#" xstr(rx_p),
			"Hysteresis,mV#" xstr(rx_hys),
		"Dosing settings#316",
			"Manual continuous dosing,min#" xstr(rx_man_dos),
			"Activate continuous dosing#" xstr(set_nt),
			"Dosing time monitoring,min#" xstr(rx_dos_watch),
	"Sample water monitoring#317",
		"Type#" xstr(mw_art_t),
		"Flow,l/h#" xstr(fl_aktl_mw_ix),
		"Flow rate,P/l#" xstr(fl_rate_mw),
		"Minimum flow,l/h#" xstr(min_fl_mw),
		"Compensation,l/h#" xstr(flow_komp),
	"Date and time#318",
		"Hours#" xstr(std_1),
		"Minutes#" xstr(min_1),
		"Day#" xstr(day),
		"Month#" xstr(mon),
		"Year#" xstr(year),
	"AER#319",
		"Hours#" xstr(asr_std),
		"Minutes#" xstr(asr_min),
		"Number of AER per day#" xstr(asr_day),
		"AER manual start#" xstr(set_nt),
	"Temperature#320",
		"Compensation#" xstr(t_comp_t),
		"Manual compensation,C#" xstr(t_man_comp),
		"Correction,C#" xstr(t_korr),
"Setpoints electrolysis#321",
	"Electrolysis#322",
		"Brine dosing,%#" xstr(sole_dos),
		"Brine refill monitoring,min#" xstr(sole_nspw),
		"Limit temperature,C#" xstr(temp_lim_t),
		"Max. product temp.C#" xstr(maxt),
		"CL2 concentration,g/l#" xstr(cl_konz),
		"Flow,l/h#" xstr(flow_ely),
		"Correction,C#" xstr(t0_korr),
		"Voltage monitoring#" xstr(v_monitus_t),
	"Product tank#323",
		"Level monitoring#" xstr(lev_art_t),
		"Level overflow,cm#" xstr(prodlev_ovfl),
		"Level max.,cm#" xstr(prodlev_max),
		"Level min.,cm#" xstr(prodlev_min),
		"Emergency running#" xstr(not_btr_t),
		"Emergency run time,min#" xstr(not_zeit),
	"Fan#324",
		"Lead time,sec#" xstr(luft_vor),
		"Soft stop duration,min#" xstr(luft_nach),
"Relays#325",
	"Relay 2 [#326",
		"Allocation#" xstr(r3_strg_t),
		"Controller type#" xstr(r3_art_t),
		"Pulse frequency,P/h#" xstr(r3_frq),
		"Pulse cycle time,sec#" xstr(r3_pp),
		"Minimum pulse,sec#" xstr(r3_min),
	"Relay 3 ]#327",
		"Allocation#" xstr(r4_strg_t),
		"Controller type#" xstr(r4_art_t),
		"Pulse frequency,P/h#" xstr(r4_frq),
		"Pulse cycle time,sec#" xstr(r4_pp),
		"Minimum pulse,sec#" xstr(r4_min),
"Language#" xstr(sprache_t),
"Factory setting#" xstr(set_nt),
"Device data#328",
	"Device number#" xstr(dev_nr_ix),
	"Software version#" xstr(softver_ix),
	"Software version control#" xstr(soft_strg_ix),
	"Date of manufacture#" xstr(mdate_in),
	"manufacturer#329",
		"dinotec GmbH",
		"Phillipp-Reis Str. 28",
		"D-61130 Nidderau",
		"Tel: 0049 (0)6187 41379-0",
		"Hotline: 0049 (0)6187 41379-72",
		"www.dinotec.de",
		"service@dinotec.de",
"Free",
"Fan",
"System in operation",
"Alarm",
"pH reduce",
"pH raise",
"Redox",
"CL2",
"CL2,pH",
"CL2,pH,Redox",
"pH",
"pH,Redox",
"Excl. measuring equipment",
"30",
"60",
"90",
"150",
"200",
"300",
"Set",
"Reset",
"Deactivated",
"Normal operation",
"Fill brine tank",
"Fill cell",
"Fill system",
"system ready",
"Brine tank filled",
"Cell filled",
"System filled",
"System is producing",
"Softener is regenerating",
"Alarm system operation",
"Check alert DES system",
"Alarm level measurem.product tank",
"Alarm product tank overflow",
"Alarm cell voltage too high",
"Alarm current too high",
"Alarm current too low",
"Alarm flow too high",
"Alarm flow too low",
"Alarm level brine tank",
"ON / OFF",
"Pulse frequency",
"Pulse interval",
"Yes",
"No",
"Manual",
"Automatic",
"Alert CL2 upper",
"Alert CL2 lower",
"Check alert POT probe",
"Alarm CL2 upper",
"Alarm CL2 lower",
"Alarm pH upper",
"Alarm pH lower",
"Alarm redox",
"Alert redox",
"Alert pH upper",
"Alert pH lower",
"Sample water deficiency",
"measurement",
"float switch",
"Flow measurement",
"External dosing stop",
"No connection to control part",
"Slope error Cl2",
"Error slope pH",
"Zero point error",
"pH container empty",
"Dosing time disinfection exceeded",
"Dosing time pH raise exceeded",
"Dosing time pH reduce exceeded",
"Switch-on delay enabled",
"Cont.dosing disinfection in progres",
"Continuous dosing pH running",
"Control limit disinfection exceeded",
"Control lim.disinf.fallen short of",
"Control limit pH exceeded",
"Control limit pH fallen short of",
"Alarm product temperature too high",
"Alert product temperature high",
"Alert product temperature low",
"Alarm cell voltage too low",
"Simply enjoy the best water",
"Product tank is empty",
"Dosing deactivated", 
"Electrolysis deactivated", 
"Ventilator lead time",					//   =vent_vor_txt
"Ventilator soft stop",					//   =vent_nach_txt
"Warning emergency operation",					
"0 - 1 mg/l",
"0 - 10 mg/l",
"Startup process, please wait",
"German",
"English",
"French",
"Spanish",
"Polish",
"Ukrainian",
"Russian",
"Italian",
"Czech",
"Slovenian",
"Croatian",
"Hungarian",
"Romanian",
"Dutch",
"Serbian",
"Communication#" xstr(komm_t),
"Modbus",
"dinoREMOTE",
"WLAN#330",
	"IP: #" xstr(ip_en),							// komma 124
	"SSID#" xstr(ssid_en),							// komma 125	
	"Signal strength,%#" xstr(sign_en),				// komma 126
	"Connected#" xstr(conn_en),						// komma 127
	"Server connection#" xstr(server_en),			// komma 127
	"WLAN reset#" xstr(wreset_en)					// komma 127
};
