const char* text_pl[] = {
"MENU glèwne",
"kod#" xstr(code0_in),
"Praca Elektroliza#" xstr(btr_art_t),
"Konfiguracja urzôdzenia#300",
	"Typ urzôdzenia,g/h#" xstr(anl_typ_t),
	"Adres BUS#" xstr(sh_adr),
	"Kontrast#" xstr(contr),
	"Technika pomiarowa#" xstr(msr_t),
	"Zakres pomiarowy Cl2#" xstr(mgl_t),
	"Cl2 pH z kompensacja#" xstr(set_nt),
"Kalibracja#301",
	"Kalibracja sondy chloru#302",
		"Wart. pomiar.,mg/l#" xstr(cl_val_ix),
		"Stromoõú,mV#" xstr(cl_sth_in),
		"Napiécie wejeciowe,mV#" xstr(cl_mv_ix),
		"Zapisz Uwe#" xstr(set_nt),
		"Uwe zapisany,mV#" xstr(uin_saved_ix),
		"Punkt zerowy,mV#" xstr(cl_mv0_in),
		"Ustawianie punktu zerowego#" xstr(set_nt),
		"Wartoõú DPD,mg/l#" xstr(cl_dpd_in),
		"Reset kalibracji#" xstr(set_nt),
		"Koniec ACE za, Min#" xstr(aer_min_ix),
		"Kalibracja niemoûliwa",
		"Wart. pomiar. < 0,1 mg/l",
		"Wart. pomiar. < 0,05 mg/l",
	"Kalibracja pH#303",
		"Wart. pomiar.,pH#" xstr(ph_ix),
		"Stromoõú,mV/pH#" xstr(ph_sth_in),
		"Punkt zerowy,mV#" xstr(ph_null_in),
		"Napiécie wejeciowe,mV#" xstr(ph_mv_ix),
		"Kalibracja pH 4/7#" xstr(ph_dpd2_in),
		"Reset kalibracji#" xstr(set_nt),
"Wartoeci zadane Technika pomiarowa#304",
	"Opèönianie wòôczenia,Min#" xstr(on_dly),
	"Wartoeci zadane CL2#305",
		"Wartoeci zadane CL2#306",
			"Gèrna wartoõú alarmowa,mg/l#" xstr(cl_alr_ob),
			"Gèrna wartoõú ostrzegawcza,mg/l#" xstr(cl_wr_ob),
			"Wartoõú zadana,mg/l#" xstr(cl_soll),
			"Dolna wartoõú ostrzegawcza,mg/l#" xstr(cl_wr_un),
			"Dolna wartoõú alarmowa,mg/l#" xstr(cl_alr_un),
			"Opèönienie alarmu,Min#" xstr(cl_alr_dly),
		"Regulacja CL2#307",
			"Zakres regulacji P,mg/l#" xstr(cl_p),
			"Czas caòkowania,Sek#" xstr(cl_i),
			"Histereza,mg/l#" xstr(cl_hys),
		"Ustawienia dozowania#308",
			"Dozowanie ciôgòe réczne,Min#" xstr(cl_man_dos),
			"Wòôcz dozowanie ciôgòe#" xstr(set_nt),
			"Kontrola czasu dozowania,Min#" xstr(cl_dos_watch),
	"Wartoeci pH#309",
		"Wartoõúi zadane pH#310",
			"Gèrna wartoõú alarmowa,pH#" xstr(ph_alr_ob),
			"Gèrna wartoõú ostrzegawcza,pH#" xstr(ph_wr_ob),
			"Wartoõú zadana,pH#" xstr(ph_soll),
			"Dolna wartoõú ostrzegawcza,pH#" xstr(ph_wr_un),
			"Dolna wartoõú alarmowa,pH#" xstr(ph_alr_un),
			"Opèönienie alarmu,Min#" xstr(alr_dly_ph),
		"Regulacja pH#311",
			"Zakres regulacji P,pH#" xstr(ph_p),
			"Histereza,pH#" xstr(ph_hys),
			"Czas caòkowania,Sek#" xstr(ph_zi),
			"Zakres martwy,pH#" xstr(totband_ph),
		"Ustawienia dozowania#312",
			"Dozowanie ciôgòe réczne,Min#" xstr(ph_man_dos),
			"Wòôcz dozowanie ciôgòe#" xstr(set_nt),
			"Kontrola czasu dozowania,Min#" xstr(ph_dos_watch),
	"Redox#313",
		"Wartoõúi zadane redox#314",
			"Wart. pomiar.,mV#" xstr(rx_ix),
			"Wartoõú zadana,mV#" xstr(rx_soll),
			"Dolna wartoõú ostrzegawcza,mV#" xstr(rx_wr_un),
			"Dolna wartoõú alarmowa,mV#" xstr(rx_alr_un),
			"Opèönienie alarmu,Min#" xstr(alr_dly_rx),
		"Regulacja Redox#315",
			"Zakres regulacji P,mV#" xstr(rx_p),
			"Histereza,mV#" xstr(rx_hys),
		"Ustawienia dozowania#316",
			"Dozowanie ciôgòe réczne,Min#" xstr(rx_man_dos),
			"Wòôcz dozowanie ciôgòe#" xstr(set_nt),
			"Kontrola czasu dozowania,Min#" xstr(rx_dos_watch),
	"Kontrola wody pomiarowej#317",
		"Rodzaj#" xstr(mw_art_t),
		"Przepòyw,l/h#" xstr(fl_aktl_mw_ix),
		"Wskaönik przepòywu,P/l#" xstr(fl_rate_mw),
		"Minimalny przepòyw,l/h#" xstr(min_fl_mw),
		"Kompensacja,l/h#" xstr(flow_komp),
	"Data i czas#318",
		"Godziny#" xstr(std_1),
		"minuty#" xstr(min_1),
		"Dzieì#" xstr(day),
		"miesiôc#" xstr(mon),
		"rok#" xstr(year),
	"ACE#319",
		"Godziny#" xstr(asr_std),
		"minuty#" xstr(asr_min),
		"Liczba operacji ACE dziennie#" xstr(asr_day),
		"Réczne wòôczanie ACE#" xstr(set_nt),
	"Temperatura#320",
		"Kompensacja#" xstr(t_comp_t),
		"Kompensacja réczna,C#" xstr(t_man_comp),
		"Korekta,C#" xstr(t_korr),
"Wartoeci zadane Elektroliza#321",
	"Elektroliza#322",
		"Dozowanie solanki,%#" xstr(sole_dos),
		"Kontrola zasilania solankô,Min#" xstr(sole_nspw),
		"Ograniczanie temperatury,C#" xstr(temp_lim_t),
		"Maks. temperatura produktu C#" xstr(maxt),
		"Stéûenie CL2,g/l#" xstr(cl_konz),
		"Przepòyw,l/h#" xstr(flow_ely),
		"Poprawka,C#" xstr(t0_korr),
		"Monitorowanie napiùcia#" xstr(v_monitus_t),
	"Zbiornik produktu#323",
		"Monitor. poziomu#" xstr(lev_art_t),
		"Poziom przelewu,cm#" xstr(prodlev_ovfl),
		"Poziom maks.,cm#" xstr(prodlev_max),
		"Poziom min.,cm#" xstr(prodlev_min),
		"Tryb awaryjny#" xstr(not_btr_t),
		"Bieg awaryjny,min#" xstr(not_zeit),
	"Wentylator#324",
		"Czas rozbiegu,sek#" xstr(luft_vor),
		"Czas wybiegu,min#" xstr(luft_nach),
"Przekaönik#325",
	"Przekaönik 2 [#326",
		"Przyporzôdkowanie#" xstr(r3_strg_t),
		"Rodzaj regulacji#" xstr(r3_art_t),
		"Czéstotliwoõú impulsèw,P/h#" xstr(r3_frq),
		"Dòugoõú cyklu,Sek#" xstr(r3_pp),
		"Minimalny impuls,Sek#" xstr(r3_min),
	"RPrzekaönik 3 ]#327",
		"Przyporzôdkowanie#" xstr(r4_strg_t),
		"Rodzaj regulacji#" xstr(r4_art_t),
		"Czéstotliwoõú impulsèw,P/h#" xstr(r4_frq),
		"Dòugoõú cyklu,Sek#" xstr(r4_pp),
		"Minimalny impuls,Sek#" xstr(r4_min),
"Jézyk#" xstr(sprache_t),
"Ustawienie fabryczne#" xstr(set_nt),
"Dane urzôdzenia#328",
	"Numer urzôdzenia#" xstr(dev_nr_ix),
	"Wersja oprogramow.#" xstr(softver_ix),
	"Kontrola wersji oprogramow.#" xstr(soft_strg_ix),
	"Data produkcji#" xstr(mdate_in),
	"Producent#329",
		"dinotec GmbH",
		"Phillipp-Reis Str. 28",
		"D-61130 Nidderau",
		"Tel: 0049 (0)6187 41379-0",
		"Hotline: 0049 (0)6187 41379-72",
		"www.dinotec.de",
		"service@dinotec.de",
"Frei",
"Wentylator",
"Praca urzôdzenia",
"Alarm",
"Obniûanie pH",
"podnoszenie pH",
"Redox",
"CL2",
"CL2,pH",
"CL2,pH,Redox",
"pH",
"pH,Redox",
"Bez techniki pomiarowej",
"30",
"60",
"90",
"150",
"200",
"300",
"Ustaw",
"Cofnij",
"Wyòôczone",
"Tryb normalny",
"Napeòn.zbior.sol.",
"Napeònij celé",
"Napeònij urzôdzenie",
"Urzôdz. gotowe",
"Zbiornik solanki napeòniony",
"Cela napeòniona",
"Urzôdzenie napeònione",
"Urzôdzenie produkuje",
"Zmiékczacz zregenerowany",
"Alarm Instalacja",
"Ostrzeûenie Sprawdö dezynfekcjé DES",
"Alarm Pomiar poziomu Zbior.produktu",
"Alarm Zbiornik produktu Przelew",
"Alarm Napiécie celi za wysokie",
"Alarm Prôd za wysoki",
"Alarm Prôd za niski",
"Alarm Przepòyw za wysoki",
"Alarm Przepòyw za niski",
"Alarm Poziom Zbiornik solanki",
"Wòôcz / Wyòôcz",
"Czéstotliwoõú impulsèw",
"impuls / przerwa",
"tak",
"nie",
"réczne",
"Automatycznie",
"Ostrzeûenie Wysoka wartoõú CL2",
"Ostrzeûenie Niska wartoõú CL2",
"Ostrzeûenie Sprawdö sondé POT",
"Alarm CL2 Poziom gèrny",
"Alarm CL2 Poziom dolny",
"Alarm pH Poziom gèrny",
"Alarm pH Poziom dolny",
"Alarm Redox",
"Ostrzeûenie Redox",
"Ostrzeûenie gèrna wartoõú pH",
"Ostrzeûenie dolna wartoõú pH",
"Brak wody pomiar.",
"Pomiar poziomu",
"lôcznik pòywakowy",
"Pomiar przepòywu",
"Zewnétrzne zatrzymanie dozowania",
"Brak poòôczenia ze sterownikiem",
"Bòôd nachylenia charakterystyki CL2",
"Bòôd nachylenia charakter.sondy pH ",
"Bòôd punktu zerowego",
"Kanister pH pusty",
"Czas dozow. dezynf. przekroczony",
"Czas dozow. podnosz. pH przekrocz",
"Czas dozow. obniû. pH przekrocz.",
"Opèönianie wòôczenia aktywne",
"Dziaòa dozowanie ciôgòe",
"Dziaòa dozowanie ciôgòe pH",
"Gèrna granica dezynf. przekrocz.",
"Dolna granica dezynf. przekrocz.",
"Gèrna granica pH przekroczona",
"Dolna granica pH przekroczona",
"Alarm Temperat.produktu za wysoka",
"Ostrzeûen.Temperat.produk.za wysoka",
"Ostrzeûen.Temperat.produk.za niska",
"Alarm Napiécie celi za niskie",
"Po prostu ciesz sié czystô wodô!",
"Zbiornik produktu pusty",
"Dozowanie wyòôczone", 
"Elektroliza wyòôczone",
"Rozbieg wentylatora",					//   =vent_vor_txt
"Wybieg wentylatora",					//   =vent_nach_txt
"Ostrzegawcza operacja awaryjna",					
"0 - 1 mg/l",
"0 - 10 mg/l",
"Proces uruchamiania, proszù czekaú",
"Niemiecki",
"Angielski",
"Francuski",
"Hiszpaìski",
"Polski",
"Ukraiìski",
"Rosyjski",
"Wòoski",
"Czeski",
"Sòoweìski",
"Chorwacki",
"Wégierski",
"Rumuìski",
"Niederlandzki",
"Serbski",
"Communication#" xstr(komm_t),
"Modbus",
"dinoREMOTE",
"WLAN#330",
	"IP: #" xstr(ip_en),							// komma 124
	"SSID#" xstr(ssid_en),							// komma 125	
	"Signal strength,%#" xstr(sign_en),				// komma 126
	"Connected#" xstr(conn_en),						// komma 127
	"Server connection#" xstr(server_en),			// komma 127
	"WLAN reset#" xstr(wreset_en)					// komma 127

};
