const char* text_cz[] = {
"HLAVNí MENU",
"Kèd#" xstr(code0_in),
"Elektrolyza provoz#" xstr(btr_art_t),
"Konfigurace pßístroje#300",
	"Typ zaßízení,g/h#" xstr(anl_typ_t),
	"Bus adresa#" xstr(sh_adr),
	"Kontrast#" xstr(contr),
	"Míßící technika#" xstr(msr_t),
	"Rozsah merení Cl2#" xstr(mgl_t),
	"Cl2 pH kompenzací#" xstr(set_nt),
"Kalibrace#301",
	"Kalibrace chlorovå sondy#302",
		"Míß.hodnota,mg/l#" xstr(cl_val_ix),
		"Strmost,mV#" xstr(cl_sth_in),
		"Vstupní napítí,mV#" xstr(cl_mv_ix),
		"Uloñit Uein#" xstr(set_nt),
		"Uein uloñen,mV#" xstr(uin_saved_ix),
		"Nulov• bod,mV#" xstr(cl_mv0_in),
		"Stanovit nulov• bod#" xstr(set_nt),
		"DPD-hodnota,mg/l#" xstr(cl_dpd_in),
		"Kalibraóní reset#" xstr(set_nt),
		"Konec AER, Min#" xstr(aer_min_ix),
		"Kalibrace není moñnà",
		"Míß.hodnota < 0,1 mg/l",
		"Míß.hodnota < 0,05 mg/l",
	"Kalibrace pH#303",
		"Míß.hodnota,pH#" xstr(ph_ix),
		"Strmost,mV/pH#" xstr(ph_sth_in),
		"Nulov• bod,mV#" xstr(ph_null_in),
		"Vstupní napítí,mV#" xstr(ph_mv_ix),
		"Kalibrace pH 4/7#" xstr(ph_dpd2_in),
		"Kalibraóní reset#" xstr(set_nt),
"Nast.hodnota míßící techniky#304",
	"óasoví zpoñdínå spínàní,Min#" xstr(on_dly),
	"Nast.hodnota Cl2#305",
		"Nast.hodnota CL2#306",
			"Alarm. hodn. nahoße,mg/l#" xstr(cl_alr_ob),
			"Var. hod. nahoße,mg/l#" xstr(cl_wr_ob),
			"Poñadovanà hodnota,mg/l#" xstr(cl_soll),
			"Varovnà hodnota spodní,mg/l#" xstr(cl_wr_un),
			"Alarmovà hodnota spodní,mg/l#" xstr(cl_alr_un),
			"Alarmovå zpoñdíní,Min#" xstr(cl_alr_dly),
		"Regulace CL2#307",
			"P-oblast,mg/l#" xstr(cl_p),
			"Integraóní óasovà hodnota ,Sek#" xstr(cl_i),
			"Hystereze,mg/l#" xstr(cl_hys),
		"Nastavení dàvkovàní#308",
			"ruó. dàvkovàní,Min#" xstr(cl_man_dos),
			"Trvalå dàvkovàní zapnuto#" xstr(set_nt),
			"Hlídàní óasu dàvkovàní ,Min#" xstr(cl_dos_watch),
	"pH-hodnota#309",
		"Nast.hodnota pH   #310",
			"Alarm. hodn. nahoße,pH#" xstr(ph_alr_ob),
			"Var. hod. nahoße,pH#" xstr(ph_wr_ob),
			"Poñadovanà hodnota,pH#" xstr(ph_soll),
			"Varovnà hodnota spodní,pH#" xstr(ph_wr_un),
			"Alarmovà hodnota spodní,pH#" xstr(ph_alr_un),
			"Alarmovå zpoñdíní,Min#" xstr(alr_dly_ph),
		"Regulace pH#311",
			"P-oblast,pH#" xstr(ph_p),
			"Hystereze,pH#" xstr(ph_hys),
			"Integraóní óasovà hodnota ,Sek#" xstr(ph_zi),
			"Mrtv• bod,pH#" xstr(totband_ph),
		"Nastavení dàvkovàní#312",
			"ruó. dàvkovàní,Min#" xstr(ph_man_dos),
			"Trvalå dàvkovàní zapnuto#" xstr(set_nt),
			"Hlídàní óasu dàvkovàní ,Min#" xstr(ph_dos_watch),
	"Redox#313",
		"Nast.hodnota Redox#314",
			"Míß.hodnota,mV#" xstr(rx_ix),
			"Poñadovanà hodnota,mV#" xstr(rx_soll),
			"Varovnà hodnota spodní,mV#" xstr(rx_wr_un),
			"Alarmovà hodnota spodní,mV#" xstr(rx_alr_un),
			"Alarmovå zpoñdíní,Min#" xstr(alr_dly_rx),
		"Ragulace redox#315",
			"P-oblast,mV#" xstr(rx_p),
			"Hystereze,mV#" xstr(rx_hys),
		"Nastavení dàvkovàní#316",
			"ruó. dàvkovàní,Min#" xstr(rx_man_dos),
			"Trvalå dàvkovàní zapnuto#" xstr(set_nt),
			"Hlídàní óasu dàvkovàní ,Min#" xstr(rx_dos_watch),
	"Hlídàní míßenå vody#317",
		"Typ#" xstr(mw_art_t),
		"Pr®tok,l/h#" xstr(fl_aktl_mw_ix),
		"Míra pr®toku,P/l#" xstr(fl_rate_mw),
		"minimàlní pr®tok,l/h#" xstr(min_fl_mw),
		"Kompenzace,l/h#" xstr(flow_komp),
	"Datum a óas#318",
		"Hodina#" xstr(std_1),
		"Minuta#" xstr(min_1),
		"Den#" xstr(day),
		"Mísíc#" xstr(mon),
		"Rok#" xstr(year),
	"AER#319",
		"Hodina#" xstr(asr_std),
		"Minuta#" xstr(asr_min),
		"Poóet AER za den#" xstr(asr_day),
		"AER ruóní start#" xstr(set_nt),
	"Teplota#320",
		"Kompenzace#" xstr(t_comp_t),
		"Ruóní kompenzace,C#" xstr(t_man_comp),
		"Korekce,C#" xstr(t_korr),
"Nast.hodnota elektrol•zy#321",
	"Elektrol•za#322",
		"Dàvkovàní solanky,%#" xstr(sole_dos),
		"Hlídàní doplníní solanky,Min#" xstr(sole_nspw),
		"Teplotní limit,C#" xstr(temp_lim_t),
		"Max. teplota produktu C#" xstr(maxt),
		"CL2 koncentrace,g/l#" xstr(cl_konz),
		"Durchfluss,l/h#" xstr(flow_ely),
		"Korekce,C#" xstr(t0_korr),
		"Monitorovàní nap¶tí#" xstr(v_monitus_t),
	"Produkóní tank#323",
		"Sledovàní hladiny#" xstr(lev_art_t),
		"îroveê pßeteóení,cm#" xstr(prodlev_ovfl),
		"Max. hladina,cm#" xstr(prodlev_max),
		"Min. hladina,cm#" xstr(prodlev_min),
		"Nouzov• provoz#" xstr(not_btr_t),
		"Nouzov• chod,min#" xstr(not_zeit),
	"Ventilàtor#324",
		"Doba rozb¶hu,s#" xstr(luft_vor),
		"Doba dob¶hu,min#" xstr(luft_nach),
"Relå#325",
	"Relå 2 [#326",
		"Postoupení#" xstr(r3_strg_t),
		"Druh regulace#" xstr(r3_art_t),
		"Puls.frekvence,P/h#" xstr(r3_frq),
		"Doba kmitu,Sek#" xstr(r3_pp),
		"Minimàlní impuls,Sek#" xstr(r3_min),
	"Relå 3 ]#327",
		"Postoupení#" xstr(r4_strg_t),
		"Druh regulace#" xstr(r4_art_t),
		"Puls.frekvence,P/h#" xstr(r4_frq),
		"Doba kmitu,Sek#" xstr(r4_pp),
		"Minimàlní impuls,Sek#" xstr(r4_min),
"Jazyk#" xstr(sprache_t),
"Nastavení z v•roby#" xstr(set_nt),
"Data pßístroje#328",
	"óíslo pßístroje#" xstr(dev_nr_ix),
	"Stav softwaru#" xstr(softver_ix),
	"Datum v•roby#" xstr(mdate_in),
	"Kontrola verze softwaru#" xstr(soft_strg_ix),
	"V•robce#329",
		"dinotec GmbH",
		"Phillipp-Reis Str. 28",
		"D-61130 Nidderau",
		"Tel: 0049 (0)6187 41379-0",
		"Hotline: 0049 (0)6187 41379-72",
		"www.dinotec.de",
		"service@dinotec.de",
"Frei",
"Ventilàtor",
"Zaßízení v provozu",
"Alarm",
"pH sníñit",
"pH zv•ïit",
"Redox",
"CL2",
"CL2,pH",
"CL2,pH,Redox",
"pH",
"pH,Redox",
"bez míßící techniky",
"30",
"60",
"90",
"150",
"200",
"300",
"dosadit",
"reset",
"Vypnutå",
"Normàlní provoz",
"Tank solan.napl.",
"Celu naplnit",
"Zaßízení naplnit",
"Zaßízení je hotovo",
"Tank solanky naplnín",
"Cela naplnínà",
"Zaßízení naplníno",
"Zaßízení vyràbí",
"Tvrdost regenerovàna",
"Zabezpeóovací syståm v provozu",
"V•strahu DES-zaßízení pßezkouïet",
"Alarm míßení hladin.produk.v nàdrñi",
"Alarm pßeteóení produkóní nàdrñe",
"Alarm napítí cely pßíliï vysok•",
"Alarm proud pßíliï vysok•",
"Alarm proud pßíliï nízk•",
"Alarm pr®toku pßíliï vysok•",
"Alarm pr®toku pßíliï nízk•",
"Alarm hladiny nàdrñ.solnåho roztoku",
"Zap./ Vyp",
"Puls.frekvence",
"Puls/Pßestàvka",
"Ano",
"ne",
"ruóní",
"automaticky",
"V•straha Cl2 vysoko",
"V•straha Cl2 nízko",
"V•strahu POT sondu zkontrolovat",
"Alarm CL2 vysok•",
"Alarm CL2 nízk•",
"Alarm pH vysok•",
"Alarm pH nízk•",
"Alarm Redox",
"V•straha redox",
"V•straha pH vysoko",
"V•straha pH nízko",
"Hlídàní míßenå vody",
"M¶ßení hladiny",
"Plovàkov• spínaó",
"Míßení pr®toku",
"Externí stop dàvkovàní",
"ñàdnå pßipojení k ßídídímu dílu",
"Chyba strmosti Cl2",
"Chyba strmosti pH",
"Chyba nulovåho bodu",
"pH Kanystr je pràzdn•",
"Dàvkovací óas desinfekce pßekroóen",
"Dàvkovací óas zv•ïení pH pßekroóen",
"Dàvkovací óas sníñení pH pßekroóen",
"óasoví zpoñdínå spínàní aktivní",
"Trvalå dàvkovàní desinfekce bíñí",
"Trvalå dàvkovàní pH bíñí",
"Regulaóní hranice desinf.pßekroóena",
"Regulaóní hranice desinfek.nedosañ.",
"Regulaóní hranice pH pßekroóena",
"Regulaóní hranice pH nedosañena",
"Alarm teplota produktu vysokà",
"V•straha teplota produktu vysokà",
"V•straha teplota produktu nízkà",
"Alarm napítí cely pßíliï nízkà",
"Prostí lepïí voda!",
"Produkóní tank je pràzdn•",
"Dàvkovàní vypnutå", 
"Elektrol•zy vypnutå",
"Ventilàtor, rozb¶h",					//   =vent_vor_txt
"Ventilàtor, dob¶h",					//   =vent_nach_txt
"V•straha nouzov• provoz",
"0 - 1 mg/l",
"0 - 10 mg/l",
"Proces spouït¶ní, vyókejte prosím",
"Nímecky",
"Anglicky",
"Francouzsky",
"ïpanílsk•",
"Polsky",
"Ukrajinsky",
"Rusky",
"Italsky",
"óesky",
"Slovinsky",
"Chorvatsky",
"Madarsky",
"Rumunsky",
"Holandsky",
"Srbsky",
"Communication#" xstr(komm_t),
"Modbus",
"dinoREMOTE",
"WLAN#330",
	"IP: #" xstr(ip_en),							// komma 124
	"SSID#" xstr(ssid_en),							// komma 125	
	"Signal strength,%#" xstr(sign_en),				// komma 126
	"Connected#" xstr(conn_en),						// komma 127
	"Server connection#" xstr(server_en),			// komma 127
	"WLAN reset#" xstr(wreset_en)					// komma 127

};
