const char* text_sr[] = {
"GLAVNI MENI",
"Kod#" xstr(code0_in),
"Pogon elektroliz.#" xstr(btr_art_t),
"Konfiguracija ure£aja#300",
	"Tip ure£aja,g/h#" xstr(anl_typ_t),
	"Bus adresa#" xstr(sh_adr),
	"Kontrast#" xstr(contr),
	"Merna tehnika#" xstr(msr_t),
	"Merni opseg Cl2#" xstr(mgl_t),
	"Cl2 pH-kompensovana#" xstr(set_nt),
"Kalibracija#301",
	"Kalibracija elektrode za hlor#302",
		"Merna vrednost,mg/l#" xstr(cl_val_ix),
		"Nagib,mV#" xstr(cl_sth_in),
		"Ulazni napon,mV#" xstr(cl_mv_ix),
		"Sa—uvati Uein#" xstr(set_nt),
		"Uein sa—uvati,mV#" xstr(uin_saved_ix),
		"Nulta ta—ka,mV#" xstr(cl_mv0_in),
		"Pode•avanje nulte ta—ke#" xstr(set_nt),
		"DPD-vrednost,mg/l#" xstr(cl_dpd_in),
		"Reset kalibracije#" xstr(set_nt),
		"Zavr•etak AER,Min#" xstr(aer_min_ix),
		"Kalibracija nije moguæa",
		"Merna vrednost < 0,1 mg/l",
		"Merna vrednost < 0,05 mg/l",
	"Kalibracija pH#303",
		"Merna vrednost,pH#" xstr(ph_ix),
		"Nagib,mV/pH#" xstr(ph_sth_in),
		"Nulta ta—ka,mV#" xstr(ph_null_in),
		"Ulazni napon,mV#" xstr(ph_mv_ix),
		"Kalibracija pH4/7#" xstr(ph_dpd2_in),
		"Reset kalibracije#" xstr(set_nt),
"–eljena vrednost merne opreme#304",
	"Odlaganje,Min#" xstr(on_dly),
	"–eljena vrednost Cl2#305",
		"–eljena vrednost CL2#306",
			"Vrednost alarma iznad,mg/l#" xstr(cl_alr_ob),
			"Upozorav.vrednos.je iznad,mg/l#" xstr(cl_wr_ob),
			"–eljena_vrednost,mg/l#" xstr(cl_soll),
			"Upozorav.vrednos.je ispod,mg/l#" xstr(cl_wr_un),
			"Vrednost alarma ispod,mg/l#" xstr(cl_alr_un),
			"Odlaganje_alarma,Min#" xstr(cl_alr_dly),
		"Regulacija CL2#307",
			"P-podru—je,mg/l#" xstr(cl_p),
			"Sastavni,Sek#" xstr(cl_i),
			"Histerezis,mg/l#" xstr(cl_hys),
		"Pode•avanje-doziranja#308",
			"ru—.kontinuirano doziranje,Min#" xstr(cl_man_dos),
			"Prekid na kontinuir.doziranja#" xstr(set_nt),
			"Nadzor vremena doziranja,Min#" xstr(cl_dos_watch),
	"pH vrednost#309",
		"–eljena vrednost pH#310",
			"Vrednost alarma iznad,pH#" xstr(ph_alr_ob),
			"Upozorav.vrednost je iznad,pH#" xstr(ph_wr_ob),
			"–eljena vrednost,pH#" xstr(ph_soll),
			"Upozorav.vrednos.je ispod,pH#" xstr(ph_wr_un),
			"Vrednost alarma ispod,pH#" xstr(ph_alr_un),
			"Odlaganje alarma,Min#" xstr(alr_dly_ph),
		"Regulacija pH#311",
			"P-podru—je,pH#" xstr(ph_p),
			"Histerezis,pH#" xstr(ph_hys),
			"Sastavni,Sek#" xstr(ph_zi),
			"Prazno podru—je,pH#" xstr(totband_ph),
		"Pode•avanje-doziranja#312",
			"ru—.kontinuirano doziranje,Min#" xstr(ph_man_dos),
			"Prekid na kontinuir.doziranja#" xstr(set_nt),
			"Nadzor vremena doziranja,Min#" xstr(ph_dos_watch),
	"Redox#313",
		"–eljena vrednost Redox#314",
			"Merna vrednost,mV#" xstr(rx_ix),
			"–eljena_vrednost,mV#" xstr(rx_soll),
			"Upozorav.vrednost je ispod,mV#" xstr(rx_wr_un),
			"Vrednost alarma ispod,mV#" xstr(rx_alr_un),
			"Odlaganje alarma,Min#" xstr(alr_dly_rx),
		"Regulacija Redox#315",
			"P-podru—je,mV#" xstr(rx_p),
			"Histerezis,mV#" xstr(rx_hys),
		"Pode•avanje-doziranja#316",
			"ru—.kontinuirano doziranje,Min#" xstr(rx_man_dos),
			"Prekid na kontinuir.doziranja#" xstr(set_nt),
			"Nadzor vremena doziranja,Min#" xstr(rx_dos_watch),
	"Nadzor uzorkovane vode#317",
		"•ifra#" xstr(mw_art_t),
		"Protok,l/h#" xstr(fl_aktl_mw_ix),
		"Stepen protoka,P/l#" xstr(fl_rate_mw),
		"minimalni protok,l/h#" xstr(min_fl_mw),
		"Kompenzacija,l/h#" xstr(flow_komp),
	"Datum i vreme#318",
		"Sati#" xstr(std_1),
		"Minuti#" xstr(min_1),
		"Dan#" xstr(day),
		"Mesec#" xstr(mon),
		"Godina#" xstr(year),
	"AER#319",
		"Sati#" xstr(asr_std),
		"Minuti#" xstr(asr_min),
		"Koli—ina AER po danu#" xstr(asr_day),
		"AER ru—no pokretanje#" xstr(set_nt),
	"Temperatura#320",
		"Kompenzacija#" xstr(t_comp_t),
		"Ru—na kompenzacija,C#" xstr(t_man_comp),
		"Korekcija,C#" xstr(t_korr),
"–eljena vrednost Elektrolizer#321",
	"Elektrolizer#322",
		"Doziranje soli,%#" xstr(sole_dos),
		"Nadzor soli,Min#" xstr(sole_nspw),
		"Temperaturni limit,C#" xstr(temp_lim_t),
		"Max.temperatura proizvoda.C#" xstr(maxt),
		"CL2-koncentracija,g/l#" xstr(cl_konz),
		"Protok,l/h#" xstr(flow_ely),
		"Korekcija,C#" xstr(t0_korr),
		"Praœenja napona#" xstr(v_monitus_t),
	"Proizvodni rezervoar#323",
		"Praœenje nivoa#" xstr(lev_art_t),
		"Nivo prelivanja,cm#" xstr(prodlev_ovfl),
		"Max nivo,cm#" xstr(prodlev_max),
		"Min nivo,cm#" xstr(prodlev_min),
		"U slu—aju nu–de#" xstr(not_btr_t),
		"Nu–ni,min#" xstr(not_zeit),
	"Ventilator#324",
		"Vreme pripremnog rada,sek#" xstr(luft_vor),
		"Vreme zaustavljanja,min#" xstr(luft_nach),
"Relej#325",
	"Relej 2 [#326",
		"Zadatak#" xstr(r3_strg_t),
		"Tip regulatora#" xstr(r3_art_t),
		"Frekventni impuls,P/h#" xstr(r3_frq),
		"Period trajanje,Sek#" xstr(r3_pp),
		"Minimalni impuls,Sek#" xstr(r3_min),
	"Relej 3 ]#327",
		"Zadatak#" xstr(r4_strg_t),
		"Tip regulatora#" xstr(r4_art_t),
		"Frekventni impuls,P/h#" xstr(r4_frq),
		"Period trajanje,Sek#" xstr(r4_pp),
		"Minimalni impuls,Sek#" xstr(r4_min),
"Jezik#" xstr(sprache_t),
"Fabri—ka pode•avanja#" xstr(set_nt),
"Datum ure£aja#328",
	"Broj ure£aja#" xstr(dev_nr_ix),
	"Verzija softvera#" xstr(softver_ix),
	"Kontrolu verzije softvera#" xstr(soft_strg_ix),
	"Datum proizvodnje#" xstr(mdate_in),
	"Proizvodja—#329",
		"dinotec GmbH",
		"Phillipp-Reis Str. 28",
		"D-61130 Nidderau",
		"Tel: 0049 (0)6187 41379-0",
		"Hotline: 0049 (0)6187 41379-72",
		"www.dinotec.de",
		"service@dinotec.de",
"Nevezan",
"Ventilator",
"Ure£aj je u radu",
"Alarm",
"ph smanjivanje",
"ph poveæavanje",
"Redox",
"CL2",
"CL2,pH",
"CL2,pH,Redox",
"pH",
"pH,Redox",
"bez merne opreme",
"30",
"60",
"90",
"150",
"200",
"300",
"odre£ivanje",
"resetovanje",
"Isklju—ivanje",
"Normalan rad",
"Rezerv.slan.se puni",
"æelija se puni",
"Ure£aj se puni",
"Ure£aj je spreman",
"Rezervoar slanice je napunjen",
"æelija je napunjena",
"Ure£aj je popunjen",
"Ure£aj proizvodi",
"Regeneracija omek•iva—a",
"Alarm oprema u radu",
"Upozorenje DES-ure£aja proveriti",
"Alarm nivoa kod proizvod.rezervoara",
"Alarm prelivanje proizv.rezervoara",
"Alarm napon u æeliji je previsok",
"Alarm struja je previ•e jaka",
"Alarm struja je slaba",
"Alarm protok je previsok",
"Alarm protok je previ•e mali",
"Alarm nivoa kod rezerv.za slanicu",
"OD-DO",
"Frekventni_impuls",
"Puls-Pauza",
"Da",
"Ne",
"ru—no",
"automatski",
"Upozorenje CL2 iznad",
"Upozorenje ispod CL2",
"Upozorenje POT-elektrode proveriti",
"Alarm CL2 iznad",
"Alarm CL2 ispod",
"Alarm pH iznad",
"Alarm pH ispod",
"Alarm Redox",
"Upozorenje Redox",
"Upozorenje pH iznad",
"Upozorenje pH ispod",
"Manjak uzorkovane vode",
"mjerenje razine",
"Plivajuæi prekida—",
"Merenje protoka",
"Zavr•etak spoljnog doziranja",
"Ne postoji veza sa upravlja—k.delom",
"Gre•ka nagiba Cl2",
"Gre•ka nagiba pH",
"Gre•ka kod nulte ta—ke",
"kanister pH je prazan",
"Prekora—eno je doziranje dezinfic.",
"Prekor.je dozir.sredst.za poveæ.pH",
"Prekor.je dozir.sredst.za sman.pH",
"Odlaganje uklju—ivanja aktivirano",
"Kontinuirano dozir.dezinfic.u toku",
"Kontinuirano doziranje pH u toku",
"Grani—na vrednost dezinfekc.iznad",
"Grani—na vrednost dezinfekc.ispod",
"Grani—na vrednost pH iznad",
"Grani—na vrednost pH ispod",
"Alarm temperat.produkta previsoka",
"Upozorenje temper.produk.je visoka",
"Upozorenje temper.produk.je niska",
"Alarm napon u æeliji je prenizak",
"U–ivanje u naj—istijoj vodi",
"Proizvodni rezervoar je prazan",
"doziranje isklju—ivanje", 
"Elektrolizer isklju—ivanje",
"Pripremni rad ventilatora",					//   =vent_vor_txt
"Zaustavljanje ventilator",					//   =vent_nach_txt
"Upozorenje hitne operacije",
"0 - 1 mg/l",
"0 - 10 mg/l",
"Proces pokretanja, sa—ekajte",
"Nema—ki",
"Engleski",
"Francuski",
"•panski",
"Poljski",
"Ukrajinski",
"Ruski",
"Italijanski",
"—e•ki",
"Slovena—ki",
"Hrvatski",
"Ma£arski",
"Rumunski",
"Holandski",
"Srpski",
"Communication#" xstr(komm_t),
"Modbus",
"dinoREMOTE",
"WLAN#330",
	"IP: #" xstr(ip_en),							// komma 124
	"SSID#" xstr(ssid_en),							// komma 125	
	"Signal strength,%#" xstr(sign_en),				// komma 126
	"Connected#" xstr(conn_en),						// komma 127
	"Server connection#" xstr(server_en),			// komma 127
	"WLAN reset#" xstr(wreset_en)					// komma 127

};
