char* text_it[] = {
"MENU PRINCIPALE",
"Codice#" xstr(code0_in),
"Funzion.elettrolisi#" xstr(btr_art_t),
"Configurazione apparecchio#300",
	"Tipo di impianto,g/h#" xstr(anl_typ_t),
	"Indirizzo bus#" xstr(sh_adr),
	"Contrasto#" xstr(contr),
	"Tecnica di misuraz.#" xstr(msr_t),
	"Campo di misura Cl2#" xstr(mgl_t),
	"Cl2 pH compensata#" xstr(set_nt),
"Calibratura#301",
	"Calibratura sonda cloro#302",
		"Valore di misura,mg/l#" xstr(cl_val_ix),
		"Pendenza,mV#" xstr(cl_sth_in),
		"Tensione d'ingresso,mV#" xstr(cl_mv_ix),
		"Salvare tensione ingresso#" xstr(set_nt),
		"Tensione ingresso salvata,mV#" xstr(uin_saved_ix),
		"Punto zero,mV#" xstr(cl_mv0_in),
		"Imposta punto zero#" xstr(set_nt),
		"Valore DPD,mg/l#" xstr(cl_dpd_in),
		"Reset calibratura#" xstr(set_nt),
		"Fine AER tra,min#" xstr(aer_min_ix),
		"Impossibile calibrare",
		"Valore di misura < 0,1 mg/l",
		"Valore di misura < 0,05 mg/l",
	"Calibratura pH #303",
		"Valore di misura,pH#" xstr(ph_ix),
		"Pendenza,mV/pH#" xstr(ph_sth_in),
		"Punto zero,mV#" xstr(ph_null_in),
		"Tensione d'ingresso,mV#" xstr(ph_mv_ix),
		"Calibratura pH4/7#" xstr(ph_dpd2_in),
		"Reset calibratura#" xstr(set_nt),
"Valori teorici tecnica di misuraz.#304",
	"Ritardo d'inserzione,min#" xstr(on_dly),
	"Valori teorici Cl2#305",
		"Valori teorici CL2#306",
			"Valore allarme superiore,mg/l#" xstr(cl_alr_ob),
			"Valore avvertim.super.,mg/l#" xstr(cl_wr_ob),
			"Valore nominale,mg/l#" xstr(cl_soll),
			"Valore avvertim.inferiore,mg/l#" xstr(cl_wr_un),
			"Valore allarme inferiore,mg/l#" xstr(cl_alr_un),
			"Ritardo allarme,min#" xstr(cl_alr_dly),
		"Regolazione CL2#307",
			"Banda proporzionale,mg/l#" xstr(cl_p),
			"Tempo azione integrale,sec#" xstr(cl_i),
			"Isteresi,mg/l#" xstr(cl_hys),
		"Impostazioni dosaggio#308",
			"Dosaggio continuo manuale,min#" xstr(cl_man_dos),
			"Attivare dosaggio continuo#" xstr(set_nt),
			"Monitor tempo dosaggio,min#" xstr(cl_dos_watch),
	"Valori pH#309",
		"Valori teorici pH#310",
			"Valore allarme superiore,pH#" xstr(ph_alr_ob),
			"Valore avvertimento super.,pH#" xstr(ph_wr_ob),
			"Valore nominale,pH#" xstr(ph_soll),
			"Valore avvertimento infer.,pH#" xstr(ph_wr_un),
			"Valore allarme inferiore,pH#" xstr(ph_alr_un),
			"Ritardo allarme,min#" xstr(alr_dly_ph),
		"Regolazione pH#311",
			"Banda proporzionale,pH#" xstr(ph_p),
			"Isteresi,pH#" xstr(ph_hys),
			"Tempo azione integrale,sec#" xstr(ph_zi),
			"Banda morta,pH#" xstr(totband_ph),
		"Impostazioni dosaggio#312",
			"Dosaggio continuo manuale,min#" xstr(ph_man_dos),
			"Attivare dosaggio continuo#" xstr(set_nt),
			"Monitor tempo dosaggio,min#" xstr(ph_dos_watch),
	"Redox#313",
		"Valori teorici Redox#314",
			"Valore di misura,mV#" xstr(rx_ix),
			"Valore nominale,mV#" xstr(rx_soll),
			"Valore avvertimento infer.,mV#" xstr(rx_wr_un),
			"Valore allarme inferiore,mV#" xstr(rx_alr_un),
			"Ritardo allarme,min#" xstr(alr_dly_rx),
		"Regolazione Redox#315",
			"Banda proporzionale,mV#" xstr(rx_p),
			"Isteresi,mV#" xstr(rx_hys),
		"Impostazioni dosaggio#316",
			"Dosaggio continuo manuale,min#" xstr(rx_man_dos),
			"Attivare dosaggio continuo#" xstr(set_nt),
			"Monitor tempo dosaggio,min#" xstr(rx_dos_watch),
	"Controllo acqua misurazioni#317",
		"Tipo#" xstr(mw_art_t),
		"Portata,l/h#" xstr(fl_aktl_mw_ix),
		"Impulsi/litro,P/l#" xstr(fl_rate_mw),
		"Portata minima,l/h#" xstr(min_fl_mw),
		"Compensazione,l/h#" xstr(flow_komp),
	"Data e ora#318",
		"Ore#" xstr(std_1),
		"minuti#" xstr(min_1),
		"Giorno#" xstr(day),
		"Mese#" xstr(mon),
		"Anno#" xstr(year),
	"AER#319",
		"Ore#" xstr(asr_std),
		"Minuti#" xstr(asr_min),
		"Numero AER al giorno#" xstr(asr_day),
		"Avvio manuale AER#" xstr(set_nt),
	"Temperatura#320",
		"Compensazione#" xstr(t_comp_t),
		"Compensazione manuale,°C#" xstr(t_man_comp),
		"Correzione,°C#" xstr(t_korr),
"Valori teorici elettrolisi#321",
	"Elettrolisi#322",
		"Dosaggio salamoia,%#" xstr(sole_dos),
		"Monitorag.aggiunta salam.,min#" xstr(sole_nspw),
		"Limitare temperatura,°C#" xstr(temp_lim_t),
		"Temp. max. prod. °C#" xstr(maxt),
		"Concentrazione CL2,g/l#" xstr(cl_konz),
		"Portata,l/h#" xstr(flow_ely),
		"Correzione,°C#" xstr(t0_korr),
		"Monitoraggio della tensione#" xstr(v_monitus_t),
	"Serbatoio prodotto#323",
		"monitor.del livello#" xstr(lev_art_t),
		"Troppopieno livello,cm#" xstr(prodlev_ovfl),
		"Livello max,cm#" xstr(prodlev_max),
		"Livello min,cm#" xstr(prodlev_min),
	"Ventilatore#324",
		"Tempo anticipo,sec#" xstr(luft_vor),
		"Tempo ritardo,min#" xstr(luft_nach),
"Relè#325",
	"Relè 3 [#326",
		"Assegnazione#" xstr(r3_strg_t),
		"Tipo di regolatore#" xstr(r3_art_t),
		"Frequenza impulsi,P/h#" xstr(r3_frq),
		"Durata periodo,sec#" xstr(r3_pp),
		"Impulso minimo,sec#" xstr(r3_min),
	"Relè 4 ]#327",
		"Assegnazione#" xstr(r4_strg_t),
		"Tipo di regolatore#" xstr(r4_art_t),
		"Frequenza impulsi,P/h#" xstr(r4_frq),
		"Durata periodo,sec#" xstr(r4_pp),
		"Impulso minimo,sec#" xstr(r4_min),
"Lingua#" xstr(sprache_t),
"Impostazione di fabbrica#" xstr(set_nt),
"Dati apparecchio#328",
	"N. apparecchio#" xstr(dev_nr_ix),
	"Data software#" xstr(softver_in),
	"Data di fabbricazione#" xstr(mdate_in),
	"Fabbricante#329",
		"dinotec GmbH",
		"Phillipp-Reis Str. 28",
		"D-61130 Nidderau",
		"Tel: 0049 (0)6187 41379-0",
		"Hotline: 0049 (0)6187 41379-72",
		"www.dinotec.de",
		"service@dinotec.de",
"Frei",
"Ventilatore",
"Impianto in funzione",
"Allarme",
"Abbassa pH",
"Aumenta pH",
"Redox",
"CL2",
"CL2,pH",
"CL2,pH,Redox",
"pH",
"pH,Redox",
"senza di misuraz.",
"30",
"60",
"90",
"150",
"200",
"300",
"Imposta",
"Ripristina",
"Disattivato",
"Modalità normale",
"Riemp.serbat.sal.",
"Riempire cella",
"Riemp.l'impianto",
"Impianto pronto ",
"Serbatoio salamoia riempito",
"Cella riempita",
"Impianto riempito",
"Produzione in corso",
"Addolcimento in corso",
"Allarme funzionamento impianto",
"Avvertimento controllo impianto DES",
"Allar.misuraz. livello serbat. prod.",
"Allarme troppopieno serbatoio prod.",
"Allarme tensione cella troppo alta",
"Allarme corrente troppo alta",
"Allarme corrente troppo bassa",
"Allarme portata eccessiva",
"Allarme portata insufficiente",
"Allarme livello serbatoio salamoia",
"ON / OFF",
"Frequenza impulsi",
"Impulso/pausa",
"Sì",
"No",
"manuale",
"automatico",
"Avvertimento superiore CL2",
"Avvertimento inferiore CL2",
"Avvertimento controllo sonda POT",
"Allarme CL2 superiore",
"Allarme CL2 inferiore",
"Allarme pH superiore",
"Allarme pH inferiore",
"Allarme Redox",
"Avvertimento Redox",
"Avvertimento superiore pH",
"Avvertimento inferiore pH",
"Mancanza acqua per misurazioni",
"Misura di livello",
"Interrut.a galleg.",
"Misurazione portata",
"Stop dosaggio esterno",
"Nessun collegam.sezione di comando",
"Errore pendenza Cl2",
"Errore di pendenza pH",
"Errore punto zero",
"Fusto pH vuoto",
"Tempo dosaggio disinfez. superato",
"Tempo dosaggio aumenta pH super.",
"Tempo dosaggio abbassa pH super.",
"Ritardo d'inserzione attivo",
"Dosaggio continuo disinfezione",
"Dosaggio continuo pH",
"Lim.regolaz.disinfezione superato",
"Lim.regolaz.disinfez.non raggiunto",
"Limite regolazione pH superato",
"Limite regolazione pH non raggiunto",
"Allarme temp. prodotto troppo alta",
"Avvertimento temp. prodotto alta",
"Avvertimento temp. prodotto bassa",
"Allarm.tensione cella troppo bassa",
"Acqua perfet.nel.massi.semplicità!",
"Serbatoio prodotto vuoto",
"Dosaggio disattivato", 
"Elettrolisi disattivato",
"Anticipo ventilatore",					//   =vent_vor_txt
"Ritardo ventilatore",					//   =vent_nach_txt
"0 - 1 mg/l",
"0 - 10 mg/l",
"Tedesco",
"Inglese",
"Francese",
"Spagnolo",
"Polacco",
"Ucraino",
"Russo",
"Italiano",
"Ceco",
"Sloveno",
"Croato",
"Ungherese",
"Rumeno",
"Olandese",
"Serbo",
};
