const char* text_ua[] = {
"‚OˆOBHE MEH”",
"Ko™#" xstr(code0_in),
"EŸe£poŸi› ¢pa¥­±#" xstr(btr_art_t),
"Ko¡¤i˜ypa¥i® ¢pœŸa™y#300",
	"Tœ¢ yc£a¡o—œ,˜/˜#" xstr(anl_typ_t),
	"Po›£a§y—a¡¡® §œ¡œ#" xstr(sh_adr),
	"Ko¡£pac£#" xstr(contr),
	"Bœ ip­—aŸ«¡e o–Ÿa™¡a¡¡®#" xstr(msr_t),
	"Messbereich Cl2#" xstr(mgl_t),
	"Cl2 › pH o ¢e¡ca¥i±­#" xstr(set_nt),
"KaŸi–py—a¡¡®#301",
	"KaŸi–py—a¡¡® xŸop¡o˜o eŸe£po™y#302",
		"Bœ .›¡a¦., ˜/Ÿ#" xstr(cl_val_ix),
		"Kpy£œ›¡a, B#" xstr(cl_sth_in),
		"Bxi™¡a ¡a¢py˜a, B#" xstr(cl_mv_ix),
		"…–epe˜£œ ®#" xstr(set_nt),
		"…–epe˜£œ ®, B#" xstr(uin_saved_ix),
		"HyŸ«o—a £o¦a, B#" xstr(cl_mv0_in),
		"HaŸa§£.¡yŸ«o—o² £o¦œ#" xstr(set_nt),
		"DPD-›¡a¦e¡¡®, ˜/Ÿ#" xstr(cl_dpd_in),
		"Cœ™ aŸi–py—a¡¡®#" xstr(set_nt),
		"ac ›ai¡¦e¡¡® AER,x—œ#" xstr(aer_min_ix),
		"KaŸi–py—a¡¡® ¡e  ošŸœ—e",
		"Bœ .›¡a¦. < 0,1 mg/l",
		"Bœ .›¡a¦. < 0,05 mg/l",
	"KaŸi–py—a¡¡® pH#303",
		"Bœ .›¡a¦.,pH#" xstr(ph_ix),
		"Kpy£œ›¡a, B/pH#" xstr(ph_sth_in),
		"HyŸ«o—a £o¦a, B#" xstr(ph_null_in),
		"Bxi™¡a ¡a¢py˜a, B#" xstr(ph_mv_ix),
		"KaŸi–py—a¡¡® pH4/7#" xstr(ph_dpd2_in),
		"Cœ™ aŸi–py—a¡¡®#" xstr(set_nt),
"Ho .›¡a¦.—œ ip.o–Ÿa™¡.#304",
	"…a£pœ a —Ÿ­¦e¡¡®,x—œ#" xstr(on_dly),
	"Ho .›¡a¦. Cl2#305",
		"Ho i¡.›¡a¦.CL2#306",
			"Bepx¡± £pœ—.›¡a¦., ˜/Ÿ#" xstr(cl_alr_ob),
			"Bepx¡± ¢o¢epe™š.›¡a¦e¡¡®, ˜/Ÿ#" xstr(cl_wr_ob),
			"Ho i¡.›¡a¦e¡¡®, ˜/Ÿ#" xstr(cl_soll),
			"‰o¢epe™še¡¡® ¡œš¡.›¡a¦., ˜/Ÿ#" xstr(cl_wr_un),
			"Hœš¡± £pœ—.›¡a¦., ˜/Ÿ#" xstr(cl_alr_un),
			"…a£pœ a £pœ—oš.cœ˜¡aŸi›.,x—œ#" xstr(cl_alr_dly),
		"Pe˜yŸ­—a¡¡® CL2#307",
			"P-™ia¢a›o¡, ˜/Ÿ#" xstr(cl_p),
			"ac i›o™po a,ce#" xstr(cl_i),
			"‚ic£epe›œc, ˜/Ÿ#" xstr(cl_hys),
		"HaŸa§£y—a¡¡® ™o›a¥i²#308",
			"py¦¡a ™o›a¥i®,x—œ#" xstr(cl_man_dos),
			"ac ™o›a¥œi — ¡.#" xstr(set_nt),
			"Ko¡£poŸ« ¦acy ™o›a¥i²,x—œ#" xstr(cl_dos_watch),
	"…¡a¦e¡® pH#309",
		"Ho i¡aŸ«¡e ›¡a¦.pH#310",
			"Bepx¡± £pœ—.›¡a¦.,pH#" xstr(ph_alr_ob),
			"Bepx¡± ¢o¢epe™š.›¡a¦e¡¡®,pH#" xstr(ph_wr_ob),
			"Ho i¡.›¡a¦e¡¡®,pH#" xstr(ph_soll),
			"‰o¢epe™še¡¡® ¡œš¡.›¡a¦.,pH#" xstr(ph_wr_un),
			"Hœš¡± £pœ—.›¡a¦.,pH#" xstr(ph_alr_un),
			"…a£pœ a £pœ—oš.cœ˜¡aŸi›.,x—œ#" xstr(alr_dly_ph),
		"Pe˜yŸ­—a¡¡® pH#311",
			"P-™ia¢a›o¡,pH#" xstr(ph_p),
			"‚ic£epe›œc,pH#" xstr(ph_hys),
			"ac i›o™po a,ce#" xstr(ph_zi),
			"Mep£—a ›o¡a,pH#" xstr(totband_ph),
		"HaŸa§£y—a¡¡® ™o›a¥i²#312",
			"py¦¡a ™o›a¥i®,x—œ#" xstr(ph_man_dos),
			"ac ™o›a¥œi — ¡.#" xstr(set_nt),
			"Ko¡£poŸ« ¦acy ™o›a¥i²,x—œ#" xstr(ph_dos_watch),
	"Redox#313",
		"Ho i¡aŸ«¡e ›¡a¦. Redox#314",
			"Bœ .›¡a¦., B#" xstr(rx_ix),
			"Ho i¡.›¡a¦e¡¡®, B#" xstr(rx_soll),
			"‰o¢epe™še¡¡® ¡œš¡.›¡a¦., B#" xstr(rx_wr_un),
			"Hœš¡± £pœ—.›¡a¦., B#" xstr(rx_alr_un),
			"…a£pœ a £pœ—oš.cœ˜¡aŸi›.,x—œ#" xstr(alr_dly_rx),
		"Pe˜yŸ­—a¡¡® Redox#315",
			"P-™ia¢a›o¡, B#" xstr(rx_p),
			"‚ic£epe›œc, B#" xstr(rx_hys),
		"HaŸa§£y—a¡¡® ™o›a¥i²#316",
			"py¦¡a ™o›a¥i®,x—œ#" xstr(rx_man_dos),
			"ac ™o›a¥œi — ¡.#" xstr(set_nt),
			"Ko¡£poŸ« ¦acy ™o›a¥i²,x—œ#" xstr(rx_dos_watch),
	"Ko¡£poŸ« ›a —œ ip. —o™o­#317",
		"Tœ¢#" xstr(mw_art_t),
		"‰po£ia¡¡®,Ÿ/˜#" xstr(fl_aktl_mw_ix),
		"O–'±  ¢o£oy,¢/Ÿ#" xstr(fl_rate_mw),
		" i¡i aŸ«¡œ ¢o£o,Ÿ/˜#" xstr(min_fl_mw),
		"Ko ¢e¡ca¥i®,Ÿ/˜#" xstr(flow_komp),
	"ƒa£a £a ¦ac#318",
		"˜o™œ¡œ#" xstr(std_1),
		"x—œŸœ¡œ#" xstr(min_1),
		"™e¡«#" xstr(day),
		" ic®¥«#" xstr(mon),
		"pi#" xstr(year),
	"AER#319",
		"˜o™œ¡œ#" xstr(asr_std),
		"x—œŸœ¡œ#" xstr(asr_min),
		"KiŸ«ic£« AER ›a ™o–y#" xstr(asr_day),
		"AER c£ap£ —py¦¡y#" xstr(set_nt),
	"Te ¢epa£ypa#320",
		"Ko ¢e¡ca¥i®#" xstr(t_comp_t),
		"Py¦¡a o ¢e¡ca¥i®,C#" xstr(t_man_comp),
		"Kope£y—a¡¡®,C#" xstr(t_korr),
"Ho i¡. ›¡a¦. eŸe£poŸi›y#321",
	"EŸe£poŸi›#322",
		"ƒo›y—a¡¡® coŸ«o—o˜o po›¦œ¡y,%#" xstr(sole_dos),
		"Ko¡£poŸ« ¢i™šœ—.coŸ«.po›¦.,x—œ#" xstr(sole_nspw),
		"O– ešœ£œ £e ¢epa£ypy,C#" xstr(temp_lim_t),
		"Mac.£e ¢ep.¢po™y£y.C#" xstr(maxt),
		"CL2-o¡¥e¡£pa¥i®,˜/Ÿ#" xstr(cl_konz),
		"O–'±  ¢o£oy,¢/Ÿ#" xstr(flow_ely),
		"Kope¥i®,C#" xstr(t0_korr),
		"Ko¡£poŸ« ¡a¢py˜œ#" xstr(v_monitus_t),
	"± ic£« ˜o£o—o˜o ¢po™y£y#323",
		"Ko¡£poŸ« pi—¡®#" xstr(lev_art_t),
		"Pi—e¡« ¢epeŸœ—y,c #" xstr(prodlev_ovfl),
		"Pi—e¡«  ac.,c #" xstr(prodlev_max),
		"Pi—e¡«  i¡.,cm#" xstr(prodlev_min),
		"A—api¡œ pešœ #" xstr(not_btr_t),
		"A—api¡œ xi™,x—œ#" xstr(not_zeit),
	"Be¡£œŸ®£op#324",
		"ac ¢o¦a£. ¢ycy,ce#" xstr(luft_vor),
		"ac pyxy ¢o i¡ep¥i²,x—#" xstr(luft_nach),
"PeŸe#325",
	"PeŸe 2 [#326",
		"Bi™¢o—i™¡ic£«#" xstr(r3_strg_t),
		"Bœ™ pe˜yŸ­—a¡¡®#" xstr(r3_art_t),
		"ac£o£a ¢yŸ«cy,¢/˜#" xstr(r3_frq),
		"Tpœ—. ¢epio™y,ce#" xstr(r3_pp),
		"Mi¡i . i ¢yŸ«c,ce#" xstr(r3_min),
	"PeŸe 3 ]#327",
		"Bi™¢o—i™¡ic£«#" xstr(r4_strg_t),
		"Bœ™ pe˜yŸ­—a¡¡®#" xstr(r4_art_t),
		"ac£o£a ¢yŸ«cy,¢/˜#" xstr(r4_frq),
		"Tpœ—. ¢epio™y,ce#" xstr(r4_pp),
		"Mi¡i . i ¢yŸ«c,ce#" xstr(r4_min),
"Mo—a#" xstr(sprache_t),
"…a—o™c«a yc£a¡o—a#" xstr(set_nt),
"ƒa¡i ¢pœŸa™y#328",
	"Ho ep ¢pœŸa™y#" xstr(dev_nr_ix),
	"Bepci® ¢po˜pa œ#" xstr(softver_ix),
	"Bepci® ¢po˜pa œ ¦ac£.y¢pa—Ÿ#" xstr(soft_strg_ix),
	"ƒa£a —œ˜o£o—Ÿe¡¡®#" xstr(mdate_in),
	"Bœpo–¡œ#329",
		"dinotec GmbH",
		"Phillipp-Reis Str. 28",
		"D-61130 Nidderau",
		"Tel: 0049 (0)6187 41379-0",
		"Hotline: 0049 (0)6187 41379-72",
		"www.dinotec.de",
		"service@dinotec.de",
"Baa¡£¡o",
"Be¡£œŸ®£op",
"Šc£a¡o—a ¢pa¥­±",
"Tpœ—o˜a",
"…¡œše¡¡® pH",
"‰i™—œ¨e¡¡® ›¡a¦. pH",
"Redox",
"CL2",
"CL2,pH",
"CL2,pH,Redox",
"pH",
"pH,Redox",
"e› —œ ip. o–Ÿa™¡.",
"30",
"60",
"90",
"150",
"200",
"300",
"—c£a¡o—œ£œ",
"cœ¡y£œ",
"Bœ ¡e¡œ",
"Po–o¦œ pešœ ",
"Ha¢.± ¡.coŸ«.po›¦.",
"…a¢o—¡œ£œ ®¦e²y",
"Ha¢o—¡.yc£a¡o—œ",
"Šc£a¡ ˜o£o—a",
"E ¡ic£« coŸ«o—.po›¦œ¡y ›a¢o—¡.",
"•¦e²a ›a¢o—¡e¡a",
"Šc£a¡o—a ¡a¢o—¡e¡a",
"‰pœŸa™ —œpo–Ÿ®± ¢po™y£",
"Pe˜e¡epa¥i® ¢o '®§y—a¦a®",
"Tpœ—o˜a Pešœ  yc£a¡o—œ",
"Š—a˜a ¢epe—ipœ£œ yc£a¡. ™e›i¡¤.",
"Tpœ—o˜a Bœ ip pi—¡® ˜o£o—.¢po™y£y",
"Tpœ—o˜a ‰epeŸ. ± ic£« ¢po™.",
"Tpœ—o˜a …a¡a™£o —œc.¡a¢py˜a ®¦e²œ",
"Tpœ—o˜a C£py  ›a¡a™£o —œcoœ",
"Tpœ—o˜a C£py  ›a¡a™£o ¡œ›«œ",
"Tpœ—o˜a ‰o£i ›a¡a™£o —eŸœœ",
"Tpœ—o˜a ‰o£o ›a¡a™£o  aŸe¡«œ",
"Tpœ—o˜a  ic£« coŸ«o—o˜o po›¦œ¡y",
"B œ.-Bœ ¡.",
"ac£o£a ¢yŸ«cy",
"‰yŸ«c-¢ay›a",
"£a",
"¡i",
"py¦¡a",
"a—£o a£œ¦¡œ",
"Š—a˜a ¢i™—œ¨. ›¡a¦ CL2",
"Š—a˜a ›¡œš. ›¡a¦. CL2",
"‰o¢epe™š. ¢o£e¡¥. —œ ip. eŸe£po™y",
"Bepx¡± £pœ—. ›¡a¦e¡¡® CL2",
"Hœš¡± £pœ—. ›¡a¦e¡¡® CL2",
"Bepx¡± £pœ—. ›¡a¦e¡¡® pH",
"Hœš¡± £pœ—. ›¡a¦e¡¡® pH",
"Tpœ—oš¡e ›¡a¦e¡¡® Redox",
"‰o¢epe™še¡¡® ›¡a¦. Redox",
"‰o¢epe™še¡¡® ¢i™—œ¨. ›¡a¦. pH",
"‰o¢epe™še¡¡® ›¡œš. ›¡a¦. pH",
"He™oc£a¦a —œ ip­—. —o™œ",
"Bœ ip pi—¡®",
"‚epo¡o—œ —œ œa¦",
"Bœ ip­—a¡¡® ¢o£oy",
"…o—¡i§¡± ¢pœ¢œ¡e¡¡® ™o›y—a¡¡®",
"He a± ¢i™Ÿ­¦e¡¡® ™o epy­¦e ¦ac£i",
"‰o œŸa py£œ›¡œ Cl2",
"‰o œŸa py£œ›¡œ pH",
"‰o œŸa ¡yŸ«o—o² £o¦œ",
"Ka¡ic£pa › pH ¢opoš¡®",
"ac ™o›a¥i² ™e›i¡¤e¥i² ¢epe—œ¨e¡œ",
"ac ™o›a¥i² ¢o—œ¨e¡.pH ¢epe—œ¨e¡œ",
"ac ™o›a¥i² ›¡œše¡¡® pH ¢epe—œ¨e¡œ",
"ƒi± ›a£pœ a —Ÿ­¦e¡¡®",
"ac ™o›y—a¡¡® ™e›i¡¤e¥i²",
"ac ™o›y—a¡¡® pH",
"Meši pe˜yŸ.™e›i¡¤e¥i² ¢epe—œ¨e¡i",
"Meši pe˜yŸ.™e›i¡¤e¥i² ¡e ™oc®˜¡y£i",
"Meši pe˜yŸ. pH ¢epe—œ¨e¡i",
"Meši pe˜yŸ. pH ¡e ™oc®˜¡y£i",
"Tpœ—o˜a ƒyše —œcoa £e ¢ep.¢po™y£a",
"Š—a˜a ™yše —œcoa £e ¢ep. ¢po™y£a",
"Š—a˜a ™yše ¡œ›«a £e ¢ep.¢po™y£a",
"Tpœ—o˜a Ha¢py˜a ®¦e²œ ›a¡.¡œ›«a",
"‰poc£o ¡acoŸo™šyc® pa¨o­ —o™o­!",
"± ic£« ˜o£o—o˜o ¢po™y£y ¢opoš¡®",
"ƒo›y—a¡¡® Bœ ¡e¡œ", 
"EŸe£poŸi› Bœ ¡e¡œ",
"Be¡£œŸ®£op ¢o¦a£.¢yc",					//   =vent_vor_txt
"Be¡£œŸ®£op Pyx ¢o i¡ep¥i²",					//   =vent_nach_txt
"‰o¢epe™še¡¡® a—api¡o² o¢epa¥i²",
"0 - 1  ˜/Ÿ",
"0 - 10  ˜/Ÿ",
"‰po¥ec ›a¢ycy, ›a¦ea£e",
"Hi e¥«a",
"A¡˜Ÿic«a",
"‹pa¡¥y›«a",
"c¢a¡c«a",
"‰oŸ«c«a",
"Špa²¡c«a",
"Pocic«a",
"I£aŸic«a",
"ec«a",
"CŸo—e¡c«a",
"Xop—a£c«a",
"Š˜opc«a",
"Py y¡c«a",
"‚oŸŸa¡™c«a",
"Cep–c«a",
"Communication#" xstr(komm_t),
"Modbus",
"dinoREMOTE",
"WLAN#330",
	"IP: #" xstr(ip_en),							// komma 124
	"SSID#" xstr(ssid_en),							// komma 125	
	"Signal strength,%#" xstr(sign_en),				// komma 126
	"Connected#" xstr(conn_en),						// komma 127
	"Server connection#" xstr(server_en),			// komma 127
	"WLAN reset#" xstr(wreset_en)					// komma 127

};
