const char* text_fr[] = {
"MENU PRINCIPAL",
"Code#" xstr(code0_in),
"Mode l'ålectrolys.#" xstr(btr_art_t),
"Configuration appareil#300",
	"Type d'installation,g/h#" xstr(anl_typ_t),
	"Adresse bus#" xstr(sh_adr),
	"Contraste#" xstr(contr),
	"Technique de mesure#" xstr(msr_t),
	"Plage de mesure Cl2#" xstr(mgl_t),
	"Cl2 pH compenså#" xstr(set_nt),
"åtalonnage#301",
	"åtalonnage sonde de chlore#302",
		"Valeur mesuråe,mg/l#" xstr(cl_val_ix),
		"Pente,mV#" xstr(cl_sth_in),
		"Tension d'entråe,mV#" xstr(cl_mv_ix),
		"Sauvegarder Uentråe#" xstr(set_nt),
		"Uentråe sauvegardåe,mV#" xstr(uin_saved_ix),
		"Point zåro,mV#" xstr(cl_mv0_in),
		"Dåfinition du point zåro#" xstr(set_nt),
		"Valeur DPD,mg/l#" xstr(cl_dpd_in),
		"RAZ åtalonnage#" xstr(set_nt),
		"Fin NAE en, min#" xstr(aer_min_ix),
		"åtalonnage pas possible",
		"Valeur mesuråe < 0,1 mg/l",
		"Valeur mesuråe < 0,05 mg/l",
	"åtalonnage pH#303",
		"Valeur mesuråe,pH#" xstr(ph_ix),
		"Pente,mV/pH#" xstr(ph_sth_in),
		"Point zåro,mV#" xstr(ph_null_in),
		"Tension d'entråe,mV#" xstr(ph_mv_ix),
		"åtalonnage pH4/7#" xstr(ph_dpd2_in),
		"RAZ åtalonnage#" xstr(set_nt),
"Valeurs de consigne syst.de mesure#304",
	"Temporisation de mise en marche,min#" xstr(on_dly),
	"Valeurs de consigne Cl2#305",
		"Valeurs de consigne CL2#306",
			"Seuil d'alarme supårieur,mg/l#" xstr(cl_alr_ob),
			"Seuil d'avertis.supårieur,mg/l#" xstr(cl_wr_ob),
			"Valeur de consigne,mg/l#" xstr(cl_soll),
			"Seuil d'avertis.infårieur,mg/l#" xstr(cl_wr_un),
			"Seuil d'alarme infårieur,mg/l#" xstr(cl_alr_un),
			"Temporisation d'alarme,min#" xstr(cl_alr_dly),
		"Rågulation CL2#307",
			"Bande P,mg/l#" xstr(cl_p),
			"Temps de correction,sec#" xstr(cl_i),
			"Hyståråsis,mg/l#" xstr(cl_hys),
		"Råglages de dosage#308",
			"Dosage continu manuel,min#" xstr(cl_man_dos),
			"Mett.en marche le dosag.cont.#" xstr(set_nt),
			"Surveill.du temps de dosage,min#" xstr(cl_dos_watch),
	"Valeurs pH#309",
		"Valeurs de consigne pH#310",
			"Seuil d'alarme supårieur,pH#" xstr(ph_alr_ob),
			"Seuil d'avertis.supårieur,pH#" xstr(ph_wr_ob),
			"Valeur de consigne,pH#" xstr(ph_soll),
			"Seuil d'avertis.infårieur,pH#" xstr(ph_wr_un),
			"Seuil d'alarme infårieur,pH#" xstr(ph_alr_un),
			"Temporisation d'alarme,min#" xstr(alr_dly_ph),
		"Rågulation pH#311",
			"Bande P,pH#" xstr(ph_p),
			"Hyståråsis,pH#" xstr(ph_hys),
			"Temps de correction ,sec#" xstr(ph_zi),
			"Zone morte,pH#" xstr(totband_ph),
		"Råglages de dosage#312",
			"Dosage continu manuel,min#" xstr(ph_man_dos),
			"Mett.en marche le dosag.cont.#" xstr(set_nt),
			"Surveill.du temps de dosage,min#" xstr(ph_dos_watch),
	"Redox#313",
		"Valeurs de consigne Redox#314",
			"Valeur mesuråe,mV#" xstr(rx_ix),
			"Valeur de consigne,mV#" xstr(rx_soll),
			"Seuil d'avertis.infårieur,mV#" xstr(rx_wr_un),
			"Seuil d'alarme infårieur,mV#" xstr(rx_alr_un),
			"Temporisation d'alarme,min#" xstr(alr_dly_rx),
		"Rågulation Redox#315",
			"Bande P,mV#" xstr(rx_p),
			"Hyståråsis,mV#" xstr(rx_hys),
		"Råglages de dosage#316",
			"Dosage continu manuel,min#" xstr(rx_man_dos),
			"Mett.en marche le dosag.cont.#" xstr(set_nt),
			"Surveill.du temps de dosage,min#" xstr(rx_dos_watch),
	"Surveillance de l'eau de mesure#317",
		"Mode#" xstr(mw_art_t),
		"Dåbit,l/h#" xstr(fl_aktl_mw_ix),
		"Taux de dåbit,P/l#" xstr(fl_rate_mw),
		"Dåbit mini,l/h#" xstr(min_fl_mw),
		"Compensation,l/h#" xstr(flow_komp),
	"Date et heure#318",
		"Heures#" xstr(std_1),
		"Minutes#" xstr(min_1),
		"Jour#" xstr(day),
		"Mois#" xstr(mon),
		"an#" xstr(year),
	"NAE#319",
		"Heures#" xstr(asr_std),
		"Minutes#" xstr(asr_min),
		"Nombre NAE par jour#" xstr(asr_day),
		"Dåmarrage manuel NAE#" xstr(set_nt),
	"Tempårature#320",
		"Compensation#" xstr(t_comp_t),
		"Compensation manuelle,C#" xstr(t_man_comp),
		"Correction,C#" xstr(t_korr),
"Valeurs de consigne ålectrolyse#321",
	"Electrolyse#322",
		"Dosage de saumure,%#" xstr(sole_dos),
		"Surveil.råalimentat.saumure,min#" xstr(sole_nspw),
		"Limiter la tempårature,C#" xstr(temp_lim_t),
		"Temp.produit maxi,C#" xstr(maxt),
		"Concentration en CL2,g/l#" xstr(cl_konz),
		"Dåbit,l/h#" xstr(flow_ely),
		"Correction,C#" xstr(t0_korr),
		"Surveillance de la tension#" xstr(v_monitus_t),
	"Bac de stockage#323",
		"Surveill. du niveau#" xstr(lev_art_t),
		"Niveau trop-plein,cm#" xstr(prodlev_ovfl),
		"Niveau maxi,cm#" xstr(prodlev_max),
		"Niveau mini,cm#" xstr(prodlev_min),
		"Opåration d'urgence#" xstr(not_btr_t),
		"Temps d'exåcution d'urgence,min#" xstr(not_zeit),
	"Ventilateur#324",
		"Temps de marche pråalable,sec#" xstr(luft_vor),
		"Temps de poursuite,min#" xstr(luft_nach),
"Relais#325",
	"Relais 2 [#326",
		"Affectation#" xstr(r3_strg_t),
		"Mode de rågulation#" xstr(r3_art_t),
		"Fråquence d'impulsion,P/h#" xstr(r3_frq),
		"Duråe de påriode,sec#" xstr(r3_pp),
		"Impulsion mini,sec#" xstr(r3_min),
	"Relais 3 ]#327",
		"Affectation#" xstr(r4_strg_t),
		"Mode de rågulation#" xstr(r4_art_t),
		"Fråquence d'impulsion,P/h#" xstr(r4_frq),
		"Duråe de påriode,sec#" xstr(r4_pp),
		"Impulsion mini,sec#" xstr(r4_min),
"Langue#" xstr(sprache_t),
"Paramåtrages usine#" xstr(set_nt),
"Donnåes de l'appareil:#328",
	"Numåro de l'appareil#" xstr(dev_nr_ix),
	"Version logiciel#" xstr(softver_ix),
	"Contrële de version du logiciel#" xstr(soft_strg_ix),
	"Date de fabrication#" xstr(mdate_in),
	"Fabricant#329",
		"dinotec GmbH",
		"Phillipp-Reis Str. 28",
		"D-61130 Nidderau",
		"Tel: 0049 (0)6187 41379-0",
		"Hotline: 0049 (0)6187 41379-72",
		"www.dinotec.de",
		"service@dinotec.de",
"pas occupå",
"Ventilateur",
"Installation en marche",
"Alarme",
"Abaissement du pH",
"Augmentation du pH",
"Redox",
"CL2",
"CL2,pH",
"CL2,pH,Redox",
"pH",
"pH,Redox",
"sans systçme de mesure",
"30",
"60",
"90",
"150",
"200",
"300",
"dåfinir",
"remettre â zåro",
"Dåsactivå",
"Rågime normal",
"Rempl.bac â saum.",
"Rempl.la cell.",
"Rempl.instal.",
"Installation préte",
"Bac â saumure rempli",
"Cellule remplie",
"Installation remplie",
"L'ålectrolyseur est en production",
"L'adoucisseur rågånçre",
"Alarme Fonctionnement du systçme",
"Avertis. Contrël.l'instal.DES",
"Alarme Mesure niveau du bac de stoc",
"Alarme Trop-plein bac de stockage",
"Alarme Tension de cell. trop ålevåe",
"Alarme Courant trop ålevå",
"Alarme Courant trop faible",
"Alarme Dåbit trop ålevå",
"Alarme Dåbit trop faible",
"Alarme Niveau bac â saumure",
"Marche/Arrét",
"Fråquence d'impulsion",
"Impulsion/Repos",
"Oui",
"Non",
"Manuelle",
"automatique",
"Avertis.CL2 seuil haut",
"Avertis.CL2 seuil bas",
"Avertis. Contrëler sonde POT",
"Alarme CL2 seuil haut",
"Alarme CL2 seuil bas",
"Alarme pH seuil haut",
"Alarme pH seuil bas",
"Alarme Redox",
"Avertis.Redox",
"Avertis.pH seuil haut",
"Avertis.pH seuil bas",
"Manque d'eau de mesure",
"Mesure de niveau",
"Interrup.â flotteur",
"Mesure de dåbit",
"Arrét dosage externe",
"Pas de liaison â l'unitå de comman.",
"Erreur de pente Cl2",
"Erreur de pente du pH ",
"Erreur de zåro",
"Bidon pH est vide",
"Dåpassement tps dosage dåsinfect.",
"Dåpassement tps dosage augm. pH",
"Dåpassement tps dosage abaiss. pH",
"Temporis. mise en marche activåe",
"Dosage continu dåsinf. en cours",
"Dosage continu pH en cours",
"Dåpasse seuil rågulation dåsinf.",
"Sous seuil rågulation dåsinfect.",
"Dåpasse seuil de rågulation pH",
"Sous seuil de rågulation pH",
"Alarme Tempårat.du prod.trop ålevåe",
"Avertis.Tempår.du prod.ålevåe",
"Avertis.Tempår.du prod.basse",
"Alarme Tension de cell. trop basse",
"Tout simpl.le plaisir la meil.des eaux!",
"Bac de stockage est vide",
"Dosage dåsactivå", 
"ålectrolyse dåsactivå",
"Ventilateur en marche pråal.",					//   =vent_vor_txt
"Ventilateur en poursuite",					//   =vent_nach_txt
"Avertissement opåration d'urgence",					
"0 - 1 mg/l",
"0 - 10 mg/l",
"Dåmarrage, veuillez patienter",
"Allemand",
"Anglais",
"Franãais",
"Espagnol",
"Polonais",
"Ukrainien",
"Russe",
"Italien",
"Tchçque",
"Slovçne",
"Croate",
"Hongrois",
"Roumain",
"Nåerlandais",
"Serbe",
"Communication#" xstr(komm_t),
"Modbus",
"dinoREMOTE",
"WLAN#330",
	"IP: #" xstr(ip_en),							// komma 124
	"SSID#" xstr(ssid_en),							// komma 125	
	"Force du signal,%#" xstr(sign_en),				// komma 126
	"Connecte#" xstr(conn_en),						// komma 127
	"Connexion au serveur#" xstr(server_en),			// komma 127
	"WLAN reset#" xstr(wreset_en)					// komma 127

};
