char* text_cz[] = {
"HLAVNí MENU",
"Kód#" xstr(code0_in),
"Elektrolyza provoz#" xstr(btr_art_t),
"Konfigurace pøístroje#300",
	"Typ zaøízení,g/h#" xstr(anl_typ_t),
	"Bus adresa#" xstr(sh_adr),
	"Kontrast#" xstr(contr),
	"Mìøící technika#" xstr(msr_t),
	"Rozsah merení Cl2#" xstr(mgl_t),
	"Cl2 pH kompenzací#" xstr(set_nt),
"Kalibrace#301",
	"Kalibrace chlorové sondy#302",
		"Mìø.hodnota,mg/l#" xstr(cl_val_ix),
		"Strmost,mV#" xstr(cl_sth_in),
		"Vstupní napìtí,mV#" xstr(cl_mv_ix),
		"Uložit Uein#" xstr(set_nt),
		"Uein uložen,mV#" xstr(uin_saved_ix),
		"Nulový bod,mV#" xstr(cl_mv0_in),
		"Stanovit nulový bod#" xstr(set_nt),
		"DPD-hodnota,mg/l#" xstr(cl_dpd_in),
		"Kalibrační reset#" xstr(set_nt),
		"Konec AER, Min#" xstr(aer_min_ix),
		"Kalibrace není možná",
		"Mìø.hodnota < 0,1 mg/l",
		"Mìø.hodnota < 0,05 mg/l",
	"Kalibrace pH#303",
		"Mìø.hodnota,pH#" xstr(ph_ix),
		"Strmost,mV/pH#" xstr(ph_sth_in),
		"Nulový bod,mV#" xstr(ph_null_in),
		"Vstupní napìtí,mV#" xstr(ph_mv_ix),
		"Kalibrace pH 4/7#" xstr(ph_dpd2_in),
		"Kalibrační reset#" xstr(set_nt),
"Nast.hodnota mìøící techniky#304",
	"časovì zpoždìné spínání,Min#" xstr(on_dly),
	"Nast.hodnota Cl2#305",
		"Nast.hodnota CL2#306",
			"Alarm. hodn. nahoøe,mg/l#" xstr(cl_alr_ob),
			"Var. hod. nahoøe,mg/l#" xstr(cl_wr_ob),
			"Požadovaná hodnota,mg/l#" xstr(cl_soll),
			"Varovná hodnota spodní,mg/l#" xstr(cl_wr_un),
			"Alarmová hodnota spodní,mg/l#" xstr(cl_alr_un),
			"Alarmové zpoždìní,Min#" xstr(cl_alr_dly),
		"Regulace CL2#307",
			"P-oblast,mg/l#" xstr(cl_p),
			"Integrační časová hodnota ,Sek#" xstr(cl_i),
			"Hystereze,mg/l#" xstr(cl_hys),
		"Nastavení dávkování#308",
			"ruč. dávkování,Min#" xstr(cl_man_dos),
			"Trvalé dávkování zapnuto#" xstr(set_nt),
			"Hlídání času dávkování ,Min#" xstr(cl_dos_watch),
	"pH-hodnota#309",
		"Nast.hodnota pH   #310",
			"Alarm. hodn. nahoøe,pH#" xstr(ph_alr_ob),
			"Var. hod. nahoøe,pH#" xstr(ph_wr_ob),
			"Požadovaná hodnota,pH#" xstr(ph_soll),
			"Varovná hodnota spodní,pH#" xstr(ph_wr_un),
			"Alarmová hodnota spodní,pH#" xstr(ph_alr_un),
			"Alarmové zpoždìní,Min#" xstr(alr_dly_ph),
		"Regulace pH#311",
			"P-oblast,pH#" xstr(ph_p),
			"Hystereze,pH#" xstr(ph_hys),
			"Integrační časová hodnota ,Sek#" xstr(ph_zi),
			"Mrtvý bod,pH#" xstr(totband_ph),
		"Nastavení dávkování#312",
			"ruč. dávkování,Min#" xstr(ph_man_dos),
			"Trvalé dávkování zapnuto#" xstr(set_nt),
			"Hlídání času dávkování ,Min#" xstr(ph_dos_watch),
	"Redox#313",
		"Nast.hodnota Redox#314",
			"Mìø.hodnota,mV#" xstr(rx_ix),
			"Požadovaná hodnota,mV#" xstr(rx_soll),
			"Varovná hodnota spodní,mV#" xstr(rx_wr_un),
			"Alarmová hodnota spodní,mV#" xstr(rx_alr_un),
			"Alarmové zpoždìní,Min#" xstr(alr_dly_rx),
		"Ragulace redox#315",
			"P-oblast,mV#" xstr(rx_p),
			"Hystereze,mV#" xstr(rx_hys),
		"Nastavení dávkování#316",
			"ruč. dávkování,Min#" xstr(rx_man_dos),
			"Trvalé dávkování zapnuto#" xstr(set_nt),
			"Hlídání času dávkování ,Min#" xstr(rx_dos_watch),
	"Hlídání mìøené vody#317",
		"Typ#" xstr(mw_art_t),
		"Průtok,l/h#" xstr(fl_aktl_mw_ix),
		"Míra průtoku,P/l#" xstr(fl_rate_mw),
		"minimální průtok,l/h#" xstr(min_fl_mw),
		"Kompenzace,l/h#" xstr(flow_komp),
	"Datum a čas#318",
		"Hodina#" xstr(std_1),
		"Minuta#" xstr(min_1),
		"Den#" xstr(day),
		"Mìsíc#" xstr(mon),
		"Rok#" xstr(year),
	"AER#319",
		"Hodina#" xstr(asr_std),
		"Minuta#" xstr(asr_min),
		"Počet AER za den#" xstr(asr_day),
		"AER ruční start#" xstr(set_nt),
	"Teplota#320",
		"Kompenzace#" xstr(t_comp_t),
		"Ruční kompenzace,°C#" xstr(t_man_comp),
		"Korekce,°C#" xstr(t_korr),
"Nast.hodnota elektrolýzy#321",
	"Elektrolýza#322",
		"Dávkování solanky,%#" xstr(sole_dos),
		"Hlídání doplnìní solanky,Min#" xstr(sole_nspw),
		"Teplotní limit,°C#" xstr(temp_lim_t),
		"Max. teplota produktu °C#" xstr(maxt),
		"CL2 koncentrace,g/l#" xstr(cl_konz),
		"Durchfluss,l/h#" xstr(flow_ely),
		"Korekce,°C#" xstr(t0_korr),
		"Monitorování napětí#" xstr(v_monitus_t),
	"Produkční tank#323",
		"Sledování hladiny#" xstr(lev_art_t),
		"úroveò pøetečení,cm#" xstr(prodlev_ovfl),
		"Max. hladina,cm#" xstr(prodlev_max),
		"Min. hladina,cm#" xstr(prodlev_min),
	"Ventilátor#324",
		"Doba rozběhu,s#" xstr(luft_vor),
		"Doba doběhu,min#" xstr(luft_nach),
"Relé#325",
	"Relé 3 [#326",
		"Postoupení#" xstr(r3_strg_t),
		"Druh regulace#" xstr(r3_art_t),
		"Puls.frekvence,P/h#" xstr(r3_frq),
		"Doba kmitu,Sek#" xstr(r3_pp),
		"Minimální impuls,Sek#" xstr(r3_min),
	"Relé 4 ]#327",
		"Postoupení#" xstr(r4_strg_t),
		"Druh regulace#" xstr(r4_art_t),
		"Puls.frekvence,P/h#" xstr(r4_frq),
		"Doba kmitu,Sek#" xstr(r4_pp),
		"Minimální impuls,Sek#" xstr(r4_min),
"Jazyk#" xstr(sprache_t),
"Nastavení z výroby#" xstr(set_nt),
"Data pøístroje#328",
	"číslo pøístroje#" xstr(dev_nr_ix),
	"Stav softwaru#" xstr(softver_in),
	"Datum výroby#" xstr(mdate_in),
	"Výrobce#329",
		"dinotec GmbH",
		"Phillipp-Reis Str. 28",
		"D-61130 Nidderau",
		"Tel: 0049 (0)6187 41379-0",
		"Hotline: 0049 (0)6187 41379-72",
		"www.dinotec.de",
		"service@dinotec.de",
"Frei",
"Ventilátor",
"Zaøízení v provozu",
"Alarm",
"pH snížit",
"pH zvýšit",
"Redox",
"CL2",
"CL2,pH",
"CL2,pH,Redox",
"pH",
"pH,Redox",
"bez mìøící techniky",
"30",
"60",
"90",
"150",
"200",
"300",
"dosadit",
"reset",
"Vypnuté",
"Normální provoz",
"Tank solan.napl.",
"Celu naplnit",
"Zaøízení naplnit",
"Zaøízení je hotovo",
"Tank solanky naplnìn",
"Cela naplnìná",
"Zaøízení naplnìno",
"Zaøízení vyrábí",
"Tvrdost regenerována",
"Zabezpečovací systém v provozu",
"Výstrahu DES-zaøízení pøezkoušet",
"Alarm mìøení hladin.produk.v nádrži",
"Alarm pøetečení produkční nádrže",
"Alarm napìtí cely pøíliš vysoký",
"Alarm proud pøíliš vysoký",
"Alarm proud pøíliš nízký",
"Alarm průtoku pøíliš vysoký",
"Alarm průtoku pøíliš nízký",
"Alarm hladiny nádrž.solného roztoku",
"Zap./ Vyp",
"Puls.frekvence",
"Puls/Pøestávka",
"Ano",
"ne",
"ruční",
"automaticky",
"Výstraha Cl2 vysoko",
"Výstraha Cl2 nízko",
"Výstrahu POT sondu zkontrolovat",
"Alarm CL2 vysoký",
"Alarm CL2 nízký",
"Alarm pH vysoký",
"Alarm pH nízký",
"Alarm Redox",
"Výstraha redox",
"Výstraha pH vysoko",
"Výstraha pH nízko",
"Hlídání mìøené vody",
"Měření hladiny",
"Plovákový spínač",
"Mìøení průtoku",
"Externí stop dávkování",
"žádné pøipojení k øídídímu dílu",
"Chyba strmosti Cl2",
"Chyba strmosti pH",
"Chyba nulového bodu",
"pH Kanystr je prázdný",
"Dávkovací čas desinfekce pøekročen",
"Dávkovací čas zvýšení pH pøekročen",
"Dávkovací čas snížení pH pøekročen",
"časovì zpoždìné spínání aktivní",
"Trvalé dávkování desinfekce bìží",
"Trvalé dávkování pH bìží",
"Regulační hranice desinf.pøekročena",
"Regulační hranice desinfek.nedosaž.",
"Regulační hranice pH pøekročena",
"Regulační hranice pH nedosažena",
"Alarm teplota produktu vysoká",
"Výstraha teplota produktu vysoká",
"Výstraha teplota produktu nízká",
"Alarm napìtí cely pøíliš nízká",
"Prostì lepší voda!",
"Produkční tank je prázdný",
"Dávkování vypnuté", 
"Elektrolýzy vypnuté",
"Ventilátor, rozběh",					//   =vent_vor_txt
"Ventilátor, doběh",					//   =vent_nach_txt
"0 - 1 mg/l",
"0 - 10 mg/l",
"Nìmecky",
"Anglicky",
"Francouzsky",
"španìlský",
"Polsky",
"Ukrajinsky",
"Rusky",
"Italsky",
"česky",
"Slovinsky",
"Chorvatsky",
"Madarsky",
"Rumunsky",
"Holandsky",
"Srbsky",
};
