const char* text_es[] = {
"MENî PRINCIPAL",
"Cèdigo#" xstr(code0_in),
"Electrèl.funcion.#" xstr(btr_art_t),
"Configuracièn del aparato#300",
	"Tipo de equipo,g/h#" xstr(anl_typ_t),
	"Direccièn BUS#" xstr(sh_adr),
	"Contraste#" xstr(contr),
	"Tåcnicas de medicièn#" xstr(msr_t),
	"Rango de medicièn Cl2#" xstr(mgl_t),
	"Cl2 pH-kompensiert#" xstr(set_nt),
"Calibracièn#301",
	"Calibracièn sonda de cloro#302",
		"Valor de medicièn,mg/l#" xstr(cl_val_ix),
		"Transconductancia,mV#" xstr(cl_sth_in),
		"Tensièn de entrada,mV#" xstr(cl_mv_ix),
		"Almacenar Uein#" xstr(set_nt),
		"Uein guardado,mV#" xstr(uin_saved_ix),
		"Punto cero,mV#" xstr(cl_mv0_in),
		"Ajuste de punto cero#" xstr(set_nt),
		"Valor DPD,mg/l#" xstr(cl_dpd_in),
		"Reinicio calibracièn#" xstr(set_nt),
		"Fin ciclo AER, Min#" xstr(aer_min_ix),
		"No puede efectuarse la calibracièn",
		"Valor de medicièn < 0,1 mg/l",
		"Valor de medicièn < 0,05 mg/l",
	"Calibracièn de pH#303",
		"Valor de medicièn,pH#" xstr(ph_ix),
		"Transconductancia,mV/pH#" xstr(ph_sth_in),
		"Punto cero,mV#" xstr(ph_null_in),
		"Tensièn de entrada,mV#" xstr(ph_mv_ix),
		"Calibracièn pH 4/7#" xstr(ph_dpd2_in),
		"Reinicio calibracièn#" xstr(set_nt),
"Valores nominales de medicièn#304",
	"Retardo de conexièn ,Min#" xstr(on_dly),
	"Valores nominales CL2#305",
		"Valores nominales CL2#306",
			"Valor superior de alarma,mg/l#" xstr(cl_alr_ob),
			"Valor superior de aviso,mg/l#" xstr(cl_wr_ob),
			"Valor nominal:,mg/l#" xstr(cl_soll),
			"Valor inferior de aviso,mg/l#" xstr(cl_wr_un),
			"Valor inferior de alarma,mg/l#" xstr(cl_alr_un),
			"Retardo conexièn de alarma,Min#" xstr(cl_alr_dly),
		"Regulacièn CL2#307",
			"àmbito P,mg/l#" xstr(cl_p),
			"Tiempo de accièn integral,Sek#" xstr(cl_i),
			"Histåresis,mg/l#" xstr(cl_hys),
		"Ajustes de dosificacièn#308",
			"Dosif.manual continua,Min#" xstr(cl_man_dos),
			"Conectar dosificacièn continua#" xstr(set_nt),
			"Control del tiempo de dosificacièn ,Min#" xstr(cl_dos_watch),
	"Valores de pH#309",
		"Valores nominales de pH#310",
			"Valor superior de alarma,pH#" xstr(ph_alr_ob),
			"Valor superior de aviso,pH#" xstr(ph_wr_ob),
			"Valor nominal:,pH#" xstr(ph_soll),
			"Valor inferior de aviso,pH#" xstr(ph_wr_un),
			"Valor inferior de alarma,pH#" xstr(ph_alr_un),
			"Retardo conexièn de alarma,Min#" xstr(alr_dly_ph),
		"Regulacièn pH#311",
			"àmbito P,pH#" xstr(ph_p),
			"Histåresis,pH#" xstr(ph_hys),
			"Tiempo de accièn integral,Sek#" xstr(ph_zi),
			"Banda muerta,pH#" xstr(totband_ph),
		"Ajustes de dosificacièn#312",
			"Dosif.manual continua,Min#" xstr(ph_man_dos),
			"Conectar dosificacièn continua#" xstr(set_nt),
			"Control del tiempo de dosificacièn ,Min#" xstr(ph_dos_watch),
	"Redox#313",
		"Valores nominales Redox#314",
			"Valor de medicièn,mV#" xstr(rx_ix),
			"Valor nominal:,mV#" xstr(rx_soll),
			"Valor inferior de aviso,mV#" xstr(rx_wr_un),
			"Valor inferior de alarma,mV#" xstr(rx_alr_un),
			"Retardo conexièn de alarma,Min#" xstr(alr_dly_rx),
		"Regulacièn Redox#315",
			"àmbito P,mV#" xstr(rx_p),
			"Histåresis,mV#" xstr(rx_hys),
		"Ajustes de dosificacièn#316",
			"Dosif.manual continua,Min#" xstr(rx_man_dos),
			"Conectar dosificacièn continua#" xstr(set_nt),
			"Control del tiempo de dosificacièn ,Min#" xstr(rx_dos_watch),
	"Control del agua de medicièn#317",
		"Tipo#" xstr(mw_art_t),
		"Circulacièn,l/h#" xstr(fl_aktl_mw_ix),
		"Volumen de circulacièn:,P/l#" xstr(fl_rate_mw),
		"Circulacièn mínima,l/h#" xstr(min_fl_mw),
		"Compensacièn,l/h#" xstr(flow_komp),
	"Fecha y hora#318",
		"Horas#" xstr(std_1),
		"Minutos#" xstr(min_1),
		"Día#" xstr(day),
		"Mes#" xstr(mon),
		"Aìo#" xstr(year),
	"AER#319",
		"Horas#" xstr(asr_std),
		"Minutos#" xstr(asr_min),
		"Nîmero de ciclos AER al día#" xstr(asr_day),
		"Activ.manual del proceso AER#" xstr(set_nt),
	"Temperatura#320",
		"Compensacièn#" xstr(t_comp_t),
		"Compensacièn manual,C#" xstr(t_man_comp),
		"Correccièn,C#" xstr(t_korr),
"Valores nominales electrolisis#321",
	"Electrolisis#322",
		"Dosificacièn de salmuera,%#" xstr(sole_dos),
		"Control reposicièn salmuera,Min#" xstr(sole_nspw),
		"Limitar temperatura,C#" xstr(temp_lim_t),
		"Màx.termperatura prod.C#" xstr(maxt),
		"Concentracièn CL2,g/l#" xstr(cl_konz),
		"Circulacièn,l/h#" xstr(flow_ely),
		"Correccièn,C#" xstr(t0_korr),
		"Supervisièn de la tensièn#" xstr(v_monitus_t),
	"Tanque de producto#323",
		"monitor.de niveles#" xstr(lev_art_t),
		"Desbordamiento de nivel,cm#" xstr(prodlev_ovfl),
		"Nivel màx.,cm#" xstr(prodlev_max),
		"Nivel mín.,cm#" xstr(prodlev_min),
		"Operacièn de emergencia#" xstr(not_btr_t),
		"Marcha de emergencia,min#" xstr(not_zeit),
	"Ventilador#324",
		"Tiempo de arranque,seg#" xstr(luft_vor),
		"Tiempo funcion.por inercia,min#" xstr(luft_nach),
"Relå#325",
	"Relå 2 [#326",
		"Asignacièn#" xstr(r3_strg_t),
		"Tipo de regulador#" xstr(r3_art_t),
		"Frecuencia de pulsos,P/h#" xstr(r3_frq),
		"Duracièn periodos,Sek#" xstr(r3_pp),
		"Impulso mínimo,Sek#" xstr(r3_min),
	"Relå 3 ]#327",
		"Asignacièn#" xstr(r4_strg_t),
		"Tipo de regulador#" xstr(r4_art_t),
		"Frecuencia de pulsos,P/h#" xstr(r4_frq),
		"Duracièn periodos,Sek#" xstr(r4_pp),
		"Impulso mínimo,Sek#" xstr(r4_min),
"Idioma#" xstr(sprache_t),
"Ajuste de fàbrica#" xstr(set_nt),
"Datos del aparato#328",
	"Nîmero de aparato#" xstr(dev_nr_ix),
	"Versièn software#" xstr(softver_ix),
	"Versièn Software control#" xstr(soft_strg_ix),
	"Fecha de fabricacièn#" xstr(mdate_in),
	"Fabricante#329",
		"dinotec GmbH",
		"Phillipp-Reis Str. 28",
		"D-61130 Nidderau",
		"Tel: 0049 (0)6187 41379-0",
		"Hotline: 0049 (0)6187 41379-72",
		"www.dinotec.de",
		"service@dinotec.de",
"Frei",
"Ventilador",
"Equipo en funcion.",
"Alarma",
"Reducir pH",
"Elevar pH",
"Redox",
"CL2",
"CL2,pH",
"CL2,pH,Redox",
"pH",
"pH,Redox",
"Sin equipo de medicièn",
"30",
"60",
"90",
"150",
"200",
"300",
"fijar",
"reiniciar",
"Desconectado",
"Funcion.normal",
"Llenar tanque salm.",
"Rellenar cålula",
"Llenar equipo",
"Equipo preparado",
"Tanque de salmuera lleno",
"Cålula llena",
"Equipo lleno",
"Equipo produciendo",
"Regeneracièn del desendurecedor",
"Alarma funcionamiento de sistema",
"Aviso controlar disposit.DES",
"Alar.nivel de medic.tanque de prod.",
"Alar.desbordam.tanque de producto",
"Alarma tensièn en cålula demas.alta",
"Alarma corriente demasiado alta",
"Alarma corriente demasiado baja",
"Alarma circulacièn demasiado alta",
"Alarma circulacièn demasiado baja",
"Alarma nivel tanque de salmuera",
"Activo/Inactivo",
"Frecuencia de pulsos",
"Pulso / Pausa",
"Si",
"No",
"manual",
"Automàtica",
"Aviso valor superior de CL2",
"Aviso valor inferior de CL2",
"Aviso verificac.sonda potenc.",
"Alarma superior CL2",
"Alarma inferior CL2",
"Alarma valor superior pH",
"Alarma valor inferior pH",
"Alarma Redox",
"Aviso Redox",
"Aviso valor superior de pH",
"Aviso valor inferior de pH",
"Falta de agua de medicièn",
"Medicièn de nivel",
"Conector de boya",
"Medicièn de caudal",
"Parada de dosificacièn externa",
"Sin conexièn a elemento de control",
"Error de transconductancia CL2",
"Error de transconductancia de pH ",
"Error de punto cero",
"Recipiente de pH vacío",
"Tiempo dosif.desinfectante exced.",
"Tiempo dosif.elevador de pH exced.",
"Tiempo dosif.reductor de pH exced.",
"Retardo conexièn activado",
"Dosificacièn continua desinfectante",
"Dosificacièn continua de pH",
"Lím.de regul.de desinfec.sobrepas.",
"Lím.de regul.de desinfec.no alcanz.",
"Lím.de regul.de pH sobrepasado",
"Lím.de regul.de pH no alcanzado",
"Alarma temp.del prod.demas.elevada",
"Alarm.temperat.del producto demas.alta",
"Alarm.temperat.del producto demas.baja",
"Alarma tensièn en cålula demas.baja",
"Disfrute sencil.de la mejor agua!",
"Tanque de producto vacío",
"Dosificacièn desconectado", 
"Electrèlisis desconectado",
"Arranque ventilador",					//   =vent_vor_txt
"Funcion. por inercia ventilador",					//   =vent_nach_txt
"Operacièn de emergenc.de advert.",					
"0 - 1 mg/l",
"0 - 10 mg/l",
"Proceso de inicio, por favor espere",
"Alemàn",
"Inglås",
"Francås",
"Espaìol",
"Polaco",
"Ucraniano",
"Ruso",
"Italiano",
"Checo",
"Eslovaco",
"Croata",
"Hîngaro",
"Rumano",
"Holandås",
"Serbio",
"Communication#" xstr(komm_t),
"Modbus",
"dinoREMOTE",
"WLAN#330",
	"IP: #" xstr(ip_en),							// komma 124
	"SSID#" xstr(ssid_en),							// komma 125	
	"Signal strength,%#" xstr(sign_en),				// komma 126
	"Connected#" xstr(conn_en),						// komma 127
	"Server connection#" xstr(server_en),			// komma 127
	"WLAN reset#" xstr(wreset_en)					// komma 127
};
